### PR TITLE
Update gtkdialog to 0.8.5a

### PR DESCRIPTION
**Pull request by dimkr**
Waiting for all builds to finish - I want to make sure the subproject fallback kicks in everywhere without problems.

### CODE REVIEW

**Comment by 01micko** [comment]
I'll delete the current release and set a new 0.8.5a release pending https://github.com/puppylinux-woof-CE/gtkdialog/pull/149

**Comment by dimkr** [comment]
All builds pass, but I had to fix focal64 in [f6f144d](https://github.com/puppylinux-woof-CE/woof-CE/pull/3143/commits/f6f144dc406f2e854734b1e8bed8a2f3c32da953). focal64 has libwayland-dev, but without its dependency, libwayland-bin.

**Comment by 01micko** [comment]
Ok, release is removed. Focal change approved.

**Comment by dimkr** [comment]
> Ok, release is removed. Focal change approved.

Thanks. I'll update the SHA256 when the second 0.8.5a is out.

**Comment by 01micko** [comment]
New [release](https://github.com/puppylinux-woof-CE/gtkdialog/releases/tag/0.8.5a)

**Review by 01micko — APPROVED** [review]

**Pull request merged**
