### PR TITLE
RK3288 Chromebooks support 

### PR DESCRIPTION
**Pull request by dimkr**
This code has been tested against Asus C201. I was able to produce a very basic Puppy that boots via a flash drive and reaches X, with Libreboot installed.

These cheap laptops are particularly interesting because:
- They can be used with _100% free software_ (but with an ath9k_htc WiFi dongle and without 3D acceleration)
- Right now RK3288 is the only laptop board supported by Libreboot that is _still under (mass) production_ (three chromebooks use it - by Asus Hisense and Haier; this pull request should address all three)
- They're a great match for Puppy - a 16 GB SSD and 2 GB of RAM are more than enough
- Right now, no _libre_ distro supports this board and I want Librepup to be the first
- They're so goddamn cheap

There's a long way to go until this Puppy reaches release quality, but most work from now on is under woof-distro. This pull request contains just the required infrastructure changes (the kernel, SD card skeleton, etc').

A Devuan-based, working configuration that produces a traditional, small Puppy image will appear in the testing branch shortly. Currently, I'm building a small repository of ARMv7-optimized, _100% libre_ PET packages that cover the basics (the kernel, some core packages like busybox, JWM, basic GUI applications, etc').

The changes to woof-CE are very minimal: I added a new SD image skeleton, GPT handling in 3builddistro, an ARM directory under kernel-kit and recompiled the (recently updated) tools under support/.

Anyone willing to review the changes? :tired_face:

### CODE REVIEW

**Comment by mavrothal** [comment]
You think we can delay merging till after current testing is merged into master.
Maybe also try to built x86/x86_64 pups from this branch (if you did not already) to make sure that there are no issues with other architectures.
It is in woof anyway already.

**Comment by dimkr** [comment]
These changes affect only woof-arch/arm and the ARM-specific parts of 3builddistro, so nothing will break for x86/x86_64.

**Comment by 01micko** [comment]
@dimkr 

I'm going to pull your fork and build a slacko32 with. I'll do a kernel too.

**Comment by 01micko** [comment]
Apart from librepup and 2createpackages being a little broken it all went well :laughing:

**Comment by dimkr** [comment]
Open issues for all problems you found and assign me, I'll fix 'em during this week.

**Comment by 01micko** [comment]
I did for 2createpackages, its a slacko thing so I'll fix that.

As for librepup, see the forum thread ;-)

**Comment by wdlkmpx** [comment]
I see this branch has conflicts that must be resolved

**Comment by dimkr** [comment]
Yes, there were many changes in testing since the last time I merged testing back into this branch. I'll fix them whenever I find the time to resume my work on this port.

**Comment by wdlkmpx** [comment]
That's why I think woof ce should have periods of turbulence or great tribulations, where puplet builders or whatever it is called are advised to test and report bugs only. Or a testing2 branch, time passes by and this project needs a complete cleanup, but I guess that won't happen

**Comment by 01micko** [comment]
Sorry but I'm closing this. While the conflicts are an easy fix it obviously needs work. I can't see anywhere where package db's and stuff are downloaded to make a build for rk3288.

I'm sure when you get time @dimkr you can bring it up to speed and re-open a pull request.

**Comment by 01micko** [comment]
Oh, I see, its only got the kernel-kit changes etc, sorry.. I could have pulled it I guess, but it does need a modification to `merge2out` so the correct kernel-kit goes to the top level, otherwise we'd need to edit `3builddistro-Z` in a few places.

**Comment by dimkr** [comment]
I'll take care of this.

**Comment by 01micko** [comment]
@dimkr we can delete the `rk3288` branch now, yes?

**Pull request closed without merging**
