### PR TITLE
remove the Original Pup theme

### PR DESCRIPTION
**Pull request by dimkr**
This theme is kind of broken and I don't think anyone uses it really:
- It uses the 4.3.1 era Blue-Moon icon theme, which has many missing icons, and it doesn't mix nicely with the SVG themes
- It doesn't have a matching GTK 3 theme, so some applications (browsers, Transmission, etc') look different
- It uses .jpg wallpapers that don't scale nicely

(Personally, I think Original Pup, z_null, Blue-Moon, ZXP and Deep_blue_bold should be removed, and I'll do that depending on the feedback I receive here.)

Also, changing the default to Bright Mouse will help the Slacko 8.x effort, by exposing its default theme to more users.

### CODE REVIEW

**Comment by peabee** [comment]
> I don't think anyone uses it really:

What makes you think that?? I see no evidence that it needs to be removed - people will notice any inconsistencies and will choose to use it or not on their preference.

**Comment by dimkr** [comment]
@peabee It's hard to argue with the fact no released Puppy uses it as the default, and I don't see anyone using it in screenshots posted in the forums. Please correct me if I'm wrong.

**Comment by peabee** [comment]
My preference - if there are problems with the components - change the components to better ones but keep a theme called "Original Pup" that looks something like older pups..... maybe fix Blue Moon with missing icons?

**Comment by dimkr** [comment]
Maybe 431 can be renamed to "Original Pup" 🤔

**Comment by peabee** [comment]
No 431 does not look like Original ..............

My suggestion:
ICON="/usr/share/pixmaps/puppy/puppy_theme_generic.svg"
PTHEME_ICONS="StandardSvg"
PTHEME_ICONS_GTK="Puppy Standard"
PTHEME_ROX_PIN="Puppy Standard"
PTHEME_ROX_DRIVEICONS="Puppy bottom"
PTHEME_GTK="Raleigh"
PTHEME_JWM_COLOR="Stardust_bright"
PTHEME_JWM_BUTTONS="XPish"
PTHEME_JWM_TRAY="minimal"
PTHEME_JWM_SIZE="normal"
PTHEME_WALL="Sky.svg"
PTHEME_MOUSE="DMZ-White"
PTHEME_GTKDIALOG="default"
PTHEME_PWIDGETS_PROFILE=""
PTHEME_PWIDGETS_THEME=""

**Comment by dimkr** [comment]
This suggestion doesn't solve the problem of inconsistency between GTK+ 2 and 3 ... IMHO only a theme that solves all problems with Original Pup is a good candidate to replace it.

**Comment by peabee** [comment]
Where's the problem???
It looked fine on Slacko64-8

**Comment by dimkr** [comment]
What about GTK+ 3 applications? Raleigh is the default GTK+ 2 theme ... 🙄

**Comment by peabee** [comment]
> What about GTK+ 3 applications? Raleigh is the default GTK+ 2 theme ...

What would be better?

**Comment by dimkr** [comment]
> What would be better?

Any theme that supports both GTK+ 2 and 3 (Flat-grey-rounded, Polished-Blue, Stardust_bright_mouse, Stardust_bright_touch, Stardust_dark_mouse, Stardust_dark_touch).

This is why I'm proposing Bright Mouse as the new default, if Original Pup is dropped.

**Comment by 01micko** [comment]
I say keep it with necessary changes. It's just a bit of tradition and some like that ugly trianglish array of icons in the top left!
```sh
ICON="/usr/share/pixmaps/puppy/puppy.svg"
PTHEME_ICONS="StandardSvg"
PTHEME_ICONS_GTK="Puppy Standard"
PTHEME_ROX_PIN="Puppy Standard"
PTHEME_ROX_DRIVEICONS="Puppy bottom"
PTHEME_GTK="Stardust_bright_mouse"
PTHEME_JWM_COLOR="Stardust_bright"
PTHEME_JWM_BUTTONS="Basix"
PTHEME_JWM_TRAY="minimal"
PTHEME_JWM_SIZE="normal"
PTHEME_WALL="Sky.svg"
PTHEME_MOUSE="DMZ-White"
PTHEME_GTKDIALOG="default"
PTHEME_PWIDGETS_PROFILE=""
PTHEME_PWIDGETS_THEME=""
```
Dark_Blue,  Blue-Moon, ZXP and Deep_blue_bold can all go.

Ziggy has his reasons for z_null, IDK what it is .. @zigbert ?

**Comment by zigbert** [comment]
z_null has only one purpose - clear all comboboxes. This can be done manually, but if first chosen a global theme it activates 12-14 comboboxes...

This can be solved other ways... a new menu, a new button, or simply restart pTheme. My choice at the time I made pTheme was adding z_null. My target was to build the gui as clean as possible. pTheme is after all a rather complex gui-task.

**Comment by dimkr** [comment]
> I say keep it with necessary changes.

:+1:

Your suggestion solves issues 1, 2 and 3 with Original Pup, while also cleaning up Puppy from old (and broken to some degree) themes.

**Comment by peabee** [comment]
> I say keep it with necessary changes. It's just a bit of tradition and some like that ugly trianglish array of icons in the top left!
> 
@01micko suggestion looks fine to me....

Maybe all the plain .svg backgrounds could be "improved" with a bit of subtle "branding".........

[Sky.svg-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6643602/Sky.svg-false.gz)

Screenshot

**Pull request closed without merging**
