### PR TITLE
Add a Puppy 4.1.2 style global theme

### PR DESCRIPTION
**Pull request by dimkr**
4.1.2 was the first Puppy version I used any my favorite even when 4.3 was out. I even remember I liked the "retro" variant better, and loved the default artwork, with Gradient-grey and the (Icelandic?) lake wallpaper. The video https://forum.puppylinux.com/viewtopic.php?f=115&t=3769 was super nostalgic, and inspired me to revive this theme.
 
screeny

### CODE REVIEW

**Comment by 01micko** [comment]
IIRC 'Dingo' was my first too!

EDIT: I think I might spend some time at some point re-creating some of those classic wallpapers in pure SVG.

**Comment by dimkr** [comment]
> EDIT: I think I might spend some time at some point re-creating some of those classic wallpapers in pure SVG.

At first, I thought, let's do a "Material design", flat and minimal remake of the lake wallpaper in SVG.

But even with `decorations="motif"`, the tray and menu are very different from 4.1.x, and a simple gradient (with two colors picked from the lake wallpaper) works better with today's flat JWM style, flat icons, etc'. This theme is far from 100% historical accuracy and I gave up on that idea in the name of practicality.

**Comment by 01micko** [comment]
> This theme is far from 100% historical accuracy and I gave up on that idea in the name of practicality.

'Icelandic' is out of the question! Your idea is fine. I was thinking more of something simple like the 4.3 wallpaper.. 
[here](http://3.bp.blogspot.com/_aXQZQf_h5Mk/SxGHyffGySI/AAAAAAAABLE/Wd7tG_dZTbI/s1600/puppy+desktop.jpg)

**Comment by dimkr** [comment]
> 'Icelandic' is out of the question! Your idea is fine. I was thinking more of something simple like the 4.3 wallpaper..
> [here](http://3.bp.blogspot.com/_aXQZQf_h5Mk/SxGHyffGySI/AAAAAAAABLE/Wd7tG_dZTbI/s1600/puppy+desktop.jpg)

I tried to make a SVG pattern with diagonal stripes in the same colors and failed miserably 😊

**Comment by 01micko** [comment]
Here's a start

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"  viewBox="0 0 800 600">
  
  <!--431 svg mockup -->
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:rgb(121,168,214);stop-opacity:1" />
      <stop offset="100%" style="stop-color:rgb(123,200,230);stop-opacity:1" />
    </linearGradient>
    <linearGradient id="grad2" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:rgb(107,157,206);stop-opacity:1" />
      <stop offset="100%" style="stop-color:rgb(108,197,227);stop-opacity:1" />
    </linearGradient>
  </defs>
  
  <path style="fill:url(#grad1);" d="m 0,0 800,0 0,600 -800,0 z"/>
  <path style="fill:url(#grad2);" d="m 680,520
                                      -300,80-380,0 680,-80
                                      -680,0 0,-100 680,100
                                      -680,-200 0,-100 680,300
                                      -680,-400, 0,-100 680,500
                                      -520,-520 180,0 340,520
                                      -230,-520 140,0 90,520
                                      40,-520 80,0 0,200 -120,320 
                                      "/>
</svg>

```

PNG preview
p431

**Comment by dimkr** [comment]
This is amazing!!!

**Comment by dimkr** [comment]
😊 

screeny

**Comment by 01micko** [comment]
This is close enough

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"  viewBox="0 0 800 600">
  
  <!--431 svg mockup -->
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:rgb(121,168,214);stop-opacity:1" />
      <stop offset="100%" style="stop-color:rgb(123,200,230);stop-opacity:1" />
    </linearGradient>
    <linearGradient id="grad2" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:rgb(107,157,206);stop-opacity:1" />
      <stop offset="100%" style="stop-color:rgb(108,197,227);stop-opacity:1" />
    </linearGradient>
    <radialGradient id="grad3" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
      <stop offset="0%" style="stop-color:rgb(248,247,245);
      stop-opacity:1" />
      <stop offset="100%" style="stop-color:rgb(188,210,239);stop-opacity:1" />
    </radialGradient>
    <radialGradient id="grad4" cx="40%" cy="70%" r="70%" fx="50%" fy="50%">
      <stop offset="0%" style="stop-color:rgb(248,247,245);
      stop-opacity:1" />
      <stop offset="100%" style="stop-color:rgb(212,232,244);stop-opacity:1" />
    </radialGradient>
  </defs>
  
  <!-- rays -->
  <path style="fill:url(#grad1);" d="m 0,0 800,0 0,600 -800,0 z"/>
  <path style="fill:url(#grad2);" d="m 680,520
                                      -300,80-380,0 680,-80
                                      -680,0 0,-100 680,100
                                      -680,-200 0,-100 680,300
                                      -680,-400, 0,-100 680,500
                                      -520,-520 180,0 340,520
                                      -230,-520 140,0 90,520
                                      40,-520 80,0 0,200 -120,320 
                                      "/>
  <!-- clouds -->
  <path style="fill:url(#grad3);" d="m 680,350 a 52 52 0 0 1 86,-50 
                                        a 62 62 0 0 1 34,-30 
                                        l 0,80 z"/>
  <path style="fill:url(#grad4);" d="m 360,600 a 62 62 0 0 1 86,-80 
                                        a 62 62 0 0 1 38,-12
                                        a 62 62 0 0 1 28,-28 
                                        a 72 72 0 0 1 60,-88 
                                        a 52 52 0 0 1 98,-36 
                                        a 74 74 0 0 1 86,-6
                                        a 40 40 0 0 1 44,-42
                                        l 0,292 "/>
  <!-- logo -->
  <g transform="translate(740,406) scale(-0.3,0.3)" style="fill:#69BCDC;stroke:none;">
    <path d="M 21,26 C 11,26 1,35 1,47 1.1,58 9,69 21,69 33,69 43,59 43,47 l -6,0 c 0,4 -4,9 -10,9 -6,0 -9,-5 -9,-10 0,-6 5,-10 9,-10 6,0 10,5 10,10 l 0,1 6,0 C 43,35 35,26 21,26 z"/>
    <ellipse cx="88" cy="29" rx="11" ry="11"/>
    <path d="m 50,54 26,-8 c 3,-1 6,-1 4,4 l -9,16 c -1,3 -2,3 -4,1 L 50,58 c -4,-2 0,-4 0,-4 z"/>
    <path style="fill:none;stroke:#69BCDC;stroke-width:3;stroke-linecap:round;" d="m 42,75 c 2,6 16,8 22,2 5,-5 5,-10 5,-10 0,0 4,6 12,6 13,0 13,-14 13,-14"/>
  </g>
  
  <!-- text -->
  <text style="fill:#69BCDC;stroke:none;" font-style="italic" font-weight="bold" font-size="0.8em" x="608" y="432">Puppy Linux</text>
 
</svg>
```

**Comment by dimkr** [comment]
Amazing! Much better than the ugly blue-green gradient in 431.

**Comment by 01micko** [comment]
> Amazing! Much better than the ugly blue-green gradient in 431.

I like that it's 3245 B :-)

**Comment by 01micko** [comment]
Ok, cleaned up the `svg` code and packaged up 3, standard 800x600, HD and HDx2 (for dual monitors). Incredibly, the tarball is bigger than the files added together! 

A great site for editing SVG paths [here](https://yqnn.github.io/svg-path-editor/). I mainly used it to convert absolute paths to relative paths - so _much_ easier to use relative paths.

[431-svg.tar.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/7063977/431-svg.tar.gz)

Here is my dual monitor setup:

p432-HDx2

**Pull request merged**
