### PR TITLE
Delete /var/run/dbus/pid on boot, otherwise D-Bus does not start on dpup

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by 01micko** [comment]
Should be deleted on shutdown, (note not _is_ but _should_)

https://github.com/puppylinux-woof-CE/woof-CE/blob/5822702bad38d3f4832ff16c70890bf4d4e296ff/woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown#L146

**Comment by 01micko** [comment]
By the way, I don't mind redundancy in case of a forced poweroff so maybe your PR has merit, but my above comment does too.

**Comment by dimkr** [comment]
@01micko Fixed - the pidfile is now renamed to dbus.pid on dpup

**Comment by 01micko** [comment]
Ok, I'll get to work soon on #2467

**Pull request merged**
