### PR TITLE
Provide access to wmonitors.sh through the video wizard (fixes #2554)

### LINKED ISSUE #2554: Missing support for display configuration when using Xwayland
These two are intentionally grayed out:

gray

Once #2528 and #2550 are fixed, it should be possible to run wlr-randr in startxwayland, and configure things like resolution, refresh rate, rotation and the scaling factor.

### PR DESCRIPTION
**Pull request by dimkr**
xorgwizard

### CODE REVIEW

**Review by 01micko — APPROVED** [review]
Looks good. I'll delete my PR and offer separate stuff for `quicksetup` and have a think about `pupx`

**Comment by dimkr** [comment]
> Looks good. I'll delete my PR and offer separate stuff for `quicksetup` and have a think about `pupx`

Now I see that this PR duplicates some of the work in your PR 😕

**Comment by 01micko** [comment]
> Now I see that this PR duplicates some of the work in your PR :confused:

It's ok, I'll retrieve the stuff from my fork before I delete it and refactor accordingly.

PS: I wasn't quite happy with `pupx` mods anyway and was going to take another look today.

**Comment by 01micko** [comment]
Ok, done in #2688 and #2689 so merging this

**Pull request merged**
