### PR TITLE
xorgwizard: Use xorg-autoconf if available

### PR DESCRIPTION
**Pull request by rizalmart**
xorg-autoconf is a script that automatically generates xorg.conf with high accuracy and precision which able to configure the video card with proper xorg driver and its parameters

http://www.murga-linux.com/puppy/viewtopic.php?p=1051102

### CODE REVIEW

**Comment by mavrothal** [comment]
I would think that you either include xorg-autoconf 2.0 in woof or just add an install script in the pet to patch xorgwizard  (you can add the patch in the pinstall)

**Comment by 01micko** [comment]
@rizalmart I do see the specific need for a script like `xorg-autoconf` particularly for the intel `uxa` issue, on which the laptop I'm typing on suffers. ( `8086:0126` ) _Norgo_ (forum handle) has tried to address this with a boot parameter but I think that approach is a bit too 'clunky'. 

Perhaps if you can improve and maintain the script it _should_ be in woof.

I notice in a lot of your scripts you omit the paths of `/lib64/` and `/usr/lib64/` which Slackware uses, so consequently, many do not work as expected in  _Slacko64_.

> `lib<qual>` Alternate format essential shared libraries
>                    (optional)

Many distros take a different approach to `qual`. See [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf) (PDF)

Anyway, here is a diff against your current `xorg-autoconf` on the forum:

```diff
diff -rup xorg-autoconf-2.0/usr/bin/xorg-autoconf xorg-autoconf-2.0-new/usr/bin/xorg-autoconf
--- xorg-autoconf-2.0/usr/bin/xorg-autoconf	2020-02-26 13:57:25.000000000 +1000
+++ xorg-autoconf-2.0-new/usr/bin/xorg-autoconf	2020-03-01 07:17:16.402588697 +1000
@@ -17,7 +17,7 @@ case $devid in
  7800)
   drv="i740"
  ;;
- 0412|2562|2772|27a2|5a85)
+ 0412|2562|2772|27a2|5a85|0126)
   drv="intel"
   accel="uxa"
  ;;
@@ -65,7 +65,7 @@ esac
 
 drvfound=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules/drivers/${drv}_drv.so ]; then
   drvfound="1"
@@ -168,7 +168,7 @@ esac
 
 drvfound=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules/drivers/${drv}_drv.so ]; then
   drvfound="1"
@@ -178,7 +178,7 @@ done
 
 if [ "$drvfound" == "" ] && [ "$drv" == "amdgpu" ]; then
 
-	for xpath in /usr/lib/X11 /usr/lib/xorg
+	for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 	do
 	 if [ -e $xpath/modules/drivers/radeon_drv.so ]; then
 	  drvfound="1"
@@ -199,7 +199,7 @@ fi
 
 if [ "$drvfound" == "" ] && [ "$drv" != "ati" ]; then
 
-	for xpath in /usr/lib/X11 /usr/lib/xorg
+	for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 	do
 	 if [ -e $xpath/modules/drivers/ati_drv.so ]; then
 	  drvfound="1"
@@ -263,7 +263,7 @@ bid="$(echo "$PCILIST" | grep "$1" | cut
 
 drvfound=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules/drivers/${drv}_drv.so ]; then
   drvfound="1"
@@ -314,7 +314,7 @@ esac
 
 drvfound=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules/drivers/${drv}_drv.so ]; then
   drvfound="1"
@@ -362,7 +362,7 @@ esac
 
 drvfound=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules/drivers/${drv}_drv.so ]; then
   drvfound="1"
@@ -410,7 +410,7 @@ esac
 
 drvfound=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules/drivers/${drv}_drv.so ]; then
   drvfound="1"
@@ -468,7 +468,7 @@ probe_nvidia(){
  
 drvfound=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules/drivers/${drv}_drv.so ]; then
   drvfound="1"
@@ -514,7 +514,7 @@ probe_via(){
  
 drvfound=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules/drivers/${drv}_drv.so ]; then
   drvfound="1"
@@ -561,7 +561,7 @@ EndSection
 
 xorg_mod_path=""
 
-for xpath in /usr/lib/X11 /usr/lib/xorg
+for xpath in /usr/lib/X11 /usr/lib/xorg /usr/lib64/X11 /usr/lib64/xorg
 do
  if [ -e $xpath/modules ]; then
   xorg_mod_path="$xpath/modules"
```

Also, for consistency, perhaps the generated `xorg.conf` should resemble the pre-constructed versions in woof now. I'm not saying yours is wrong, but maybe some improvements could be made to the existing files.

**Comment by 01micko** [comment]
Also, perhaps this commit needs improvement for affected intel chips with a touch screen  (and perhaps others). As is the case now, those will be missed because `xorg-udev` will have already been chosen. However, the raspi and arm specific stuff should be left untouched.

Thanks.

**Comment by 01micko** [comment]
Since I merged #1768 this commit certainly needs the required work before merge.

Thanks.

**Comment by 01micko** [comment]
@gyrog .. IIRC you had a problematic intel chip with default `SNA` acceleration. Does it fall within the ID's of my diff above?

**Comment by 01micko** [comment]
@rizalmart if your intention is to make `xorg-autoconf` available to `evdev` systems based on the existence of  `/var/local/xorg_udev` perhaps this commit needs a rethink altogether.

**Comment by rizalmart** [comment]
@01micko I sent a pull request on xorg-autoconf. It wont generate InputDevice section in xorg.conf and enables AutoAddDevices on ServerFlag section for evdev systems.

**Comment by 01micko** [comment]
Ok, merged @rizalmart but there are other conditions for  `AutoAddDevices = true` such as arm devices and touch screen devices.

See `/etc/rc.d/rc.sysinit`

**Comment by rizalmart** [comment]
I noticed that fbturbo thing for arm platform. Is there any to detect arm gpu's or retrieve gpu info due to lack of interface standards unlike in x86 and amd64 which can be get gpu info with PCI standard

**Comment by 01micko** [comment]
> I noticed that fbturbo thing for arm platform. Is there any to detect arm gpu's or retrieve gpu info due to lack of interface standards unlike in x86 and amd64 which can be get gpu info with PCI standard

Not that I am aware of. I have only had odroid XU3 and raspberries 0, 1, 3 and  4. There is no PCI bus. They are [SoC](https://www.tomshardware.com/reviews/glossary-soc-system-on-chip-definition,5890.html)s (link = tom's hardware) where everything is on the main chip meaning little to no chance of isolating the GPU via a device ID.

Perhaps in the fbturbo docs there is a list of what SoC's it supports, so some research must be done.

**Comment by rizalmart** [comment]
@01micko the xorg-autoconf is now stable on x86 and x86_64 architecture. The arm arch autoconf was experimental, it is done by probing the loaded kernel modules and probing the contents of /proc and /sys folder. 

So far there are four gpu on ARM platform: VideoCore, PowerVR, Mali, and OMAP. We need to detect those soc gpu by probing any presence of a file/folder related to them in /dev, /proc, and /sys folder.

**Comment by 01micko** [comment]
At the moment permissions on `/usr/sbin/xorg-autoconf` are `0644`. For it to work it needs to be `0755` or just `755`. I think leave it at 644 and only enable it if the builder wants at the woof level with an obvious change to `3builddistro`.

This preserves stability for the conservative builders here while allowing more adventurous builders to include your work out of the box (I'll be one of those when the time allows).

@rizalmart this will require a change in this commit depending on the state of permissions on `xorg-autoconf`, not whether it is available, because it is (merged to woof). Obviously with your improvements to the script all architectures should be included.

Any questions, please ask.

**Comment by rizalmart** [comment]
@01micko no problem. thanks

**Comment by 01micko** [comment]
@rizalmart 
I finally got around to testing `xorg-autoconf` in a woof build on my problematic intel graphics laptop and it works well. I used the method I outlined above and will commit a variation of this commit shortly. I'll test later on the raspberry boards but I can't see an issue.

**Comment by 01micko** [comment]
[207220](https://github.com/puppylinux-woof-CE/woof-CE/commit/2072200affde1fb03b15a10fdc0c0d4dfdafd7bd) closes this PR. Thanks for the work

**Pull request closed without merging**
