### PR TITLE
Switch to PMaterial icons in Dark Gray

### PR DESCRIPTION
**Pull request by dimkr**
Workaround for #2082.

This makes Dark Gray more similar to The Beach Grey.

### CODE REVIEW

**Comment by 01micko** [comment]
I'll just wait here :smile_cat: until standard is ready (not too long).

I think Dark Gray needs to be more distinct.

**Comment by 01micko** [comment]
Are you sure?

Puppy_Standard

Commits soon!

**Comment by 01micko** [comment]
If you _really_ want to use PMaterial, well reopen and it will be merged.

**Comment by dimkr** [comment]
> Are you sure?

Nope. Dark gray is my favorite color, my aesthetic standards are almost non-existing. I'd use any theme that works well and solves the three major problems (complete set if icons for menus, PCManFM, and pavucontrol) 😈

**Comment by dimkr** [comment]
I just built https://github.com/dimkr/woof-CE/releases/tag/dpupos-arm-cros-8.0-prepreprealpha5 and booted it on my C201. GTK 3 applications look great now, after all the icon theme improvements. Users that upgrade to Slacko 8.0 won't know GTK was upgraded.

**Pull request closed without merging**
