### PR TITLE
Bootmenu updates

### PR DESCRIPTION
**Pull request by woodenshoe-wi**

### CODE REVIEW

**Comment by wdlkmpx** [comment]
Do you have more updates in mind? I've also been testing this code, and i realized that:

that using read FIELD VALUE < bootmenu.txt , etc, there are 42 insertions and 200 deletions
by making init source /sbin/init-bootmenu there are 63 insertions and 239 deletions

**Comment by wdlkmpx** [comment]
I'm doing everything in the experimental branch, it has all the interesting changes for a raspi.. including the raspi-version script. More ram available (no tmpfs to preserve the initrd), etc..

After moving init-bootmenu to initrd-progs i realize that i need to rebase on top of testing again

So opening pull requests to merge into experimental might be a good idea..

**Comment by wdlkmpx** [comment]
I remember we were discussing about search options in a raspi, theoretically init already provides all the needed functionality that is triggered by a param .. or a exported variable.

PMEDIA cd  -- trigger global search
PSUBIDR /raspup -- look in PSUBDIR

But i think someone said pmedia=cd doesn't work in a raspi or something

**Comment by woodenshoe-wi** [comment]
> Do you have more updates in mind? I've also been testing this code, and i realized that:

> that using read FIELD VALUE < bootmenu.txt , etc, there are 42 insertions and 200 deletions
by making init source /sbin/init-bootmenu there are 63 insertions and 239 deletions

I wasn’t planning to make more changes, I just thought that I should finish writing some documentation for bootmenu.txt and discovered that the init-bootmenu script didn’t support comments.  I also wanted to add a countdown for the TIMEOUT function.

As for optimizing the script, I guess I’m not that much of an expert on ash scripting.  It took me quite a while to get rid of the “out of range” errors that ash was giving me because apparently you can’t test if a variable is greater than 10 if the variable = “”.  Go ahead and make any changes you want, hopefully the documentation in bootmenu.txt helps you understand what my intentions were.

> I remember we were discussing about search options in a raspi, theoretically init already provides all the needed functionality that is triggered by a param .. or a exported variable.

> PMEDIA cd -- trigger global search
PSUBIDR /raspup -- look in PSUBDIR

> But i think someone said pmedia=cd doesn't work in a raspi or something

I don’t remember if pmedia=cd works or not, but I do remember some disagreements about whether init should be searching for stuff.  I wanted to try to implement the search functionality outside of the main init in case it was removed in the future.  It also allowed me to implement a menu to choose between the search results.  It can be used to choose between multiple save files, and pressing ESC twice in a row should get you back to the main menu.

**Comment by wdlkmpx** [comment]
Ok thanks. I'll optimize and probably improve stuff.

**Pull request merged**
