### PR TITLE
getflash: Synch with EasyOS's version 1.9 + code cleanup

### PR DESCRIPTION
**Pull request by rserwin1**

### CODE REVIEW

**Comment by wdlkmpx** [comment]
A getflash pet pkg was recently updated, is that the same getflash?

https://github.com/puppylinux-woof-CE/woof-CE/commit/a3e60e72c46172cfaa1b26eb53b1911168f22de0

**Comment by rserwin1** [comment]
The recent update changed only the woofCE distro entry.  This PR is for 
the latest changes made in EasyOS, its 1.9.  I added a few things to 
that.  See the getflash 1.9.1 history entry for those details.

I expect to also update the woofCE-noarch pet package, once I get set up 
to do that.


wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
There should be only one getflash package. It's going to be EOL next
year. This probably should replace the noarch pet package.

https://github.com/puppylinux-woof-CE/woof-CE-noarch/

Does it work with palemoon? slacko 14.0 and 14.1 include an up to date
palemoon sfs [by default] and probably the same will happen with
tahrpup.. and xenialpup

**Comment by wdlkmpx** [comment]
It looks like there are at least 2 getflash pkgs that are properly fixed. In that case I have a task for you, identify the best version, it usually includes eye candy. Sacrificing pkgs is part of wce's culture.

EDIT: I see you added the pet package to noarch, you have to update the noarch pkg db.

**Comment by rserwin1** [comment]
I tested with Palemoon.  Its Add-ons-Plugins shows the latest Adobe 
Flash entry.

I have lost track of the sites that still need flashplayer.  Do you know 
of a site to try?


wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
Years ago I used to play tetris at https://www.tetrisfriends.com/

**Comment by rserwin1** [comment]
Now that site says:
  Tetris Friends is no longer available.

But I found a site that does require flashplayer:
    http://bear71.nfb.ca/#/bear71

It works in both palemoon and seamonkey.  They detect whether 
flashplayer is present or absent.




wdlkmpx wrote:

**Comment by rserwin1** [comment]
I see what you mean about different versions.  Version 1.7.2 was never 
in woofCE.  It is based on an older version of getfllash from before 
logic was added for 32/64-bit architectures.

I believe the getflash-1.7.2 .pet package should be removed from the 
noarch repo.


wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
This pkg is not "stable" and is going to be EOL, sites with flash content are disappearing or slowly migrating to html5. Firefox & chrome are already actively blocking flash content, and flash player support will be completely dropped next year (that's what I read).

It probably should be in the noarch repo... it already is, uploaded by rserwin1.

Games, hmm I prefer emulators (SNES, Play station 1, 2).

Commit 489073c11d3bad34da2c8ecf224a5727b9157481 updates the noarch pkg db ( https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/Packages-puppy-noarch-official )

Commit 30a62e3e034738f898d63156c89545161f7b7ae6 adds getflash to most pkgs_specs (except bionicpup, raspup).

Commit 23e09c3679176254b527e5be4e9a3957c4d38540 deletes the getflash rootfs-package.

Now it's easier to update, and updates become available to those who update the package databases.

Just upload the updated pkg and edit Packages-puppy-noarch-official, no need to open a pull request or use the git cli app. It doesn't get easier than that.

**Pull request closed without merging**
