### PR TITLE
Add weechat to dpup and jammy64

### PR DESCRIPTION
**Pull request by dimkr**
Similar to irssi in some ways, but doesn't need Perl and more actively maintained.

weechat

### CODE REVIEW

**Comment by 01micko** [comment]
Hmmm... I've `irssi` (compiled myself and probably getting old) in the slacko's and default runs as spot. I've nothing aginst this PR, but maybe a petbuild would be cool, at least for slacko - limited repo there.

**Review by 01micko — APPROVED** [review]

**Comment by 01micko** [comment]
https://distro.ibiblio.org/puppylinux/pet_packages-slacko6415.0/irssi-1.2.2-x86_64_s84.pet

The slacko package for irssi - designed to be super user/newbie friendly.

**Comment by dimkr** [comment]
> maybe a petbuild would be cool

On it.

**Comment by dimkr** [comment]
Done, now it's a petbuild. I removed my "user friendly shell" thing and just configured weechat to auto-connect to #puppylinux: that's more user friendly than reconfiguring it every time it's started (some users want to use weechat, but without auto-connecting to this channel).

**Review by 01micko — APPROVED** [review]

**Pull request merged**
