### PR TITLE
Fixes Issue#1775 - pkg_chooser.sh can't differentiate repos names wit…

### PR DESCRIPTION
**Pull request by s243a**
…h more than 3 hyphens. (e.g. "arch-32-community" "arch-32-community-testing"

### CODE REVIEW

**Comment by 01micko** [comment]
I cant see what this fixes :confused: 

```
# echo arch-32-community-testing | cut -f 2-4 -d -
32-community-testing
#  echo arch-32-community | cut -f 2-4 -d -
32-community
#  echo arch-32-community | cut -f 2- -d -
32-community
# echo arch-32-community-testing | cut -f 2- -d -
32-community-testing
```

How do you get results other than that?

**Comment by s243a** [comment]
If you are using arch32pup, then add to /var/packages/DISTRO_COMPAT_REPOS the following:
```
PKG_DOCS_DISTRO_COMPAT="
z|https://mirror.archlinux32.org/pentium4/core/core.db.tar.gz|Packages-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}-core 
z|https://mirror.archlinux32.org/pentium4/extra/extra.db.tar.gz|Packages-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}-extra
z|https://mirror.archlinux32.org/pentium4/community/community.db.tar.gz|Packages-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}-community
z|https://mirror.archlinux32.org/pentium4/community/community-testing.db.tar.gz|Packages-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}-community-testing
z|https://mirror.archlinux32.org/pentium4/community/testing.db.tar.gz|Packages-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}-testing
```
You also need the following in /var/packages/PKGS_MANAGMENT
```
PKG_REPOS_ENABLED='Packages-puppy-slacko14.2-official Packages-puppy-noarch-official Packages-puppy-common32-official Packages-arch-32-community Packages-arch-32-core Packages-arch-32-extra Packages-arch-32-testing Packages-arch-32-community-testing'
```

and in /usr/local/petget/0setup you need to modify the for loop:

```
for arepo in core extra community testing community-testing; do
```
The point here is you need to update testing and community-testing

Now, run /usr/local/petget/0setup

Now in the ppm (aka pkg_chooser.sh) search for something in the repo arch-32-community-testing such as "6tunnel-0.13". You'll see two entries:
```
[arch-32-community] Tunnels IPv6 connection for IPv4-only applications
[arch-32-community-testing] Tunnels IPv6 connection for IPv4-only applications
```

This is also applicable to other puppies. For instance in debian we might have the repo "debian-stretch-tor-main"

which has four hyphens. The only difference, is that with the other puppies we don't need to modify 0setup to test this. 

without this fix you would see:
```
[arch-32-community] Tunnels IPv6 connection for IPv4-only applications
[arch-32-community] Tunnels IPv6 connection for IPv4-only applications
```
that is it wouldn't differentiate between the two repos.

**Comment by s243a** [comment]
>  cant see what this fixes confused
> 
> ```
> # echo arch-32-community-testing | cut -f 2-4 -d -
> 32-community-testing
> #  echo arch-32-community | cut -f 2-4 -d -
> 32-community
> #  echo arch-32-community | cut -f 2- -d -
> 32-community
> # echo arch-32-community-testing | cut -f 2- -d -
> 32-community-testing
> ```
> 
> How do you get results other than that?

You need to modify those echo statments:


 ```
 # echo Packages-arch-32-community-testing | cut -f 2-4 -d -
 arch-32-community
 #  echo Packages-arch-32-community | cut -f 2-4 -d -
 arch-32-community
 #  echo Packages-arch-32-community | cut -f 2- -d -
 arch-32-community
 # echo Packages-arch-32-community-testing | cut -f 2- -d -
 arch-32-community-testing
 ```
> 
> How do you get results other than that?

**Comment by 01micko** [comment]
ok

**Pull request merged**
