### PR TITLE
Merge the two Firefox package templates

### PR DESCRIPTION
**Pull request by dimkr**
Needs testing with the Slackware package.

### CODE REVIEW

**Comment by 01micko** [comment]
Ok, I'll do a build today (64) and also test out teh gray as well as some ideas of my own - a fixup_hack for pulseaudio and a simple `yad --notification` to launch pavucontrul from the tray icon.

**Comment by 01micko** [comment]
Firefox 68.12.0 ESR opens just a blank page in slacko64, even on second run. As a side note,  Running in qemu Dark Gray looks great and the few gtk3 apps (I manually added your other PR look good). And my Pulseaudio thing works a treat!

Not sure what to do about the FF template though, I suppose I can experiment but I'm getting low on time :disappointed: 

The_Gray_Slacko

**Review by 01micko — CHANGES_REQUESTED** [review]
From your original `firefox_FIXUPHACK` can I request a user friendly change please.

replace
```
defaultPref("browser.startup.homepage", "about:blank");
```
with
```
defaultPref("browser.startup.homepage", "file:///usr/share/doc/home.htm");
```

I know you originally had 
```
defaultPref("browser.startup.homepage", "file:///usr/share/doc/index.html");
```
but I think the 'jumping off page" is friendlier and there is a link to the index page anyway.

The_Gray_Slacko1

**Comment by dimkr** [comment]
@01micko The homepage change is already in testing. Please pull :)

~~EDIT: synced this branch with testing - indeed, #2017 is merged into testing already~~

EDIT 2: changed the homepage

**Pull request merged**
