### PR TITLE
sns: Added ability to rescan for wifi networks

### PR DESCRIPTION
**Pull request by rizalmart**
wireless setup moved to function in order to create recursion if the user choose to rescan for wifi networks

### CODE REVIEW

**Comment by 01micko** [comment]
I'll wait for @rserwin1 to review before merge. Thanks.

**Comment by 01micko** [comment]
@rserwin1 Richard, are you around to check this?

**Comment by 01micko** [comment]
In the absense of @rserwin1 review I'll let this through.

**Comment by dimkr** [comment]
I think this PR broke SNS. I can't connect to WiFi - when I connect, it scans again.

**Comment by 01micko** [comment]
I'll revert

**Comment by dimkr** [comment]
> I'll revert

Wait, I'm not 100% sure it's because of this PR, but this does look like a very likely hypothesis because nothing else has changed and wpa_supplicant+dhcpcd do work and it behaves like a pure UI bug.

I'll probably do a quick debugging round later today or tomorrow.

**Comment by 01micko** [comment]
too late 87e1f18

**Comment by dimkr** [comment]
Commenting-out this line makes the problem disappear:

```
[ "`echo "$RETSTRING" | grep '^EXIT' | grep 'BUT_RESCAN'`" == "" ] && setup_wifi
```

This condition is always true.

**Comment by 01micko** [comment]
Well the PR was a good idea and I took it on trust. My bad.

**Comment by dimkr** [comment]
> Well the PR was a good idea and I took it on trust. My bad.

No worries, it's good idea with a bug and we'll fix it :)

**Pull request merged**
