### PR TITLE
Update ui_Classic

### PR DESCRIPTION
**Pull request by rizalmart**
Contain ppm temp files to a folder

### CODE REVIEW

**Comment by wdlkmpx** [comment]
All these PPM pull requests are merged by https://github.com/puppylinux-woof-CE/woof-CE/commit/b43115ffef8d709ef42f4e5cc219665b20084536 .. in a single commit, which includes /usr/sbin/download_file (it's part of the ppm).

**Comment by wdlkmpx** [comment]
I meant all the PPM pull requests with msg "Contain ppm temp files in a folder" are merged by commit https://github.com/puppylinux-woof-CE/woof-CE/commit/b43115ffef8d709ef42f4e5cc219665b20084536 
followed by bugfix https://github.com/puppylinux-woof-CE/woof-CE/commit/e39bf5a8b1f7e7e1151cf355ffc5bfb16e15b4cf .. (applied sed 2 times on download_file)

I'll close all the PPM pull requests with msg "Contain ppm temp files in a folder", but this will flood people's emails, those who are reading this, maybe tomorrow. This message has to be read.

I merged those changes into exp branch, which resulted in a different commit, i tested and it seems to work fine. So the changes are good...

**Comment by wdlkmpx** [comment]
Does "Contain ppm temp files in a folder"  affect Pkg in any way?

**Comment by rizalmart** [comment]
Nope it does not affect the pkg but just reorganization of temporary files produced by petget

**Pull request closed without merging**
