### PR TITLE
puppyapps: -takeover option

### PR DESCRIPTION
**Pull request by wdlkmpx**

### CODE REVIEW

**Comment by mavrothal** [comment]
Keep in mind that the takeover option will not generate the new default<app> of the original, so if/when this goes to packages the install script should add them. Alternatively the -takeover option should add them.
Another option that would be nice to have, is to be called from PPM with a flag to check if any new .desktop file is generated and then offer to set it as default if it belongs to any of the categories.
The checking and call could be done from the PPM side too (from installpkg.sh, checking for desktop files in /root/.packages/${DLPKG_NAME}.files).

**Comment by wdlkmpx** [comment]
Do you mean something like this?

	for app in $(default_apps) ; do
		file=/usr/local/bin/default${app}
		apps_array $app > /tmp/puppyapps/puppyapps_items_$app
		RUNAPP_EXEC=$(get_default "$app")
		if [ $? -eq 1 -o ! "$RUNAPP_EXEC" ] ; then
			echo -e "#!/bin/sh\nexec puppyapps default${app} \"\$@\"" > $file
			echo "[autodetect] > $file"
		else
			echo -e "#!/bin/sh\nexec puppyapps default${app} \"\$@\"" > $file
			echo "$RUNAPP_EXEC > $file"
		fi
		chmod +x $file
	done


	file-roller > /usr/local/bin/defaultarchiver
	mhwaveedit > /usr/local/bin/defaultaudioeditor
	gnome-alsamixer > /usr/local/bin/defaultaudiomixer
	deadbeef > /usr/local/bin/defaultaudioplayer
	mozstart > /usr/local/bin/defaultbarehtmlviewer
	dillo > /usr/local/bin/defaultbrowser
	osmo > /usr/local/bin/defaultcalendar
	[autodetect] > /usr/local/bin/defaultcdplayer
	pburn > /usr/local/bin/defaultcdrecorder
	hexchat > /usr/local/bin/defaultchat
	[autodetect] > /usr/local/bin/defaultchmviewer
	connectwizard > /usr/local/bin/defaultconnect
	osmo > /usr/local/bin/defaultcontact
	mtpaint > /usr/local/bin/defaultdraw
	libfm-pref-apps > /usr/local/bin/defaultemail
	pcmanfm > /usr/local/bin/defaultfilemanager
	geany > /usr/local/bin/defaulthtmleditor
	mozstart > /usr/local/bin/defaulthtmlviewer
	mtpaint > /usr/local/bin/defaultimageeditor
	viewnior > /usr/local/bin/defaultimageviewer
	gnomemplayershell > /usr/local/bin/defaultmediaplayer
	deadbeef > /usr/local/bin/defaultmusicplayer
	mtpaint > /usr/local/bin/defaultpaint
	evince > /usr/local/bin/defaultpdfviewer
	lxtask > /usr/local/bin/defaultprocessmanager
	screeny > /usr/local/bin/defaultscreenshot
	gmrun > /usr/local/bin/defaultrun
	pfind > /usr/local/bin/defaultsearch
	gnumeric > /usr/local/bin/defaultspreadsheet
	lxterminal > /usr/local/bin/defaultterminal
	geany > /usr/local/bin/defaulttexteditor
	leafpad > /usr/local/bin/defaulttextviewer
	abiword > /usr/local/bin/defaultwordprocessor
	`/usr/bin/defaults-chooser' -> `/usr/sbin/puppyapps'

I see that I have make to more tweaks to the apps array

Regarding the PPM, I'll try to think of something to accomplish that

**Comment by wdlkmpx** [comment]
Although that could be another switch, like -scan "Scan and set defaults accordingly"

**Comment by mavrothal** [comment]
> Do you mean something like this?

No more something like this
```
# close to the end of /usr/local/petget/instalpkg.sh
HASDESKTOP=$(grep -s 'desktop' /root/.packages/${DLPKG_NAME}.files)
[ "$HASDESKTOP" ] && DESKNAME=$($(basename $HASDESKTOP) | sed 's/\.desktop//')
[ "$DESKNAME" ] && INPUPPYAPPS=$(grep -s '$DESKNAME' /usr/sbin/puppyapps
[ "$INPUPPYAPPS" ] && #detect category in puppyapps
[ "$INPUPPYAPPS" ] && . /usr/lib/gtkdialog/box_yesno "$(gettext 'Puppyapps')" "$(gettext "Do you want to set")" "<b>${DESKNAME}</b>" "$(gettext "as default for")" "<b>${CATEGORY} ?</b>"
[ "$EXIT" = "yes" ] && puppyapps -c -m default$CATEGORY $DESKNAME # something like that
# Or it can set the default directly echo'ing the command into default\<category\>.
```
Not sure if puppyapps really need any changes to accommodate this.
(Note the above is not tested at all...)

**Comment by wdlkmpx** [comment]
zigbert do you how can I make the main dialog show up maximized?

There are too many caterories, withn 10 rows and 3 columns they almost
fit in a 1024x768 screen, I removed the dog to make room (.svg ->
none), and I'd like to remove the whole element in yellow, but I'm not
sure.

The next pull request will have various commits and code relocation, I
hope you don't mind. I'm having a headache and am trying to apply all
my thoughts now to avoid thinking of this all day and night

**Pull request merged**
