### PR TITLE
Add get_java and automatic Java interface for user-installed JRE/JDK packages

### PR DESCRIPTION
**Pull request by rserwin1**
Java can be installed from PET or SFS packages by users. This javaif bundle also accommodates Java packages installed by expanding a JRE or JDK archive (tar.gz) file into /opt.  The javaif files substitute and (usually) override the code included in familiar Java SFS and PET packages.  (A PET java.sh file will replace the javaif version, but will provide similar function.)

Although developed to support my new get_java package, this interface is not dependent on it.  But it adds support for expansion of java tarballs into the operational Java directory.  If multiple Java packages are present, it will select the latest version, for use.

Although the interface automation is done during bootup, this bundle includes a menu entry for the Java Control Panel, and an intermediary script (javaif) that detects the extent to which Java is installed and notifies the user if it is not completely installed.  Besides possibly being absent or fully operational, Java may have been installed by the user but not yet integrated by links and environmentaly variables.

Although the links can be set without a reboot, I found no way to completely update the environment variables as used by subsequent scripts.  A command line query (echo) of the PATH variable may show the update, but the Java Control Panel (and the intermediary) see only the old value.  If anyone knows a way fix that, I will consider modifying further to achieve complete installation without rebooting.

Edit: I see that this includes the get_java package, which I placed in a different branch. I thought that pull requests were tied to branches, but apparently not.  Get_java handles downloading, packaging and installation of Java tarballs.

### CODE REVIEW

**Comment by 01micko** [comment]
I understand that the "Add files via upload" thing is github quirk, but can you in future also add a meaningful, even if it is only the filename, commit message. TIA

I have no problem with the PR but again, github does. All executable files don't have perms preserved with the git interface re #786

**Comment by rserwin1** [comment]
Mick,
Thanks for pointing out the need for the file name for the uploads.  
Will do.

Re permissions: is there any way, at all, for me to set permissions with 
github?  How do you folks do it for me?  Is it something I can do, myself?

I am coming around to the need to master the command line git processes, 
initially to keep my fork up to date.  Are you suggesting that I should 
also use it for uploading files, and possibly instead of editing files 
in github, to preserve execute permission?

I know you gave me instructions on how to do some things locally, but I 
cannot locate that information.  At one point you mentioned updating 
your blog with some instructions.  But your blogs I can find are not 
related to git.  Is there a simple way to get to the instructions I 
need?  Surely, there must be a link to them somewhere.  I Know  Karl 
Godt wrote some howtos and mavrothal wrote some, too.  But I cannot find 
yours, which address exactly what I need to know.

Thanks for your help.


Mick Amadio wrote:

**Comment by wdlkmpx** [comment]
Hi rerwin, I can do everything you want me to, any change. Just send
me the file or files to add or replace/update (specify the exact
path), depending on the situation i will open a pull request or push
it directly.

My email is my username plus gmail. I will commit crediting you as the
author, that can be called "impersonation".. something like this:
https://github.com/puppylinux-woof-CE/woof-CE/commit/2d1f77327a2ec184af1974ca69991c138ac16538

**Comment by wdlkmpx** [comment]
Or perhaps attach files (or patches) in the "woof-ce needs you"
thread, in the Announcements section

**Pull request merged**
