### PR TITLE
Add automated builds of fossa64

### PR DESCRIPTION
**Pull request by dimkr**
Many packages stuffed into zz_* packages are lost, but there are many libraries there that don't receive security updates and a bunch of manual changes that conflict woof-CE, so I removed them.

It won't look the same as "official" 9.5, but this can be fixed easily by re-adding the artwork in separate packages. Also, some functionality is lost, but it can be re-introduced later using separate PET packages that do one thing.

I bumped the GTK+ 3 requirement of petbuilds to the version used by Debian Bullseye, so dpup Bullseye and Slacko64 8.0 can stay on GTK+ 3 while everything older (including Slacko 7.x and now fossa64 too) stays with GTK+ 2 builds of stuff like Geany.

It will be possible to restore the adrv when the zz_* packages are replaced with individual packages and #2113 is fixed.

fossa64 is popular and it's good to have it built continuously, to make sure people can build a "9.5.1" based on it, and ensure woof-CE is capable of building an Ubuntu-based Puppy until somebody picks up work on a 22.04-based Puppy.

There's a big pile of unused or legacy libraries in DISTRO_PKGS_SPECS. I haven't removed them because this can be done later, and because removing them would make fossa64 builds from woof-CE incompatible with packages for 9.5 that depend on these libraries.

### CODE REVIEW

**Review by 01micko — COMMENTED** [review]
Looks fine to me but ultimately up to @mrfricks

**Comment by dimkr** [comment]
When https://github.com/dimkr/woof-CE/runs/2105282952 is done an image will (hopefully) be uploaded to https://github.com/dimkr/woof-CE/releases.

@01micko It would be great if @mrfricks releases a 9.5.1 straight from woof-CE. However, even without @mrfricks approval, I think it's healthy for woof-CE to have CI for fossa64.

**Comment by peabee** [comment]
fossa64 - libudev.so.1 missing - X fails

the eudev package being used seems to be missing libudev

**Comment by dimkr** [comment]
> the eudev package being used seems to be missing libudev

Thanks, I'll fix this. The eudev petbuild produces a statically-linked eudev, so we can use the compatible distro libudev (both compatibility and liberty of using eudev on distros that don't have it, or have an old version).

EDIT: building now, https://github.com/dimkr/woof-CE/runs/2106805902

**Comment by peabee** [comment]
Got to desktop by making a ydrv with libudev in it....
Missing icons in menu
No clipboard
Missing dependencies & leafpad error:
[checkdeps_system.txt-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6136847/checkdeps_system.txt-false.gz)

**Comment by dimkr** [comment]
> Missing icons in menu
> No clipboard
> Missing dependencies & leafpad error:

This is not surprising, the zz_* are the duct tape that holds 9.5 together. Yes, it will require some work to restore all the missing functionality and add the libraries previously stuffed together in zz_*, but this time cleanly, as separate packages.

**Comment by mrfricks** [comment]
hi @dimkr , @01micko & @peabee ,

I'm happy with work done on fossapup to get it compliant with woofce and fossapup definitely wasn't compliant :) . The use of the adrv so people could remove it and have a minimal barebones puppy meant building two separate pups and then combining them and using some dodgy scripts.

@dimkr the adrv's DISTRO_PKG_SPECS-norm is the recipe for the complete fossapup, the one in woofce is for the barebones + adrv. 
[DISTRO_PKGS_SPECS-norm.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6137376/DISTRO_PKGS_SPECS-norm.gz) (real gz)

i agree the zz_pets should be split up into separate small packages such as  
hacks-postinstall.sh-fossapup and will strive to do so in the future. @wdlkmpx told me off for this more than once!

BTW great job on getting automated builds working in woofce !!!!

**Comment by dimkr** [comment]
> @dimkr the adrv's DISTRO_PKG_SPECS-norm is the recipe for the complete fossapup, the one in woofce is for the barebones + adrv.
> [DISTRO_PKGS_SPECS-norm.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6137376/DISTRO_PKGS_SPECS-norm.gz) (real gz)

Now it's so much clearer why fossa64 in woof-CE looks the way it does. I extracted the DISTRO_* files from the 9.5 ISO and couldn't understand how you built it 😄 

Thanks for your work, I hope to get fossa64 in woof-CE in good shape. Maybe not perfect and maybe different from 9.5, but good enough to allow people to build puplets from it and experiment on it.

EDIT: forgot to say, it's very neat what you did there with the adrv. We need to implement this cleanly in woof-CE and make it an off-the-shelf capability any Puppy builder can use.

**Comment by mrfricks** [comment]
@dimkr the send to adrv thing is already in woofce (ie the zz_adrv.pet becomes the adrv.sfs and the zz_fdrv.pet becomes the zz_fdrv.sfs in _00build.conf.) but when i first started fossapup i had been away from puppy for a while and it wasn't working for me with complex DISTRO_PKG_SPECS lines such as ffmpeg or libreoffice which have multiple packages.  i didn't investigate further and it may have been fixed and i went my own way with it.

fossapup is built with two pups, a bare bones & a full. The barebones was then subtracted from the the full (with a script) and then the full minus the barebones made manually into the adrv.pet.  The final pup is the barebones but with the adrv.pet in the DISTRO_PKG_SPECS and it's sent to the adrv.sfs in the _00build.conf.  

EDIT: and some dodgy scripts to detect whether the adrv is loaded or not, then alter the DISTRO_PKG_SPECS accordingly

anyway i'm sorry for the confusion that (franken) fossa has caused.

**Comment by 01micko** [comment]
@mrfricks seems happy enough (Thanks Phil) so I'm happy to merge and we deal with the fallout.

**Comment by 01micko** [comment]
But I'll wait until tomorrow.. :)

**Comment by dimkr** [comment]
Ha, now that I've added the missing packages the build is broken because libpulse-dev is missing and we're doing the retrovol->pa-applet transition. Will fix soon.

**Comment by 01micko** [comment]
@dimkr if you are building `yad` for fossapup under gtk2 the @step https://github.com/step-/yad/releases repo has an updated and maintained version.

**Comment by dimkr** [comment]
> @dimkr if you are building `yad` for fossapup under gtk2 the @step https://github.com/step-/yad/releases repo has an updated and maintained version.

I've seen the petbuilds PR, thanks.

I'm not sure what I think of this fork. On the one hand, it fixes some known issues with the old version of yad we use. On the other hand, it contains extra features (?) that can interfere with the GTK+ 3 migration effort. If we can switch to this fork for both GTK+2 and 3, and this yad behaves the same in both build types, then sure, let's use it.

**Comment by 01micko** [comment]
Sorry cancelled slacko64 because I initiated a build when salix fixed it's PACKAGES.txt problem.

**Pull request merged**
