### PR TITLE
Create pupmtp

### PR DESCRIPTION
**Pull request by rizalmart**
pupmtp is an application for mounting mtp devices via fuse by using simple-mtpfs by phatina 
Source code: https://github.com/phatina/simple-mtpfs
Requires fuse, libusb, and libmtp only

### CODE REVIEW

**Comment by wdlkmpx** [comment]
I compiled libmtp + simple-mtpfs, but i'm not sure how to test, i connected an android tablet and a phone, but apparently i don't know how to enable stuff haha. When i want something i just remove the micro sd card

So i guess i can merge this without testing it..

**Comment by wdlkmpx** [comment]
It also requires libgcrypt for MTPZ devices  (e.g. Zune). Which can be disabled --disable-mtpz

I found that  libmtp + simple-mtpfs quality as generic packages with --disable-mtpz, it compiles in slacko 14.0, and runs in later versions of slackware, debian, ubuntu...

**Comment by rizalmart** [comment]
I already tested that in my smartphone and it mounts the mtp and performs transfer files between across pc and mtp devices and vice versa

**Comment by wdlkmpx** [comment]
Ok, i'm merging this i haven't been able to make it work, perhaps my device is not supported

**Comment by jamesbond3142** [comment]
> Ok, i'm merging this i haven't been able to make it work, perhaps my device is not supported

Many reasons for that, yours is not the only one. We (=Fatdog) have simple-mtpfs-based MTP browser for a while now (which was based from what Mick wrote here: http://murga-linux.com/puppy/viewtopic.php?p=839972#839972 ). But your pupmtp seems to have a better looking GUI :)

First, libmtp has a list of known identifiers - if your device isn't in the list it won't work. But you can easily patch libmtp and re-compile to add your own device ID. Secondly, it has another issue, some devices are very picky; and/or libmtp has very serious timing issue. Branded devices (Samsung devices etc) are apparently more tolerant of libmtp and can happily work with it; but lesser known brands don't fare so well.

Well for me, it was so annoying because my phones are mostly not Samsung phones. I was forced to find another solution: adbfs. It worked for a while, but only up to Android 6. Adbfs failed completely on Android 7 onwards, oh joy :( 

I'm still looking a solution that works. Perhaps it is much simpler to install ftp server on the phone and use gftp for transferring files.

**Comment by jamesbond3142** [comment]
PS: the above isn't a criticism of puptmp; rather criticism of general state of matter with MTP devices. It's good have this merged for people whose phones __do__ work with MTP properly.

**Pull request merged**
