### PR TITLE
Automate the release of a slacko 7.0 successor with fixes

### PR DESCRIPTION
**Pull request by dimkr**
@01micko What do you think about releasing a 7.1 with fixes for critical issues in 7.0 soon? I can get this process automated, and 7.x can serve as additional testing ground for woof-CE.

(of course, the build workflows added in this branch need to pass first)

### CODE REVIEW

**Comment by 01micko** [comment]
@dimkr the slacko-7 build fails because we are building on HOSTARCH=x86_64, TARGETARCH=x86 but ..

```
cd: ../woof-out_x86_x86_slackware_14.2: No such file or directory
```

**Comment by dimkr** [comment]
> @dimkr the slacko-7 build fails because we are building on HOSTARCH=x86_64, TARGETARCH=x86 but ..
> 
> ```
> cd: ../woof-out_x86_x86_slackware_14.2: No such file or directory
> ```

Thanks, fixed!

I also made DISTRO_VERSION configurable (using a `sed`), so DISTRO_SPECS doesn't have to be changed every time we want to release a slacko 7.x bugfix release. I believe this should make 7.x a "zero-maintenance" release - every time a user complains about a critical bug we'll be able to issue a release after fixing the bug in woof-CE, without having to change anything in the woof-distro files of 7.0.

**Comment by 01micko** [comment]
Slacko 7 complains because FHSM is enabled in AUFS. Perhaps use the 4.19 DOTconfig?

**Comment by dimkr** [comment]
Seems to work now, and CI is much faster! Published several releases in my fork and ~~the size looks correct~~ booted one. It's important not to forget to add that `-`, and I forgot to do that in one of my test releases 😊 

flow

screeny

The releases are marked with `prerelease: true`, because maybe we'd like to see if the release is sane on real hardware, then edit the release and untick the "this is a pre-release" checkbox:

pre

What do you think, @01micko? I can change to `prerelease: false` and the new release will appear at the top of the list of release, watchers of the repo will get notified, etc', without that manual step.

**Comment by 01micko** [comment]
Been following closely and it looks good! I think changing prerelease is a good idea for 7.

**Comment by dimkr** [comment]
`build/boot/isolinux/isohybrid: error while loading shared libraries: libuuid.so.1: cannot open shared object file: No such file or directory`

Happens only in the 32-bit build 🤔

**Review by 01micko — APPROVED** [review]
@dimkr , can you merge in `testing` (1 commit outstanding) and I'm happy to merge back this PR and deal with any consequences.

**Comment by 01micko** [comment]
Done!

**Pull request merged**
