### PR TITLE
Remove the moon from 412.svg, to improve appearance on 16:9 screens

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by dimkr** [comment]
@01micko Do you have a solution for this issue, other than removing bad-looking elements? 431.svg is 4:3, and has similar scaling issues. Maybe we should make it 16:9, so it doesn't have to be stretched on most screens.

**Comment by 01micko** [comment]
I suppose some `xwinifo` gymnastics can be performed to adjust the `viewBox`, but I see you are just using `width="x" height="y"`.

I did something similar programmatically for screen rotation on a tablet, adjusting the viewBox and width= height=.

**Comment by 01micko** [comment]
Ok, 

4:3
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1101" height="800" viewBox="0 0 1101 800">
  <defs>
    <linearGradient id="d">
      <stop style="stop-color:#5064a9;stop-opacity:0" offset="0"/>
      <stop style="stop-color:#3d4f81;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient id="c">
      <stop style="stop-color:#3d4f81;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#5b90b8;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient id="b">
      <stop style="stop-color:#18275e;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#98cafb;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient x1="10" y1="80" x2="50" y2="20" id="a" gradientUnits="userSpaceOnUse" gradientTransform="translate(159.322 203.39)">
      <stop style="stop-color:#b9c3cf;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#6183a6;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient xlink:href="#b" id="e" x1="531.743" y1="-.22" x2="528.916" y2="452.328" gradientUnits="userSpaceOnUse" gradientTransform="matrix(1.00062 0 0 1 .059 .001)"/>
    <linearGradient xlink:href="#d" id="f" x1="89.095" y1="201.788" x2="161.22" y2="201.788" gradientUnits="userSpaceOnUse" gradientTransform="translate(8 -12)"/>
    <linearGradient xlink:href="#a" id="g" x1="502.954" y1="640.163" x2="487.001" y2="392.676" gradientUnits="userSpaceOnUse" gradientTransform="matrix(.99939 0 0 .99107 -1.742 3.495)"/>
    <radialGradient xlink:href="#c" id="h" cx="543.872" cy="540.5" fx="543.872" fy="540.5" r="550.499" gradientTransform="matrix(1.86466 .00087 -.0002 .474 -475.521 383.955)" gradientUnits="userSpaceOnUse"/>
  </defs>
  <path style="fill:#fff;fill-opacity:1;stroke-width:2.59737682" d="M.006-.004h1100.998v800.007H.006z"/>
  <path style="fill:url(#e);fill-opacity:1;stroke:none;stroke-width:1.00031066;stroke-opacity:1" d="M.006-.004h1100.995v548.276H.006z"/>
  <ellipse style="fill:url(#f);fill-opacity:1;stroke:none;stroke-opacity:1" cx="133.158" cy="189.788" rx="36.062" ry="33.941"/>
  <path style="fill:url(#g);fill-opacity:1;stroke:none;stroke-width:.9952212px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" d="M.006 548.271h1100.998v-114.91l-46.64 33.618-38.16-21.024-26.854 14.016-42.4-14.016-80.561 51.859-21.2-8.41-12.72 9.812-36.748-29.434-38.16-14.016-14.134 12.615-19.787-4.205-12.72 9.811-18.373-9.811-28.267 28.032-50.88-19.622-65.015 26.63L438.144 485.2l-45.227-37.843-53.708-33.638-14.133 7.008-15.547-18.22-5.653 5.606-15.547-7.008-16.96-9.812-15.547 7.008-38.16-7.008-22.614 19.623-46.971 70.079-50.885 15.417-45.227-16.819-40.987-28.031-10.97-18.283z"/>
  <path style="fill:url(#h);fill-opacity:1;stroke:none;stroke-width:1.02319765;stroke-opacity:1" d="M.006 548.271h1100.998v251.731H.006z"/>
  <path style="fill:#fff;fill-opacity:0" d="M.006-.004h1100.998v800.007H.006zM-39.598 319.167h31.113V645.85h-31.113z"/>
  <path style="fill:#fff;fill-opacity:0" d="M108.894 375.736H386.08v192.333H108.894z"/>
</svg>
```

===
1080p
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1920" height="1080" viewBox="0 100 1101 680">
  <defs>
    <linearGradient id="d">
      <stop style="stop-color:#5064a9;stop-opacity:0" offset="0"/>
      <stop style="stop-color:#3d4f81;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient id="c">
      <stop style="stop-color:#3d4f81;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#5b90b8;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient id="b">
      <stop style="stop-color:#18275e;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#98cafb;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient x1="10" y1="80" x2="50" y2="20" id="a" gradientUnits="userSpaceOnUse" gradientTransform="translate(159.322 203.39)">
      <stop style="stop-color:#b9c3cf;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#6183a6;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient xlink:href="#b" id="e" x1="531.743" y1="-.22" x2="528.916" y2="452.328" gradientUnits="userSpaceOnUse" gradientTransform="matrix(1.00062 0 0 1 .059 .001)"/>
    <linearGradient xlink:href="#d" id="f" x1="89.095" y1="201.788" x2="161.22" y2="201.788" gradientUnits="userSpaceOnUse" gradientTransform="translate(8 -12)"/>
    <linearGradient xlink:href="#a" id="g" x1="502.954" y1="640.163" x2="487.001" y2="392.676" gradientUnits="userSpaceOnUse" gradientTransform="matrix(.99939 0 0 .99107 -1.742 3.495)"/>
    <radialGradient xlink:href="#c" id="h" cx="543.872" cy="540.5" fx="543.872" fy="540.5" r="550.499" gradientTransform="matrix(1.86466 .00087 -.0002 .474 -475.521 383.955)" gradientUnits="userSpaceOnUse"/>
  </defs>
  <path style="fill:#fff;fill-opacity:1;stroke-width:2.59737682" d="M.006-.004h1100.998v800.007H.006z"/>
  <path style="fill:url(#e);fill-opacity:1;stroke:none;stroke-width:1.00031066;stroke-opacity:1" d="M.006-.004h1100.995v548.276H.006z"/>
  <ellipse style="fill:url(#f);fill-opacity:1;stroke:none;stroke-opacity:1" cx="133.158" cy="189.788" rx="36.062" ry="33.941"/>
  <path style="fill:url(#g);fill-opacity:1;stroke:none;stroke-width:.9952212px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" d="M.006 548.271h1100.998v-114.91l-46.64 33.618-38.16-21.024-26.854 14.016-42.4-14.016-80.561 51.859-21.2-8.41-12.72 9.812-36.748-29.434-38.16-14.016-14.134 12.615-19.787-4.205-12.72 9.811-18.373-9.811-28.267 28.032-50.88-19.622-65.015 26.63L438.144 485.2l-45.227-37.843-53.708-33.638-14.133 7.008-15.547-18.22-5.653 5.606-15.547-7.008-16.96-9.812-15.547 7.008-38.16-7.008-22.614 19.623-46.971 70.079-50.885 15.417-45.227-16.819-40.987-28.031-10.97-18.283z"/>
  <path style="fill:url(#h);fill-opacity:1;stroke:none;stroke-width:1.02319765;stroke-opacity:1" d="M.006 548.271h1100.998v251.731H.006z"/>
  <path style="fill:#fff;fill-opacity:0" d="M.006-.004h1100.998v800.007H.006zM-39.598 319.167h31.113V645.85h-31.113z"/>
  <path style="fill:#fff;fill-opacity:0" d="M108.894 375.736H386.08v192.333H108.894z"/>
</svg>
```
412_1080p
===
1080p dual monitors
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3840" height="1080" viewBox="0 300 1101 340">
  <defs>
    <linearGradient id="d">
      <stop style="stop-color:#5064a9;stop-opacity:0" offset="0"/>
      <stop style="stop-color:#3d4f81;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient id="c">
      <stop style="stop-color:#3d4f81;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#5b90b8;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient id="b">
      <stop style="stop-color:#18275e;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#98cafb;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient x1="10" y1="80" x2="50" y2="20" id="a" gradientUnits="userSpaceOnUse" gradientTransform="translate(159.322 203.39)">
      <stop style="stop-color:#b9c3cf;stop-opacity:1" offset="0"/>
      <stop style="stop-color:#6183a6;stop-opacity:1" offset="1"/>
    </linearGradient>
    <linearGradient xlink:href="#b" id="e" x1="531.743" y1="-.22" x2="528.916" y2="452.328" gradientUnits="userSpaceOnUse" gradientTransform="matrix(1.00062 0 0 1 .059 .001)"/>
    <linearGradient xlink:href="#d" id="f" x1="89.095" y1="201.788" x2="161.22" y2="201.788" gradientUnits="userSpaceOnUse" gradientTransform="translate(8 -12)"/>
    <linearGradient xlink:href="#a" id="g" x1="502.954" y1="640.163" x2="487.001" y2="392.676" gradientUnits="userSpaceOnUse" gradientTransform="matrix(.99939 0 0 .99107 -1.742 3.495)"/>
    <radialGradient xlink:href="#c" id="h" cx="543.872" cy="540.5" fx="543.872" fy="540.5" r="550.499" gradientTransform="matrix(1.86466 .00087 -.0002 .474 -475.521 383.955)" gradientUnits="userSpaceOnUse"/>
  </defs>
  <path style="fill:#fff;fill-opacity:1;stroke-width:2.59737682" d="M.006-.004h1100.998v800.007H.006z"/>
  <path style="fill:url(#e);fill-opacity:1;stroke:none;stroke-width:1.00031066;stroke-opacity:1" d="M.006-.004h1100.995v548.276H.006z"/>
  <ellipse style="fill:url(#f);fill-opacity:1;stroke:none;stroke-opacity:1" cx="133.158" cy="189.788" rx="36.062" ry="33.941"/>
  <path style="fill:url(#g);fill-opacity:1;stroke:none;stroke-width:.9952212px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" d="M.006 548.271h1100.998v-114.91l-46.64 33.618-38.16-21.024-26.854 14.016-42.4-14.016-80.561 51.859-21.2-8.41-12.72 9.812-36.748-29.434-38.16-14.016-14.134 12.615-19.787-4.205-12.72 9.811-18.373-9.811-28.267 28.032-50.88-19.622-65.015 26.63L438.144 485.2l-45.227-37.843-53.708-33.638-14.133 7.008-15.547-18.22-5.653 5.606-15.547-7.008-16.96-9.812-15.547 7.008-38.16-7.008-22.614 19.623-46.971 70.079-50.885 15.417-45.227-16.819-40.987-28.031-10.97-18.283z"/>
  <path style="fill:url(#h);fill-opacity:1;stroke:none;stroke-width:1.02319765;stroke-opacity:1" d="M.006 548.271h1100.998v251.731H.006z"/>
  <path style="fill:#fff;fill-opacity:0" d="M.006-.004h1100.998v800.007H.006zM-39.598 319.167h31.113V645.85h-31.113z"/>
  <path style="fill:#fff;fill-opacity:0" d="M108.894 375.736H386.08v192.333H108.894z"/>
</svg>
```
412_1080px2
===

## NOTES

- I _always_ use relative paths - easy to move elements later
- I don't use any editor apart from a text editor
- I _always_ format as `xml` - for ease of editing and syntax highlighting
- I _always_ use `viewBox`

**Comment by dimkr** [comment]
@01micko Thanks for all the pro tips! I think I'll make 16:9 first (manually, by changing the proportions between the sky and the lake), then scale to >= 1080p to make it less blurry.

**Comment by 01micko** [comment]
Just look at any of the icon themes for clues; they follow my notes. @zigbert and @technosaurus started me off and I became obsessed! :scream:

**Pull request merged**
