### PR TITLE
Create pupimgfile.desktop

### PR DESCRIPTION
**Pull request by rizalmart**

### CODE REVIEW

**Comment by wdlkmpx** [comment]
The Utility menu if full of apps, if this is merged, the category should be changed to Filesystem, it has fewer apps

**Comment by wdlkmpx** [comment]
The file was merged and it was renamed to filemnt-manager.desktop, which execs filement -manager

Categories=Filesystem

**Comment by peabee** [comment]
Categories=Filesystem 
is not recognised
should be same as Pmount:
Categories=X-Filesystem-mount

**Comment by jamesbond3142** [comment]
If you need to add a new category, then edit woof-code/rootfs-skeleton/etc/xdg/menus/puppy-filesystem.xml. You will see how "X-Filesystem-mount" is configure and you can easily add a new one as needed.

**Pull request merged**
