### PR TITLE
Refine frisbee installation process

### PR DESCRIPTION
**Pull request by rserwin1**
Previously, installation involved changing of softlinks and the package file list for builds.
These changes have the files set for a build, with the pinstall script making changes only for pet installations.
The files in /var should not have been included.
Request: PLease remove execute permissions from /usr/local/frisbee/func, which is only sourced.  The #!/bin/sh is present only to trigger formatting in geany.

### CODE REVIEW

**Comment by wdlkmpx** [comment]
This is going to get a little messy.. rerwin.. how about I replace the whole frisbee dir with the package you can provide here. Then permissions and everything will be ok. By adding you as the --author, the commit, the credits and numbers go to your account, then you can make pull requests with edits in the future..

**Comment by rserwin1** [comment]
Please tell me exactly how I am to get my frisbee directory or pet package to you?  I think you mentioned emailing the package, but cannot find that message.

**Comment by wdlkmpx** [comment]
I wrote a message from my gmail account but I think it got filtered or something.

I think I'll try and fix the conflicts, then I'll squash the commits into 1 (see #805), this will cause you problems in the testing branch, that's why you should create a branch for each pull request, then safely delete it.

But being you the mantainer of the projects, this could be easier for you, just send me the package with a brief description of the changes, my email is wdlkmpx attss gmmm , my forum username is 'jlst', although sometimes i can't read PMs... errors in the page/server.. not my fault. Then i'll just replace the folder, and git will determine what has changed

**Comment by rserwin1** [comment]
What is the nature of the conflicts?  I am surprised that there are any, 
since I  am the only one modifying frisbee.

I like the idea of using branches.  But I stayed with the testing branch 
for frisbee because that is how I submitted the original commits.  I 
find, though, that I need to keep the branches around so that I can add 
further changes to the contents of that branch. The changes do not get 
merged into my fork of the testing branch, so I get out of sync with the 
official testing branch.

wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
I see this:

CONFLICT (modify/delete): woof-code/rootfs-packages/frisbee/usr/local/frisbee/disconnect deleted in c4c511ce80c6abb2143ea8aadac85ab9a0c99043 and modified in HEAD. Version HEAD of woof-code/rootfs-packages/frisbee/usr/local/frisbee/disconnect left in tree.
and 2 more for "disconnect" and "frisbee_mode_disable"...

Are those files supposed to be deleted? If you look at the commit list, you'll see that those files  get deleted https://github.com/puppylinux-woof-CE/woof-CE/pull/804/commits/36643619da953edcac15d3727fa376a5f78fcbf0 https://github.com/puppylinux-woof-CE/woof-CE/pull/804/commits/184e7480edb3553d84082e40d8ed6f4d61c1889d , the description says "replaced by link set by pinstall.h".... I'll pretend this never happened and I'll proceed fix ...

**Comment by wdlkmpx** [comment]
Ah those files must be deleted

**Pull request closed without merging**
