### PR TITLE
Rationalise is ready i think to be merged

### PR DESCRIPTION
**Pull request by 01micko**
It does need a full review so I won't commit myself.

Changes from testing:

- a, y and f drive full support
- copying of packages to rootfs-complete (and a y z drives) now a function
- fdrive support with various mechanisms including kernel-kit, ability to include packages and downloading and packaging of non-free firmware (b43, nouveau, dvb to name a few)
- full integration into __0build.conf as not to impede 'headless' (well it's not quite headless :stuck_out_tongue: ) build
- others I've forgotten (run `git log` .. its all recorded)

Happy reviewing!

### CODE REVIEW

**Comment by 01micko** [comment]
For the curios.. isos, devx, kernel-source (32 + 64) are uploading to ibiblio

Look for 700/testing ... ETA 08.28.35 from right now. Approx iso sizes are 259 MB and 366 MB... respectively :clinking_glasses:

**Comment by ninaholic** [comment]
Hello @01micko ! I tried your Slacko 6.9.6.7, it looks nice. I connect to the internet no problems, but my browser button does not work. Maybe my Pentium M laptop is too old?

Here is screenshot: https://ibb.co/ciOVMQ

**Comment by 01micko** [comment]
Thanks for testing.

Hmmm ... I compiled pale moon (appears as 'new moon') with -march=athlon-xp
.. evodently not enough. Am now doing a build with:
 '-march=pentium3 -msse -mfpmath=sse' (as well as others) and will post
somewhere when cooked.

If it works for you I'll post a delta.

**Comment by 01micko** [comment]
@ninaholic palemoon is rebuilt and uploaded to ibiblio

http://distro.ibiblio.org/puppylinux/pet_packages-slacko14/palemoon-27.3.0-i686_701s_sse.pet
~31.5 MB (~700 kB smaller than the original)

Here is the full optimization line:
`--enable-optimize=\"-O2 -march=pentium3 -msse -mfpmath=sse -pipe -fomit-frame-pointer\"`

I suggest to unload the adrv (if you have an install - just mv it) , reboot, then install the pet. You can grab it with `wget`. That's how I tested it (posting from it now), but my cpu has all the instructions necessary and all my old computers have died.  :disappointed: so I can't do a full test. I did try with qemu but I don't think that qemu's virtual cpu is accurate.

**Comment by 01micko** [comment]
Ok, [Slacko 6967 is in the wild](http://www.murga-linux.com/puppy/viewtopic.php?p=954672#954672)

**Comment by ninaholic** [comment]
Thanks @01micko the pet works 👍 Congrats on releasing new Slacko version! :)

**Comment by 01micko** [comment]
OK thanks for testing @ninaholic. I'll do rebuild with the new pet and upload a delta. It will only be a few meg.

**Comment by 01micko** [comment]
@wdlkmpx  @mavrothal @woodenshoe-wi @ninaholic @peabee @zigbert @gyrog : if nobody objects I am going to merge this in 24 hours or so.

**Comment by wdlkmpx** [comment]
We'll find bugs eventually..

**Comment by 01micko** [comment]
I suppose this branch has served it's purpose and should be deleted. I'll wait until everyone knows that I'm deleting it and then do the deed; or anyone else with the right privileges can delete if they wish.

If we need a new branch for wild experiments then we can create one at any time.

**Comment by peabee** [comment]
LxPupSc built with "new" woof-ce testing:
> BUILD_FROM_WOOF='testing;deca49a;2017-05-21 20:38:32 +0800'
Didn't use the new adrv/fdrv facilities....
No obvious issues in build or in built system....
pupMd5sum needs enhancing to produce sha256 checksums (and SourceForge does not provide them....) so md5 will be needed for the foreseeable....

**Comment by 01micko** [comment]
> so md5 will be needed for the foreseeable....

There's no plans to deprecate, just add sha256 as an alternative.

**Comment by peabee** [comment]
Updated pupMd5sum:
[http://murga-linux.com/puppy/viewtopic.php?p=955428#955428](http://murga-linux.com/puppy/viewtopic.php?p=955428#955428)

**Pull request merged**
