### PR TITLE
add a gtkdialog main menu, that looks like a jwm menu

### PR DESCRIPTION
**Pull request by 01micko**
- this is independent of wayland, though won't suit running in X without mods
- suffers from the same bug as #2739 so this is issued as a draft
- also adds the clock menu
- doesn't use `fixmenus`, creates the menu on the fly

https://user-images.githubusercontent.com/1019119/147566066-443a182e-3698-4672-ab73-08d2bb3090f7.mp4

### CODE REVIEW

**Comment by dimkr** [comment]
Nice! I think it's better to cache the menu contents and update them via `fixmenus`, to make the menu faster to load.

Maybe we don't really need yambar, if this small menubar can be anchored to the top and expand to the screen/monitor width. I really like the idea of a GTK+ based panel, which doesn't need to be themed separately from applications.

**Comment by 01micko** [comment]
> Maybe we don't really need yambar, if this small menubar can be anchored to the top and expand to the screen/monitor width. I really like the idea of a GTK+ based panel, which doesn't need to be themed separately from applications.

Probably a bit beyond the scope of `gtkdialog` (however _is possible_) but certainly a `C` based version wouldn't be too difficult.

I did have the file cached in `/tmp` but it only takes a second to generate. Of course it isn't ready for production and certainly needs improvement, and caching really should be done to facilitate slower machines.

**Comment by 01micko** [comment]
bar

Everything you see here is functional - albeit with some issues. Not major ones, just placement.

**Comment by 01micko** [comment]
Holy cow, we _can_ have an entire `gtkdialog desktop`! (edit: I'm sure this is @zigbert 's dream :stuck_out_tongue: )

https://user-images.githubusercontent.com/1019119/147844157-fda6cc58-0a44-46cf-9a01-c9cf0a39a0a6.mp4

Sure, it's a bit crude, rude and unrefined but it _could_ be an option.

Here is the icon code; just a demo really, it could be expanded immensely to be a true pinboard with drive icons and all.


### wpdesktop
```bash
#!/bin/bash

# wpdesktop
# a pseudo icon pinboard for wayland compositors
# requires gtkdialog (gtk3), bash amd others

#*******************            styling             *******************#

cat > /tmp/${0##*\/}.css <<_S
window {
	background-color: rgba(0, 0, 0, 0.0);
}
button {
	background-color: rgba(0, 0, 0, 0.0);
	border: none;
}
_S

cat > /tmp/blank.svg <<_B
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <rect width="60"
     height="60"
     x="0"
     y="0"
     style="fill:#000;fill-opacity:0.0;fill-rule:evenodd;stroke-none;"
     id="rect1" />
</svg>
_B

PIXPATH=/usr/local/lib/X11/pixmaps/
HGT="<height>48</height>"
PAD='<pixmap><height>36</height><input file>/tmp/blank.svg</input></pixmap>'
#*******************            main                *******************#

export MAINWIN='<window title="wpdesktop" edge="topleft" layer="bottom">
	<hbox>
		<vbox space-expand="true" space-fill="false" spacing="20">
			'$PAD'
			<button relief="2" image-position="2">
				'$HGT'
				<input file>'$PIXPATH'home48.png</input>
				<label>Home</label>
				<action>defaultfilemanager &</action>
			</button>
		
			<button relief="2" image-position="2">
				'$HGT'
				<input file>'$PIXPATH'www48.png</input>
				<label>Browser</label>
				<action>defaultbrowser &</action>
			</button>
			<button relief="2" image-position="2">
				'$HGT'
				<input file>'$PIXPATH'email48.png</input>
				<label>Email</label>
				<action>defaultemail &</action>
			</button>
		
			<button relief="2" image-position="2">
				'$HGT'
				<input file>'$PIXPATH'chat48.png</input>
				<label>Chat</label>
				<action>defaultchat &</action>
			</button>
		</vbox>
	
	</hbox>
</window>'
gtkdialog -p MAINWIN --styles="/tmp/${0##*\/}.css" #>/dev/null 2>&1
```

**Comment by dimkr** [comment]
> Holy cow, we _can_ have an entire `gtkdialog desktop`! (edit: I'm sure this is @zigbert 's dream 😛 )

This is great but also disgusting 😆

**Comment by 01micko** [comment]
> > Holy cow, we _can_ have an entire `gtkdialog desktop`! (edit: I'm sure this is @zigbert 's dream stuck_out_tongue )
> 
> This is great but also disgusting laughing

..and pathetic :rofl:

**Comment by 01micko** [comment]
..and even scary.. this took 5 minutes

20220101_22h01m25s_grim

**Pull request closed without merging**
