### PR TITLE
fix quicksetup + and - bug for timezones that use GMT+ or GMT-

### PR DESCRIPTION
**Pull request by 01micko**
also fixes psync
added new script 'fix_gmt'

### CODE REVIEW

**Review by peabee — APPROVED** [review]
Looks OK to me (not really understanding what the problem is - living in the UK GMT+0 and GMT-0 are the same..)

**Comment by 01micko** [comment]
See [greengeeks problem](https://forum.puppylinux.com/viewtopic.php?f=118&t=2893&p=27330#p27330)

**Comment by gyrog** [comment]
@01micko,
Does this code eventually use the actual TZ variable?

I assume that you are aware that the actual TZ variable has the signs backwards, e.g. TZ=AEST-10 is correct for Queensland, at GMT+10.
And only the signed number of the TZ variable is significant in setting the timezone.

**Comment by 01micko** [comment]
> @01micko,
> Does this code eventually use the actual TZ variable?
> 

No

> I assume that you are aware that the actual TZ variable has the signs backwards, e.g. TZ=AEST-10 is correct for Queensland, at GMT+10.
> And only the signed number of the TZ variable is significant in setting the timezone.

Yes. That is what this PR addresses.

**Review by gyrog — APPROVED** [review]
Ok

**Pull request merged**
