### PR TITLE
Add Palemoon Petbuild

### PR DESCRIPTION
**Pull request by lakshayrohila**
I have renamed the branch. Earlier PR was this https://github.com/puppylinux-woof-CE/woof-CE/pull/3636.

### CODE REVIEW

**Comment by dimkr** [comment]
Looks good to me. Once you add this petbuild to at least one build configuration (jammy64?) it will join the cycle of weekly/bi-weekly test builds.

**Comment by lakshayrohila** [comment]
> Looks good to me. Once you add this petbuild to at least one build configuration (jammy64?) it will join the cycle of weekly/bi-weekly test builds.

I wanted to add this for jammy64 only. Should I wait for this PR to be merged, or test on jammy64 right away from my repo and then tell the status?

**Comment by dimkr** [comment]
> I wanted to add this for jammy64 only

Go ahead and do that! An unused petbuild can break and nobody would notice.

(And it's always a good idea to test a PR before it's merged, I test almost all of my PRs using release.yml)

**Comment by lakshayrohila** [comment]
@dimkr, I tested this petbuild in jammy64 (had to add package `libdbus-glib` as well). Everything worked well except for the icon file not being associated with the desktop file. The reason was that I had put icons files at `/usr/icons/`, not `/usr/pixmaps/`. Sym-linked the file there as well. Now it works!

Once this PR is merged, I'll create another PR updating few things in `jammy64`, including adding this.

**Pull request merged**
