### PR TITLE
Rename "605" to "Tahrpup" and give it a nicer wallpaper

### PR DESCRIPTION
**Pull request by dimkr**
The current one is an ugly placeholder, until we have something that 1) resembles the 6.0.5 one and 2) has better contrast, unless we make desktop icon labels black somehow and 3) works with today's flat icons.

Old:

New:

Together with the desktop icon labels, GTK+ 2 (ROX-Filer) and GTK+ 3 (Geany and Transmission):

### CODE REVIEW

**Comment by mrfricks** [comment]
i do prefer your other version (with the filled in vincents) as a picture but this one is less 'in your face' and maybe better suited for a wallpaper

**Comment by dimkr** [comment]
@01micko @mrfricks Objections to this PR?

**Comment by 01micko** [comment]
I'm ok with it but really @mrfricks holds the trump card.

**Comment by mrfricks** [comment]
no objections from me

**Pull request merged**
