### PR TITLE
rootfs-packages: Pkg 1.9.23w

### PR DESCRIPTION
**Pull request by wdlkmpx**
this is a slightly patched and modified Pkg

It probably needs a special pinstall.sh for woof. It works in dpup ootb. a raspup entry probably needs to be added to /etc/pkg/sources-all

The gtk gui is a bit slow to display actions for a specific pkg, and [really] slow to display when it's called from the file manager to install a .pet/.deb/.txz package.

It's mergeable, but testing can be performed in dksahkjfgwfhcw.vyegfiuehlkbnx

### CODE REVIEW

**Comment by sc0ttj** [comment]
Yeah `list_deps()` and `find_deps()` are very slow... My bad!
https://github.com/puppylinux-woof-CE/Pkg/issues/7

**Comment by s243a** [comment]
> Yeah `list_deps()` and `find_deps()` are very slow... My bad!
> [puppylinux-woof-CE/Pkg#7](https://github.com/puppylinux-woof-CE/Pkg/issues/7)

I think that these functions are working much faster now right? I've noticed big speed improvements with recent updates to pkg.

**Comment by sc0ttj** [comment]
@s243a  Maybe Pkg dep resolution is faster in your version of Pkg, but not in mine - these funcs haven't been touched...  And dep resolution is still as slow as ever on the latest Pkg in master branch (Gitlab).. 

Building PPA/Debian repos is now much faster though, thanks to your gawk work.. 

It' easy to be fooled into _thinking_ they're faster, by breaking the list of deps that Pkg actually parses (I've done that a few times)..

I recently made a `fix/shellcheck` branch (going through shellcheck, fixes errors and warning) which made Pkg faster, but actually broke various functions.. I'll have to revert it, and try again... 

Three is a lot of speed improvements than _can_ be made ... but each little change needs to be made on it own, then Pkg heavily tested (adding, removing, building packages & repos), then if all good, keep it ... 

It's slow going .. but will be worth it..

**Comment by sc0ttj** [comment]
@wdlkmpx  I've just merged a bunch of fixes and clean ups into the latest woof-ce fork of Pkg.. You prob wanna merge it into this PR.

The code will be slightly less horrible for you to read.

**Comment by wdlkmpx** [comment]
I read the commit diffs and saw a few changes that I wanted to apply, shellcheck seems to be a very good app. Statically linked binaries can be found here:
https://shellcheck.storage.googleapis.com/index.html

It's a bit disturbing that there's no i686 static binary, but they always provide i686 windows binaries.

By reading this PR diffs I also became aware of many things I overlooked, I guess things are clearer when they are displayed in a web browser.

At the moment I'm unable to make changes to this PR, but I can close it and open another one.

..I don't know,  sc0ttj might want to package Pkg and upload it to the noarch git repo 
https://github.com/puppylinux-woof-CE/woof-CE/wiki/Adding-or-Updating-noarch-packages 
 then anybody can install it from the PPM, and I can open a PR with changes to make it a default pkg in the default woofce builds by adding it to the DISTRO_PKGS_SPECS-* file (16)

**Comment by sc0ttj** [comment]
I have an even more cleaned up, (slightly) less horrible to read branch of Pkg on Gitlab, called `fixes/cleanups`... just merged..  I simplified the ordering of the code, and removed as much if nesting as possible..

Essentially, after doing lots of shellcheck fixes, I went over the main funcs again, and cleaned up the code in various ways: https://gitlab.com/sc0ttj/Pkg/merge_requests/19/edit

---

## From the PR:

Code clean ups, makes various funcs easier to work on... Also includes a few (small) speed ups, and some bug fixes.

- fixes `pkg_uninstall()` failure to get dependent packages
- fixes in `get_pkg_filename`: return 1 package name or nothing 
- fix: run post install stuff in a sub shell
- fix issues ( think!): 
  - 87 (suppress errors regression)
  - 90 (search local *.files first in `is_installed_pkg()`
  - 89 (weak repo name matching in `get_dep_entry`)
- (minor) speedups in package name and dep resolution, checking package status (installed or not)
- re-organised code in various functions: 
  - clearer logic and ordering
  - moved code out of `if` blocks where possible, less indentation  
  - removed unnecessary code

**Comment by sc0ttj** [comment]
> .I don't know, sc0ttj might want to package Pkg and upload it to the noarch git repo
> https://github.com/puppylinux-woof-CE/woof-CE/wiki/Adding-or-Updating-noarch-packages
> then anybody can install it from the PPM, and I can open a PR with changes to make it a default pkg in the default woofce builds by adding it to the DISTRO_PKGS_SPECS-* file (16)

OK .. I will get1 or 2 more PRs (not ready) merged, then I will release the PET as 1.9.23

**Pull request closed without merging**
