### PR TITLE
sort attempt #2

### PR DESCRIPTION
**Pull request by ninaholic**
I kept playing around with https://github.com/puppylinux-woof-CE/woof-CE/commit/f20f4bc11d2fa73af088c0968d42dbb6bdaa2b40 until I found SOMETHING that works. Feel free to test/review :laughing:

https://ibb.co/eD0Vvv

### CODE REVIEW

**Comment by ninaholic** [comment]
Here is a new screenshot. Improvements welcome :)

https://ibb.co/gTUPqv

**Comment by 01micko** [comment]
My comment is that the shield icons are a poor choice. "RED" inspires warning. I guess you feel it isn't the best choice either but of course we can construct new icons :wink:

**Comment by ninaholic** [comment]
@01micko haha yes, red warning always scares me too, I guess green is only good if you are hunting for free wifi :laughing:

I tried your pngs and they look modern and clear, maybe red vs. green is more distinguishable as small icon but yours matches with the taskbar wi-fi, here is screenshot in Slacko 6.9.9.5:

https://ibb.co/dWwtYF

**Comment by ninaholic** [comment]
@01micko: Can you add your two icons to?

https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-code/rootfs-skeleton/usr/share/pixmaps/puppy

or

https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-code/rootfs-packages/simple_network_setup/usr/share/pixmaps/puppy

I would like to try adding them into the commit. :D

**Comment by ninaholic** [comment]
I will re-add each commit separately so each can be evaluated individually. :+1:

**Comment by 01micko** [comment]
Why not merge them yourself?

Preview ..

wireless_closed

wireless_open

These are fully reworked and I think are a little clearer.

Following is the SVG code

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="100" width="100">

  <g transform="rotate(-45 50 80)">
    <path d="m 50,62 a 18,18 0 0 1 18,18 l 7,0 a 25,25 0 0 0 -25,-25 z" style="fill:#2BB927;stroke:#222222;stroke-width:1"/>
    <path d="m 50,47 a 33,33 0 0 1 33,33 l 7,0 a 40,40 0 0 0 -40,-40 z" style="fill:#2BB927;stroke:#222222;stroke-width:1"/>
    <path d="m 50,32 a 48,48 0 0 1 48,48 l 7,0 a 55,55 0 0 0 -55,-55 z" style="fill:#2BB927;stroke:#222222;stroke-width:1"/>
    <path d="m 50,17 a 63,63 0 0 1 63,63 l 7,0 a 70,70 0 0 0 -70,-70 z" style="fill:#2BB927;stroke:#222222;stroke-width:1"/>
  </g>
  <ellipse cx="50" cy="80" rx="10" ry="10" style="fill:#2BB927;stroke:#222222;stroke-width:2"/>
</svg>
```

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="100" width="100">

  <g transform="rotate(-45 50 80)">
    <path d="m 50,62 a 18,18 0 0 1 18,18 l 7,0 a 25,25 0 0 0 -25,-25 z" style="fill:#555;stroke:#222222;stroke-width:1"/>
    <path d="m 50,47 a 33,33 0 0 1 33,33 l 7,0 a 40,40 0 0 0 -40,-40 z" style="fill:#555;stroke:#222222;stroke-width:1"/>
    <path d="m 50,32 a 48,48 0 0 1 48,48 l 7,0 a 55,55 0 0 0 -55,-55 z" style="fill:#555;stroke:#222222;stroke-width:1"/>
    <path d="m 50,17 a 63,63 0 0 1 63,63 l 7,0 a 70,70 0 0 0 -70,-70 z" style="fill:#555;stroke:#222222;stroke-width:1"/>
  </g>
  <ellipse cx="50" cy="80" rx="10" ry="10" style="fill:#000;stroke:#222222;stroke-width:2"/>
  <circle cx="27" cy="27" r="24" style="fill:#F1AB24;stroke:#875900;stroke-width:2;fill-opacity:0.8;stroke-opacity:0.6"/>
  <path fill="#333333" d="m 27,7 c -4,0 -9,2 -11,6 -1,2 -1,9 -1,9 0,0 -2,0 -3,0 0,5 0,11 0,17 0,3 4,6 7,6 6,0 11,0 17,0 2,0 6,-3 6,-6 0,-6 0,-11 0,-17 -2,0 -2,0 -3,0 0,0 0,-6 -1,-9 C 36,9 31,7 27,7 z m 8,9 0,6 -16,0 c 0,-6 0,-6 0,-6 0,-4 5,-5 8,-5 3,0 8,1 8,5 z m -9,10 c 4,0 5,4 2,6 l 2,8 -7,0 2,-8 c -3,-2 -2,-6 1,-6 z"/>
</svg>
```

**Comment by ninaholic** [comment]
Thanks 01micko! I did not know I could upload file with web interface, but found a way around it just now... I think. YES! 😆

**Pull request closed without merging**
