### PR TITLE
installpkg.sh: Move package files to a folder

### PR DESCRIPTION
**Pull request by rizalmart**
Moving package files and uninstall script to folders to organize PPM folder structure

### CODE REVIEW

**Comment by s243a** [comment]
I haven't looked at the code yet but be warned, this will have a large impact on pkg (scottman's package manager). If you want to do this then you should get the related changes approved by Scott. It should also be done in a back compatible way.

P.S. I do like the idea though. We just need to be sure that we are willing to update pkg as well and at the same time.

**Comment by s243a** [comment]
One way that this could be done so that pkg doesn't need to be changed right away is to have some config variable that says where the package files dir is located.

**Comment by sc0ttj** [comment]
Yeah I don't see much benefit in this change, on it's own... 

I _do_ see it would be nice to move the `.files` files into their own dir, but not really worth it IMHO...

**Comment by rizalmart** [comment]
> Yeah I don't see much benefit in this change, on it's own...
> 
> I _do_ see it would be nice to move the `.files` files into their own dir, but not really worth it IMHO...

For me its very worth it. If the ppm data folder structure was organized, it was very easy to perform audit in certain situation also it prevents accidental deletion of a target file

**Comment by 01micko** [comment]
While Pkg is now a possibility in a woof build this PR brings an incompatibility.

**Pull request closed without merging**
