### PR TITLE
changes for a proper default rootfs-packages.conf

### PR DESCRIPTION
**Pull request by wdlkmpx**

### CODE REVIEW

**Comment by peabee** [comment]
I won't be doing any new upupbb builds with a new version of woof-ce until:
a. I can understand what all the recent changes mean....
b. I am confident that all the changes have been made so that woof-ce testing is "stable"....

**Comment by wdlkmpx** [comment]
Just like the other pull request, This one is open for discussion, this
doesn't show words but actions, that's the only way to do things

I forgot to add text

Testing (branch) is ok for release.

I'm trying to address the issue raised by wiake

I wrote this little doc:
https://github.com/puppylinux-woof-CE/woof-CE-apps/blob/master/README.md

What i've been doing the last 3 years is things you don't understand, and
thanks to all those changes woofce is better than ever.

**Comment by wdlkmpx** [comment]
The purpose of this change is to serve as the 1st step to simplify 3builddistro a bit more without the dialog to select extra packages. This implies editing the PKGS_SPECS, in this first step, only pups that require jwm_config and ptheme.

woof-CE-noarch is something needed.. contributors and the team no longer have excuses, they can add their own apps to noarch if they wish.

woof-CE-apps: this might seem unnecessary, but in the end it might be a good idea, since many of the rootfs-packages are trivial apps, and their history of changes "pollutes" the history of the main git repo, and many more trivial apps can be added, This idea can be dropped... it can be woof-CE/apps (main repo)

I added apps to rootfs-skeleton, many of them are true core apps and woof-ce specific, although rerwin undid a couple of those changes.

History:
https://github.com/puppylinux-woof-CE/woof-CE-apps/commits/master
https://github.com/puppylinux-woof-CE/woof-CE-noarch/commits/master
https://github.com/puppylinux-woof-CE/woof-CE/pull/1363/commits

This was just a thought i had, but it quickly materialized, because i can make it happen, that's the only reason.

**Comment by wdlkmpx** [comment]
My idea is that rootfs-packages should only contain extra packages that are automatically added to the main sfs by the build system

This can be open for a while and some changes to adjust stuff can happen while people try to process and comment on this issue. Meanwhile i'll focus on other things.

**Comment by wdlkmpx** [comment]
I built a dpup stretch testing all the changes i made to the different repos, the result is a completely automated 3builddistro (in my case), with no regressions.

**Comment by mavrothal** [comment]
> I won't be doing any new upupbb builds with a new version of woof-ce until:

So what's happening with the puppy 8 "official" release?

**Comment by peabee** [comment]
BionicPup32-8.0 is released built using latest testing so has noarch on github....

**Comment by ninaholic** [comment]
I tried slackware 14.0 build with this commit added and it's working good as before (loading new noarch in ppm list). Downloaded from this link (maybe there is a better way? :smile: ): https://github.com/puppylinux-woof-CE/woof-CE/tree/68bfaf2e6845c70197c5303c2e0a32edfdde75e6

Saw one warning in 3builddistro-Z "line 1105: initrd-tree/DISTRO_SPECS not found" but it happened before too and seems harmless (Ubuntu related).

**Comment by wdlkmpx** [comment]
I wasn't thinking straight when i did this, closing.

Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/d6dcb5fe5f88ed06d79aabcde69cb81052876cb7 "automates handling of rootfs-packages"

And it makes the whole build system basically completely automated (for all default builds),
but you can still find the usual behavior in 2createpackages.

Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/4562712d0f38babe97fd596159274ff27ca0442e  adds woof-code/build.sh

To achieve this i have deleted (and rewritten) lots of code and there's more to delete.

So now test builds should be easy to produce.
I built a dpup from start to finish by running only one command: ./build.sh

If we assume that the experimental branch is indeed the future of this project..

**Comment by peabee** [comment]
Experimental/zwn will need a huge amount of work to get it to an equivalent state of completeness, flexibility and stability as woof-ce/testing

**Pull request closed without merging**
