### PR TITLE
Run acpid and lock screen on lid close (#2336)

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by 01micko** [comment]
Should this go further and replace acpid-busibox?

**Comment by dimkr** [comment]
> Should this go further and replace acpid-busibox?

Maybe. I see no reason why not to put acpid-busibox (with changes) in rootfs-packages.

**Comment by 01micko** [comment]
> > Should this go further and replace acpid-busibox?
> 
> Maybe. I see no reason why not to put acpid-busibox (with changes) in rootfs-packages.

Yes, probably a better idea :bulb:

**Comment by 01micko** [comment]
Looks fine to me.. ready to merge?

**Comment by dimkr** [comment]
Building now, I can open separate PRs if I find problems.

**Comment by dimkr** [comment]
Oh no, it must be _ and not -

**Comment by 01micko** [comment]
> Building now, I can open separate PRs if I find problems.

Glad you found _ is best. Merging.

**Pull request merged**
