### PR TITLE
add 'pupmoon' font to woof-code/rootfs-packages/

### PR DESCRIPTION
**Pull request by 01micko**
Attribution given to IcoMoon in the README.md

### CODE REVIEW

**Comment by dimkr** [comment]
I think this font should be in a separate repo, because binary files make the repo bigger and slower to clone (especially after you change them many times).

**Comment by 01micko** [comment]
> I think this font should be in a separate repo, because binary files make the repo bigger and slower to clone (especially after you change them many times).

It is up at ibiblio in raw form, which would need a petbuild, but I can put in `woof-CE-noarch` as a .pet. Preference?

**Comment by dimkr** [comment]
> It is up at ibiblio in raw form, which would need a petbuild, but I can put in `woof-CE-noarch` as a .pet. Preference?

If you ask me - petbuild

**Comment by 01micko** [comment]
Ok, I'll make it super simple. I'll re-upload as `tar.xz` in the exact structure it is in now, without pet.specs.

I'll just post it here.

```
pupmoon-font-1.0|pupmoon-font|1.0||Desktop|512K||pupmoon-font-1.0.pet||Icon font for Puppy from IcoMoon||||
```

**Comment by 01micko** [comment]
Ok, uploaded

https://distro.ibiblio.org/puppylinux/sources/p/pupmoon-font-1.0.tar.xz

```
sha256sum pupmoon-font-1.0.tar.xz 
0f4cf07d0eb34e1ffaa3c1f4194ccf7cb916865953f3aaadf5182a3d5f0b7135  pupmoon-font-1.0.tar.xz
```

**Comment by 01micko** [comment]
BTW, the docs are important for usage and attribution in the README.md

**Pull request closed without merging**
