### PR TITLE
Add swaylock and run it when idle, on lid close, or on Super+l

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by 01micko** [comment]
I tried swaylock and the shadow backend failed miserably for me, Does it work for you? ~or are you using `PAM`?~ (edit: I see it's disabled)

**Comment by dimkr** [comment]
> I tried swaylock and the shadow backend failed miserably for me, Does it work for you or are you using `PAM`?

It works without PAM. I had to patch it, so it doesn't refuse to run as root.

**Comment by 01micko** [comment]
> It works without PAM. I had to patch it, so it doesn't refuse to run as root.

Yes, I patched too, and ran but the input was messed up and I couldn't unlock.

**Comment by 01micko** [comment]
Ok, I'll pass this.

**Review by 01micko — APPROVED** [review]

**Pull request merged**
