### PR TITLE
Replace yad with https://github.com/step-/yad

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Review by step- — APPROVED** [review]
@dimkr, so is this how I could do future updates to yad: by pushing commits to this pull request?

**Comment by dimkr** [comment]
> @dimkr, so is this how I could do future updates to yad: by pushing commits to this pull request?

New pull requests similar to 146a54f

**Comment by dimkr** [comment]
@01micko Any reason not to use the fork?

**Comment by 01micko** [comment]
> @01micko Any reason not to use the fork?

None whatsoever :)

**Pull request merged**
