### PR TITLE
Make lxterminal the default in focal64

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by 01micko** [comment]
Probably should fix rox options so that `<Option name="menu_xterm">defaultterminal</Option>` is set too, just for consistency across the board.

https://github.com/puppylinux-woof-CE/woof-CE/blob/c2db96076c9b758c053cc4408dc406df82f017eb/woof-code/rootfs-petbuilds/rox-filer/root/.config/rox.sourceforge.net/ROX-Filer/Options#L10

EDIT: Probably a separate commit/PR

**Comment by mrfricks** [comment]
hi @dimkr ,
is lxterminal a petbuild? or is it taken from the ubuntu repo?  
if it's from the repo it brings in libvte-2.61 which installs 
/etc/profile.d/vte-2.91.sh
/etc/profile.d/vte.csh
these cause this error to be displayed in all terminals
```
bash: /etc/profile.d/vte.csh: line 19: syntax error near unexpected token `!'
bash: /etc/profile.d/vte.csh: line 19: `if ( ! $?prompt | ! $?tcsh | ! $?TERM | ! $?VTE_VERSION ) exit'
```

**Comment by dimkr** [comment]
@mrfricks It's a petbuild. I haven't seen this issue when I tested this PR 🤔 

I'll take a look tomorrow.

**Comment by dimkr** [comment]
Looks fine in https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/1021233171, no errors.

noerror

**Pull request merged**
