### PR TITLE
Fix deletion of big Mesa drivers

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Review by peabee — COMMENTED** [review]
Sounds good if it doesn't have any consequences ..... what do the deleted drivers do? what will be the effect of deleting them?

**Comment by rizalmart** [comment]
Oh boy deleting vmware dri maybe a bad idea.

**Comment by dimkr** [comment]
The drivers this template already tried to delete are all used by some VMs. But OpenGL should still work, using swrast. I only added zink to the list, because I don't think it's in use today.

**Comment by 01micko** [comment]
Why closed?

**Comment by dimkr** [comment]
@01micko I think @peabee and @rizalmart oppose this change 🤔

**Pull request closed without merging**
