### PR TITLE
Download icons from puppy repos

### LINKED ISSUE #2404: icon theme maintenance
These icone themes, `PMaterial`, `Puppy Standard` and `Puppy Flat` have their own git repos so for ease of maintenance these should be removed from `rootfs-packages` and be made ~into petbuilds~ downladable in `3builddistro` or similar.

### PR DESCRIPTION
**Pull request by 01micko**
Why?
- ease of maintenance
- less chance of commit mistakes as the icon files are many

This closes #2404

This a draft for now as `support/get_icons.sh` downloads from my github pending PRs [#3](https://github.com/puppylinux-woof-CE/puppy_flat_theme/pull/3), [#10](https://github.com/puppylinux-woof-CE/puppy_icon_theme/pull/10) and [#4](https://github.com/puppylinux-woof-CE/Pmaterial/pull/4)

To DO

- [x] fix repos so that PR event doesn't trigger release
- [x] fix `get_icons.sh` to download direct from 'latest'
- [x] fix `get_icons.sh` so downloads aren't deleted (not sure about this - might delete them after a certain age.. 72 hours?)
- [x] fix `get_icons.sh` to use `wget -t3`
- [ ] fix `get_icons.sh` `$GUSER` when PRs [#3](https://github.com/puppylinux-woof-CE/puppy_flat_theme/pull/3), [#10](https://github.com/puppylinux-woof-CE/puppy_icon_theme/pull/10) and [#4](https://github.com/puppylinux-woof-CE/Pmaterial/pull/4) are merged.

### CODE REVIEW

**Comment by dimkr** [comment]
- dld_icons.sh can be simplified: just download https://github.com/01micko/Pmaterial/releases/latest/download/pmaterial_icons.tar.xz (always points to the latest release)
- In the icons repo, make sure you build if it's a PR build, and publish a release if it's a push to master (`if: github.event_name == 'push' && github.ref == 'refs/heads/master)`) - it won't be fun if the latest release is built from a WIP PR
- Don't forget to change GUSER
- I'd remove `rm -f ../local-repositories/icons/${ICO_PKG}` (and avoid download if it exists), so the already downloaded icons in local-repositories are kept between woof-CE runs
- Doesn't ~Pmaterial fall back to puppy_flat_theme~ (I remember it has some fallback)? If yes, then the loop in 3builddistro should also download dependencies inherits
- Not sure if we want to do this, and not sure if now is a good time: the icon themes can be removed from the history of this git repo, making it much smaller and faster to clone with full history; this will take time and require a force-push to testing
- wget -t 1 can be unreliable on GitHub Actions, make it -t 3

**Comment by 01micko** [comment]
>     * dld_icons.sh can be simplified: just download https://github.com/01micko/Pmaterial/releases/latest/download/pmaterial_icons.tar.xz (always points to the latest release)

Will do.

> 
>     * In the icons repo, make sure you build if it's a PR build, and publish a release if it's a push to master (`if: github.event_name == 'push' && github.ref == 'refs/heads/master)`) - it won't be fun if the latest release is built from a WIP PR

Ok, I'll try the `if` statement

> 
>     * Don't forget to change GUSER
> 

Yes, once icon repo's are ready to merge that will happen.

>     * I'd remove `rm -f ../local-repositories/icons/${ICO_PKG}` (and avoid download if it exists), so the already downloaded icons in local-repositories are kept between woof-CE runs
> 

As long as wget clobbers the old version!

>     * Doesn't ~Pmaterial fall back to puppy_flat_theme~ (I remember it has some fallback)? If yes, then the loop in 3builddistro should also download dependencies inherits
> 

All icon sets now use the same `build.conf` so they are all parallel.

>     * Not sure if we want to do this, and not sure if now is a good time: the icon themes can be removed from the history of this git repo, making it much smaller and faster to clone with full history; this will take time and require a force-push to testing
> 

Well, IDK how to 'force push' .. suggestion?

>     * wget -t 1 can be unreliable on GitHub Actions, make it -t 3

I'll fix it.

**Comment by dimkr** [comment]
> Well, IDK how to 'force push' .. suggestion?

I can handle this.

I've had some experience with git history rewrite tools and file deletion that goes all the way back to the initial commit. They're usually slow, and require `push --force` when they're done, because the "clean" branch no longer branches off the "dirty" branch, and this can break links (because commit hashes change). Not fun at all.

Again - not sure if we want this, but I can do this if we decide we do.

**Comment by 01micko** [comment]
The casual user can always download with `--depth=n` and probably should be a recommendation.

**Comment by 01micko** [comment]
Ok, so is this correct in the workflow?

```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: ./puppy.sh
      - name: Create Release
        if: ​github.event_name == 'push' && github.ref == 'refs/heads/master
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.run_number }}
          release_name: v${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: ​github.event_name == 'push' && github.ref == 'refs/heads/master
        id: upload-release-asset   
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./puppy_flat_icons.tar.xz
          asset_name: puppy_flat_icons.tar.xz
          asset_content_type: application/x-xz-compressed-tar
      - name: Upload Release Asset 1
        if: ​github.event_name == 'push' && github.ref == 'refs/heads/master
        id: upload-release-asset-1  
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./puppy_flat_icons.tar.xz.sha256.txt
          asset_name: puppy_flat_icons.tar.xz.sha256.txt
          asset_content_type: text/plain

**Comment by dimkr** [comment]
> Ok, so is this correct in the workflow?

Yes, looks correct to me.

**Comment by 01micko** [comment]
> > Ok, so is this correct in the workflow?
> 
> Yes, looks correct to me.

Ok, I'll try it soon.

**Comment by 01micko** [comment]
closing re #2426

**Pull request closed without merging**
