### PR TITLE
Update dependencies.sh

### PR DESCRIPTION
**Pull request by rizalmart**
Contain ppm temp files in a folder

### CODE REVIEW

**Comment by wdlkmpx** [comment]
You are testing all these changes in a woofce pup that was built recently aren't you? Otherwise it will take some time to test and fix the issues that may arise.. like, a lot of time.

In the experimental branch i also deleted a lot of code, so it will make the rebase process a bit long

**Comment by rizalmart** [comment]
Yes I tested it these codes on 2016 woof-ce built but I took some cautions before taking a shot on editing the code for this recent woof-ce

**Comment by wdlkmpx** [comment]
That's quite old. Fortunately i almost never edit the ppm, but when i do, some large changes happen and indeed some large happened in 2018 and even larger changes happen in 2019 (experimental branch.. i simplified a bit because it's too buggy.

Someone who releases very often is peebee, a recent iso of his lxpups is probably what you should be testing on, it's very close to a xslacko, you could just remove packages and leave the ones you want including pcmanfm and that would probably make you happy. And thunar will be no more.

**Comment by rizalmart** [comment]
The modifications that I made on PPM was just to isolate those temporary files made by ppm. Because I noticed that PPM produces lots of temporary files under /tmp which made the PPM harder to diagnose or troubleshoot sometimes.

**Comment by wdlkmpx** [comment]
I see you opened too many pull requests for a single change: create ppm files in a folder.

It does help to see all the changes, but I guess you should also share the files in a single tar.gz archive, so people can test it. For sns and network wizard you might want to contact rserwin1..

**Comment by rizalmart** [comment]
Thats a tough decision to make that move because all ppm scripts are tightly connected to each other

**Comment by wdlkmpx** [comment]
I rarely use the ppm, specially without the changes to simplify and
make it less buggy... I also no longer use builds from the testing
branch,  but i do merge all the changes from testing into the
experimental branch, and these changes will ensure a long rebase
process.

But let's focus on these pull requests, which all of them belong to a
single change, which is possible to achieve using the git command line
app, but requires wasting a lot of time learning how to use it.

A tarball with the modified ppm sripts would be welcome... although i
fear i may not be able to test them.. the ppm in the experimental
branch is fixed to work without the debian multiarch symlinks.. and
that's what i have. Using older ppms will break the system in a build
from the experimental branch.. or at least will cause some massive.

A tarball with the modified ppm sripts would be welcome..

**Comment by wdlkmpx** [comment]
Ok i think this change is ok to merge, it's about replacing `/tmp/` with `/tmp/petget_proc/`

I can edit all the ppm scripts in a single commit assigning you as the author of the commit. It will look like this
`authored by rizalmart commited by wdlkmpx`

Stats will go your account.

After that, all the related pull request will be closed, because everything was already merged.. what do you think?

**Comment by rizalmart** [comment]
Thats okay. At least ppm was easier to troubleshoot.

**Comment by rizalmart** [comment]
Also take a look also at my pulled request at mount script. The ntfs mount error logs are also isolated to a folder.

**Pull request closed without merging**
