### PR TITLE
icons: create a custom hicolor icon theme directory

### LINKED ISSUE #3781: Jammy64: evince: Icons not found with Pmaterial
Here are few examples (with Pmaterial icon theme):-

And their counterparts in breeze icon theme:-
breeze1
breeze2

@dimkr, I also followed your advice to build without Pmaterial icon cache (See https://github.com/puppylinux-woof-CE/woof-CE/compare/testing...lakshayrohila:woof-CE:test/jammy64#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721).

### PR DESCRIPTION
**Pull request by 01micko**
and start by populating it with some missing evince icons closes #3781 #3784

### CODE REVIEW

**Review by lakshayrohila — APPROVED** [review]
Thanks for this PR!

**Comment by 01micko** [comment]
OK, I just tested myself with Puppy Standard and looks ok. More contrast?

icons-evince

**Comment by 01micko** [comment]
So I added more contrast and slightly thicker lines and it looks better.

menu


send

**Comment by 01micko** [comment]
This PR solves the immediate issue in #3781 

I've done a quick build and the icons survive the woof process so I'm merging.

Any other missing icons in _any_ app feel free to ping me and wecan add them to `hicolor/scalable`.

**Pull request merged**
