### PR TITLE
blkinfo - format blkid's output

### PR DESCRIPTION
**Pull request by wdlkmpx**
A generic script that works in any distro
http://murga-linux.com/puppy/viewtopic.php?p=877628#877628

### CODE REVIEW

**Comment by mavrothal** [comment]
It looks like that is missing few things
```
# blkid
/dev/loop0: TYPE="squashfs" 
/dev/loop1: TYPE="squashfs" 
/dev/loop4: TYPE="squashfs" 
/dev/sda1: UUID="0fe410be-73a3-43fc-b58d-a930cf3dba66" TYPE="ext4" 
/dev/sda2: UUID="e46c64e7-4b59-419a-a9d5-20e1641ad78c" TYPE="swap" 
/dev/sda3: UUID="e1acf35b-f0d4-40c8-866a-cd1b5de097dd" TYPE="ext4" 
/dev/sdb1: UUID="F8CD-98D8" TYPE="vfat" 
/dev/sdb2: UUID="bf3c2297-17bf-4d36-a3d7-6289dd037d3f" TYPE="ext2" 
/dev/sdb3: UUID="68f66810-f0ca-45cc-93ba-24b001612d40" SEC_TYPE="ext2" TYPE="ext3" 
/dev/sdb4: UUID="26835071-9953-42bf-b938-50b1c82ff43b" TYPE="ext4" 
# ./blkinfo 
/dev/sda1|ext4|0fe410be-73a3-43fc-b58d-a930cf3dba66|
/dev/sda2|swap|e46c64e7-4b59-419a-a9d5-20e1641ad78c|
/dev/sda3|ext4|e1acf35b-f0d4-40c8-866a-cd1b5de097dd|
/dev/sdb1|vfat|F8CD-98D8|
/dev/sdb2|ext2|bf3c2297-17bf-4d36-a3d7-6289dd037d3f|
/dev/sdb3|ext3|68f66810-f0ca-45cc-93ba-24b001612d40|
/dev/sdb4|ext4|26835071-9953-42bf-b938-50b1c82ff43b|
```
More important, **why do we need this?** 
Is nice code but does it solve a bug, offers a new feature, of is more efficient than an older one? Why should it be *by default* in all puppies?

**Comment by wdlkmpx** [comment]
In full lists it ignores /dev/loops, I can remove that limitation, it's at the end of the script

It's just a tool that can be an alternative to guess_fstype, if you do

blkinfo -type /dev/sda1 , it will print the sda1's filesystem. Besides the other info it provides is really interesting, and can be useful for a script that generates grub4dos/grub2 menus (UUID)

**Comment by mavrothal** [comment]
I understand that with this instead of the specific scripts issuing a command to extract the needed info from blkid, will call blkinfo to extract it from blkid and pass it to the calling script, which is not much of improvement, I think.
If you intend to replace guess_fstype calls with blkinfo calls (which is a good idea since guess_fstype gets dated), I think it worths going to the handful of scripts that use guess_fstype, see what kind of info they need to evaluate (including loop info)  and change them (and blkinfo if needed) accordingly.:wink:
Just need to make sure that will work in all case scenarios
Also keep in mid the guess_fstype is used in the init so blkinfo should be there too.

**Comment by wdlkmpx** [comment]
Well, to avoid any kind of problems and incompatibilities, a static
build of blkid would might solve any issues with filesystems in init I
guess.

This is how I see it:
coreutils
util-linux

Every puppy should try to update those packages as much as possible,
the good news is that all of them compile in older systems.

So having a standard set to work with will make everything easier, and
will atract more developers, just saying

**Comment by mavrothal** [comment]
There is [petbuilds](https://github.com/puppylinux-woof-CE/petbuilds) that can do that. Hopefully puppy will move that way soon. It still needs integration with the rest of the build system, but hopefully interested people will push that way.

**Pull request closed without merging**
