### PR TITLE
Prepare kernel_kit for kernel 6.x

### PR DESCRIPTION
**Pull request by peabee**

### CODE REVIEW

**Review by dimkr — APPROVED** [review]
No objection, but I'd wait until the first 6.x longterm kernel

**Comment by 01micko** [comment]
Me neither but the `https://github.com/sfjro/aufs6-standalone.git` doesn't exist yet.

**Comment by peabee** [comment]
o news
  When linux-v6.0 (not -rcN) is released, current GIT repos (aufs5-linux
  and aufs5-standalone) will be replaced by aufs6-*, and I will stop
  maintaining aufs5.10--aufs5.14 branches.

Aufs5.x-rcN branches in this replease is for linux-v6.0-rc1. No new
features but some behaviours changed in the mainline.
- unlink(2) and rmdir(2) in NFS is broken, and they may result
  NULL-pointer-access.
- access(2) in tmpfs changed its error code.

J. R. Okajima

**Comment by dimkr** [comment]
> they may result NULL-pointer-access.

Good luck to early adopters of 6.0 with aufs, and those using an actively maintained 5.x longterm kernel but stuck with an unmaintained aufs with issues that won't get fixed.

(For me, this is the final nail in aufs' coffin and I don't understand the rush to use the "latest and greatest" aufs.)

**Pull request merged**
