### PR TITLE
Silence makepkgdb.sh errors

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Review by peabee — CHANGES_REQUESTED** [review]
I don't think its just a question of silencing - not sure the new /var/db/xbps/pkgdb-0.38.plist is being generated.....

**Comment by dimkr** [comment]
This PR won't make the problem worse, if it doesn't solve it.

**Comment by peabee** [comment]
Maybe better to keep the errors until the cause can be determined.........

makepkgdb runs ok, if slowly, locally - how to diagnose when it is running on github???

**Comment by dimkr** [comment]
> makepkgdb runs ok, if slowly, locally - how to diagnose when it is running on github???


Run it inside an Ubuntu container or something. I'd add `set -x`, to see which lines produce these errors.

If you choose to debug on GitHub Actions, please do this in a personal fork of woof-CE, because every build eats a portion of allowed build minutes and storage.

**Comment by peabee** [comment]
> Run it inside an Ubuntu container or something.

No idea how to do this :-((

**Comment by dimkr** [comment]
https://podman.io/getting-started/ is a good place to start if you've never used containers before.

**Comment by peabee** [comment]
Have experimented running makepkgdb locally on other upups - fossapup64 and bionicpup64 - and in both cases no errors appear just like with Slackware...... beginning to suspect its some sort of resource limitation on github??

Strangely, the void pkg database seems to be generated ok despite the error indications.

Google shows a few hits for "tail: error writing 'standard output': Broken pipe" but nothing of significance.

**Pull request closed without merging**
