### PR TITLE
Update 2createpackages

### PR DESCRIPTION
**Pull request by ninaholic**
In case you want to rebuild glibc more than once

### CODE REVIEW

**Comment by 01micko** [comment]
Is this still wanted since #873 is closed?

**Comment by ninaholic** [comment]
Yes @01micko , sorry for bad communication. I think @wdlkmpx fixed the problem, but we can reopen https://github.com/puppylinux-woof-CE/woof-CE/issues/873 if we discover a bug with it :laughing:  mv deletes the file after first compile so I think cp makes more sense.

**Comment by 01micko** [comment]
Ok thanks @ninaholic

**Comment by wdlkmpx** [comment]
cp is the command. i thought i had updated the file before pushing

**Pull request merged**
