### PR TITLE
Make 5.10.x kernels very similar to Debian Bullseye kernels

### PR DESCRIPTION
**Pull request by dimkr**
This makes them bigger and increases RAM consumption, but makes Puppy more likely to work where Debian does.

The difference between Debian kernels and these configurations are:
- The kernel is optimized for size, not performance
- File system drivers and block device drivers are built-in
- Support for AppArmor, SELinux, etc' is disabled
- No debugging info, which increases the package size to ~1 GB
- Automatic use of "huge" memory pages is disabled, to reduce RAM usage

TODO:
- [x] Test USB boot
- [x] Test Bluetooth audio
- [x] Make sure the x86 build boots

### CODE REVIEW

**Comment by dimkr** [comment]
Tested the x86_64 kernel, boots nicely (both BIOS and UEFI), Bluetooth audio works.

(`neofetch` definitely gets some things wrong)

screeny

**Comment by dimkr** [comment]
> Many of these MMC modules need to be builtin to boot from mmc card, especially that one for my Dell lappy.

I took the Debian list of drivers, and changed =m to =y wherever possible. Does Debian boot on this laptop? 🤔 

EDIT: it probably does, if the initramfs takes care of loading that module

EDIT: changed to =y

**Comment by dimkr** [comment]
@01micko Objections?

**Comment by 01micko** [comment]
> @01micko Objections?

Nope.

But @gyrog should have a look at the DOTconfig to make sure certain keyboard drivers are builtins.

**Comment by 01micko** [comment]
@gyrog ??

**Comment by dimkr** [comment]
Let's get this one merged, extra keyboard drivers can be added later if needed.

**Pull request merged**
