### PR TITLE
petbuilds: add sfwbar - a task bar and launcher for wayland

### PR DESCRIPTION
**Pull request by 01micko**
Finally doing a PR for sfwbar.

Of course this is experimental and entirely optional. Note that nothing uses this petbuild yet.

Included is a config GUI in `gtkdialog` to customise the launcher and bar settings.

There will be more to come, including but not limited to -
- ptheme support
- labwc 'unstable' petbuild - suitable for slackware-current, debian-sid, perhaps arch and void builds
- slackware-current woof-distro files

sfwbar

### CODE REVIEW

**Comment by dimkr** [comment]
Cool stuff! Let's see if sid can use this so all labwc-specific stuff in the yambar petbuild can be removed.

EDIT: should be much easier to add all the new stuff to sid after 2f234f3

**Comment by dimkr** [comment]
@01micko Why not merge this?

**Comment by 01micko** [comment]
It's fairly outdated now.

**Comment by 01micko** [comment]
I restored the branch. If I get time tomorrow I'll update and force-push.

**Comment by LBCrion** [comment]
@01micko,  I hope to have basic loadable module functionality in sfwbar ready for testing in a few days,  this should make volume control simpler and more stable (pulseaudio module will expose basic pulseaudio functionality via expressions and actions).

**Comment by 01micko** [comment]
@LBCrion the latest version of `sfwbar` works perfectly with my config so I'll update this PR and clean out extra stuff (like the `sfwbsr.svg` icon, which was part of this PR :wink: , and other icons I recently submitted here. )

I'll have a little time later in the week to test out the new modules. Then I can simply update the version and add new configs.

**Comment by 01micko** [comment]
> @01micko Why not merge this?

Some of the other outdated stuff were extra icons that I added which have since been merged in `sfwbar` [4c8537e](https://github.com/LBCrion/sfwbar/commit/4c8537ef2b95059b6e369d6517cc396c3145cb71)  and #3789 plus some `grep` warnings as well as some old config options in `sfwbar`.

**Pull request merged**
