### PR TITLE
Install 32-bit libc before running kernel-kit (#2462)

### PR DESCRIPTION
**Pull request by dimkr**
Still building in ~https://github.com/dimkr/woof-CE/runs/3449293553?check_suite_focus=true~ https://github.com/dimkr/woof-CE/actions/runs/1176727041

### CODE REVIEW

**Comment by 01micko** [comment]
https://github.com/dimkr/woof-CE/runs/3449537160?check_suite_focus=true#step:4:3494

**Comment by dimkr** [comment]
> https://github.com/dimkr/woof-CE/runs/3449537160?check_suite_focus=true#step:4:3494

Nice catch, should be good now -https://github.com/dimkr/woof-CE/actions/runs/1177167106

**Comment by 01micko** [comment]
Seems a similar error building `auibusy`

**Comment by dimkr** [comment]
> auibusy

I don't see errors 🤔 

```
2021-08-28T12:45:51.0387292Z cc -m32 -O -Wall -I /home/runner/work/woof-CE/woof-CE/kernel-kit/output/kernel_headers-5.10.61-kernel-kit-i686/usr/include -D_GNU_SOURCE -I./libau -DAUFHSM_CMD=\"/usr/bin/aufhsm\" -DMOUNT_CMD=\"/bin/mount\" -DUMOUNT_CMD=\"/bin/umount\"  -c -o auibusy.o auibusy.c
2021-08-28T12:45:51.0897894Z cc -m32 -s  auibusy.o  -L. -lautil -o auibusy
```

```
2021-08-28T12:46:34.8768258Z cc -m32 -O -Wall -I /home/runner/work/woof-CE/woof-CE/kernel-kit/output/kernel_headers-4.19.205-kernel-kit-i686/usr/include -D_GNU_SOURCE -I./libau -DAUFHSM_CMD=\"/usr/bin/aufhsm\" -DMOUNT_CMD=\"/bin/mount\" -DUMOUNT_CMD=\"/bin/umount\"  -c -o auibusy.o auibusy.c
2021-08-28T12:46:34.9210387Z cc -m32 -s  auibusy.o  -L. -lautil -o auibusy
```

**Comment by 01micko** [comment]
my bad 

https://github.com/dimkr/woof-CE/runs/3450797479?check_suite_focus=true#step:5:3353

**Pull request merged**
