### PR TITLE
Make the labwc menu button work

### PR DESCRIPTION
**Pull request by dimkr**
altf1

### CODE REVIEW

**Review by 01micko — COMMENTED** [review]
I just compiled and used on Vanilla Dpup unstable and it works but doesn't work in my slack64 install.. so I need to know what I'm missing.

**Comment by 01micko** [comment]
Still not working on slacko - is it `labwc` version specific?

EDIT: built the petbuild version and ran from terminal but still not working

**Comment by dimkr** [comment]
> EDIT: built the petbuild version and ran from terminal but still not working

Did you run `altf1d` and `killall -USR1 altf1d`?

**Comment by 01micko** [comment]
> > EDIT: built the petbuild version and ran from terminal but still not working
> 
> Did you run `altf1d` and `killall -USR1 altf1d`?

That's how I tested in dpup unstable and my current slacko install.

**Review by 01micko — APPROVED** [review]
My bad, forgot that I messed up my rc.xml and forgot to put back A-F1 :man_facepalming:

**Pull request merged**
