### PR TITLE
Change window icon to add path and delete duplicate icon; update pet_specs

### PR DESCRIPTION
**Pull request by rserwin1**
Please ignore all but the last 3 commits, since the others have already been merged. This request is to remove the duplicated frisbee icon and the need for it, reducing size by 20K.
Please do whatever you do to clear the merged commits from my testing branch.

### CODE REVIEW

**Comment by wdlkmpx** [comment]
Hahaha, I told you your testing branch was going to cause you problems, because it has "diverged" due to unmerged commits, and it is commits ahead and behind "upstream" testing.

The first time it happened to me, I had no idea what to do, I found the solution in the cli, first "git log" to see history and look for a commit that was before mine, then I copy the hash in LXTerminal, then I do this "git reset --hard commit-hash", then my local branch is several commits behind but none ahead, then I do "git pull" and everything is ok, now I have to force that into my remote branch with "git push -f remote branch" (these 2 are "origin testing" according to my settings).

Perhaps you should delete your testing branch, and somehow fork it again from woof-CE, try deleting it first, then look for a button or something in the woof-CE testing branch. And never use testing again to create a pull request, just create a temporary branch that gets autodeleted.

I can manually add the last 3 commits if you wish..

I'm looking at the frisbee 1.4 thread... another way to do this can be: for every minor frisbee release, you send a message in the forum or via email with a link to the post, then I will automatically update it in git

**Comment by rserwin1** [comment]
Thanks for the explanation.  Go ahead and merge the three.  Then I will try deleting my testing branch.  But how does one do that?  I will look around, since I have not stumbled upon it, so far.

I hope that I have completed both frisbee and pgprs, so should generate little further activity for those.  I would like to limit my updating to using github.  But I will probably experiment with the local git.  I am considering trying to make an interactive GUI (using Xdialog) for maintaining a local maintenance environment to feed github, so that others could contribute to woofCE without the hassle we went through.  But, do I really want to take on another major project?

**Comment by wdlkmpx** [comment]
I'll resolve the conflicts, merge your pull request and that means something... the 19 commits will appear in the woof-CE testing branch... yes, all of them, but it will solve future issues. This is the first time I'm going to do this, so it may not be as described.

I know that most puppy users, about 99.99% don't have a clear understanding of how git works, but that's why there are active developers. I'm willing to help people and do many things for them, but i don't have communication skills on the forum, in fact i may be a black sheep.

Well, you can do it for yourself, and perhaps other can benefit from it, it takes time before it clicks, like a language.

**Comment by rserwin1** [comment]
Thank you for merging all of the commits and thereby cleaning out my testing branch.  Now I can attempt to sync it with the Woof testing branch, so I can delete my other branches -- and then use only dedicated branches for my fixes..

**Pull request merged**
