### PR TITLE
In PUPMODE=6, let frugalify create /mnt/home

### PR DESCRIPTION
**Pull request by dimkr**
See #2829 and /usr/local/pup_event/drive_all and https://github.com/puppylinux-woof-CE/frugalify/commit/5fe84ba2ac2c466df09956309c7a78d9a42696bd

### CODE REVIEW

**Comment by mavrothal** [comment]
Tried this patch with the latest frugalify #8ee6c57
/dev/sdXN is mounted both in /mnt/sdXN (first) and  also in /initrd and then /mnt/home is linked to /dev/sdXN
This is not going to work with pup_event and friends as they expect `readlink /mnt/home` to point to /initrd/mnt/dev_save and then look what is mounted on /initrd/mnt/dev_save to determine home partition.

**Comment by dimkr** [comment]
There's no initramfs when booting with frugalify - that's the whole idea. frugalify adds /initrd to make some tools that expect something writable at /initrd keep working, but that's as close as it can get. This emulation will never be perfect.

If I understand correctly, these 4 cases should work just fine with /mnt/home that points to /mnt/sda1:

```
$ grep 'readlink /mnt/home' `find -type f` 2>/dev/null
./usr/local/pup_event/drive_all:			[ "`readlink /mnt/home`" = "$MNTPT" ] && MNTPT="/mnt/home"
./usr/sbin/pmount:			HOMELINK="`readlink /mnt/home`"
./usr/sbin/filemnt:HOMELINK="`readlink /mnt/home`"
./usr/sbin/sfsget:	 DLMOUNT1="`readlink /mnt/home`"
```

**Comment by mavrothal** [comment]
Not quite 
> `./usr/local/pup_event/drive_all:			[ "`readlink /mnt/home`" = "$MNTPT" ] && MNTPT="/mnt/home"`
is followed by 
`case $MNTPT in /initrd/pup_*) MNTPT="/"`
similarly in pmount by
`case $ONEMNTPT in /initrd/pup_*) ONEMNTPT="/"`

Unfortunately /initrd/pup_ is hardcoded in those to determine /mnt/home partition

**Comment by dimkr** [comment]
> Unfortunately /initrd/pup_ is hardcoded in those to determine /mnt/home partition

Most references to /initrd/* are guarded by an `if` that checks PUPMODE, or harmless (i.e. there's no mount point that matches the pattern `/initrd/pup_*`, so no special handling is needed).

There some checks that don't work, like this one in pmount:

```
        case $ONEMNTPT in /initrd/*)                  
                INVISBUT='<visible>disabled</visible>
```

The only way to fix this is to add another check: disable the button for /mnt/home if PUPMODE=6. But that's beyond the scope of this PR, which is only meant to make the various `readlink /mnt/home` everywhere work.

**Comment by mavrothal** [comment]
The problem I see is what it shows below

home_partition

f19046b blocked unmounting root partition (could not be unmounted anyway because was busy) but the strange behaviour remains because puppy scripts expect root partition mounted in /initrd/mnt/dev_save.
So either scripts should be changed to correctly identify root partition or frugalify mounting should provide the info they are looking for.

**Comment by dimkr** [comment]
> expect root partition mounted in /initrd/mnt/dev_save.

I don't see a clean way to fix this. frontend_rox_funcs is a total mess.

This PR won't fix the problem you're talking about, it will fix others.

**Comment by mavrothal** [comment]
On a VERY brief tasting these two patches appear to work both in initrd and frugalify pups
With some more testing could be used
```
--- a/usr/local/pup_event/drive_all	2022-01-29 02:38:32.000000000 +0200
+++ b/usr/local/pup_event/drive_all	2022-02-01 17:53:31.131998063 +0200
@@ -16,7 +16,7 @@
 export LANG	# need to restart pmount with correct locale
 export TEXTDOMAIN=drive_all
 export OUTPUT_CHARSET=UTF-8
-
+. /etc/rc.d/PUPSTATE
 [ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505
 
 ONEDRVNAME="$1" # /tmp/pup_event_frontend/drive_<ONEDRVNAME>/AppRun
@@ -163,10 +163,13 @@
 		#mounted...
 		MNTPT="`mount | grep -m1 "^/dev/${ONEDRVNAME} " | cut -f 3 -d ' '`"
 		if [ -h /mnt/home ];then
-			[ "`readlink /mnt/home`" = "$MNTPT" ] && MNTPT="/mnt/home"
+			[ "`readlink /mnt/home`" = "$MNTPT" ] && MNTPT="/mnt/home" 
+			[ $PUPMODE -eq 6 ] && MNTPT="/initrd" 
 		fi
 		#110720 should not open a layer inside aufs, ex: session saved entire partition, desktop drive icon is /initrd/pup_rw...
-		case $MNTPT in /initrd/pup_*) MNTPT="/" ;; esac
+		if [ $PUPMODE -ne 6 ] ; then
+			case $MNTPT in /initrd/pup_*) MNTPT="/" ;; esac
+		fi
 		defaultfilemanager_x $MNTPT &
 		EXITFLAG=yes
 	fi
```

```
--- a/usr/local/pup_event/frontend_rox_funcs	2022-01-29 02:38:32.000000000 +0200
+++ b/usr/local/pup_event/frontend_rox_funcs	2022-02-01 17:57:17.860004936 +0200
@@ -11,6 +11,7 @@
 }
 
 . /etc/rc.d/functions_x #fx_* functions
+. /etc/rc.d/PUPSTATE
 
 #130807 L18L
 export TEXTDOMAIN=pup_event_frontend_d
@@ -95,23 +96,24 @@
 	[ "$2" = "optical" ] && DRVICON="optical_mntd48.png"
 	#MP: support luks-encrypted partitions
 	MOUNTPOINT=$(mount | grep -E "^/dev/${1} |^/dev/mapper/lukspartition_${1} " | cut -f 3 -d ' ')
-	if [ "`echo "$MOUNTPOINT" | grep -v '/initrd/' | grep -v '^/$'`" = "" ] ; then
-		#only partitions mntd on /initrd/* then must be mntd at boot. cannot unmount.
-		#also, full hd install has partition mntd on '/'.
-		DRVICON="drive_mntd_boot48.png" #default.
-		[ "$2" = "usbdrv" ] && DRVICON="usbdrv_mntd_boot48.png"
-		[ "$2" = "card" ] && DRVICON="card_mntd_boot48.png"
-		[ "$2" = "floppy" ] && DRVICON="floppy_mntd_boot48.png"
-		[ "$2" = "optical" ] && DRVICON="optical_mntd_boot48.png"
-	fi
-	if [ "`echo "$MOUNTPOINT" | grep -v '/initrd/mnt/pdrv'`" = "" ] ; then
-		#only partitions mntd on /initrd/* then must be mntd at boot. cannot unmount.
-		#but we override last selection here
-		DRVICON="drive_mntd_nocopy48.png" #default.
-		[ "$2" = "usbdrv" ] && DRVICON="usbdrv_mntd_nocopy48.png"
-		[ "$2" = "card" ] && DRVICON="card_mntd_nocopy48.png"
-		[ "$2" = "floppy" ] && DRVICON="floppy_mntd_nocopy48.png"
-		[ "$2" = "optical" ] && DRVICON="optical_mntd_nocopy48.png"
+	if [ "$PUPMODE" = "6" ]; then
+		if [ "$(echo "$MOUNTPOINT" | grep '/initrd')" != '' ]; then
+			DRVICON="drive_mntd_boot48.png" #default.
+			[ "$2" = "usbdrv" ] && DRVICON="usbdrv_mntd_boot48.png"
+			[ "$2" = "card" ] && DRVICON="card_mntd_boot48.png"
+			[ "$2" = "floppy" ] && DRVICON="floppy_mntd_boot48.png"
+			[ "$2" = "optical" ] && DRVICON="optical_mntd_boot48.png"		
+		fi
+	else
+		if [ "$(echo "$MOUNTPOINT" | grep -v '/initrd/' | grep -v '^/$')" = "" ] ; then
+			#only partitions mntd on /initrd/* then must be mntd at boot. cannot unmount.
+			#also, full hd install has partition mntd on '/'.
+			DRVICON="drive_mntd_boot48.png" #default.
+			[ "$2" = "usbdrv" ] && DRVICON="usbdrv_mntd_boot48.png"
+			[ "$2" = "card" ] && DRVICON="card_mntd_boot48.png"
+			[ "$2" = "floppy" ] && DRVICON="floppy_mntd_boot48.png"
+			[ "$2" = "optical" ] && DRVICON="optical_mntd_boot48.png"
+		fi
 	fi
 	mounted_Icon_Path="/usr/local/lib/X11/pixmaps/${DRVICON}"
 	# custom icon? .DirIcon
```

**Comment by dimkr** [comment]
> On a VERY brief tasting these two patches appear to work both in initrd and frugalify pups With some more testing could be used

https://github.com/puppylinux-woof-CE/woof-CE/pull/2833

**Comment by dimkr** [comment]
Merging this one, it has zero side-effects and it's required to test #2833 properly

**Pull request merged**
