### PR TITLE
SusePup64

### PR DESCRIPTION
**Pull request by IdfbAn**
Built from openSUSE Tumbleweed.

Currently, SusePup64 fails very early into the build process, which is why this is a _draft_ pull request. Any help is appreciated.

### CODE REVIEW

**Comment by peabee** [comment]
Hi @IdfbAn 
Interesting initiative ..... does OpenSuse bring anything new or interesting that is not already possible with Debian/ Devuan/ Ubuntu/ Slackware/ Void?
Is OpenSuse a rolling release or a periodic release system? The latter are a better fit with Woof-CE.
What format is INDEX.gz? Can 0setup convert it into the internal Woof-CE format? If not that is the first issue you need to tackle.
You should "perfect" your build in your fork and only then issue a PR to bring the info from your fork into the mainstream Woof-CE.

**Comment by IdfbAn** [comment]
>  ..... does OpenSuse bring anything new or interesting that is not already possible with Debian/ Devuan/ Ubuntu/ Slackware/ Void?

Maybe RPM, but to be honest this is more of a "why not?" thing than anything.

> Is OpenSuse a rolling release or a periodic release system?

openSUSE has two main versions, Leap and Tumbleweed. The one SusePup64 is built from, Tumbleweed, is rolling release.

> What format is INDEX.gz?

It's basically just a list of the files in its directory, here's a small snippet of it:
```
./boot/x86_64/yast2-trans-en_GB.rpm
./boot/x86_64/root
./boot/x86_64/control.xml
./boot/x86_64/yast2-trans-sk.rpm
./boot/x86_64/yast2-trans-si.rpm
./boot/x86_64/yast2-trans-hi.rpm
./boot/x86_64/yast2-trans-es.rpm
./boot/x86_64/yast2-trans-jv.rpm
./boot/x86_64/yast2-trans-gl.rpm
./boot/x86_64/yast2-trans-hu.rpm
./boot/x86_64/bind
./boot/x86_64/yast2-trans-th.rpm
./boot/x86_64/yast2-trans-nn.rpm
./boot/x86_64/yast2-trans-uk.rpm
./boot/x86_64/yast2-trans-zu.rpm
./boot/x86_64/yast2-trans-mk.rpm
./boot/x86_64/libyui-rest-api
./boot/x86_64/yast2-trans-ca.rpm
./boot/x86_64/config
./boot/x86_64/yast2-trans-wa.rpm
./boot/x86_64/yast2-trans-sw.rpm
./boot/x86_64/arphic-uming-fonts.rpm
```

> Can 0setup convert it into the internal Woof-CE format? If not that is the first issue you need to tackle.

I don't think it can right now, which I'm pretty sure is the reason it's failing at that point.

> You should "perfect" your build in your fork and only then issue a PR to bring the info from your fork into the mainstream Woof-CE.

I know this isn't "perfect" yet. That's why this is a draft PR instead of a regular one.

**Comment by peabee** [comment]
That doesn't look like sufficient information......
You will need to add code for OpenSuse to 0setup - line 264 is the case statement for the different donor systems

**Comment by peabee** [comment]
and then in 2createpackages section start 275 you will have to be able to unpack .rpm

**Comment by peabee** [comment]
You may (??) find some inspiration in "legacy branch".......
https://github.com/puppylinux-woof-CE/woof-CE/blob/legacy/woof-code/0setup
https://github.com/puppylinux-woof-CE/woof-CE/blob/legacy/woof-code/2createpackages

**Comment by rizalmart** [comment]
I looking forward for this. However suse use systemd. I think the puppy core init and shutdown scripts must be init agnostic (can support different init systems). I tried to make a pull request on it, but everyone here got panicked.

**Comment by IdfbAn** [comment]
Why? It still doesn't build successfully.

**Pull request merged**
