### PR TITLE
fix gparted icon on first screen #1481

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by 01micko** [comment]
Probably not the right way to go about this. Sure, fixes it for slacko based on 14.0 but what about your dpup spin mentioned in #1481 ?
I'll await further review / ideas before merging, but I think a dedicated icon in pixmaps/puppy might be a better option.

**Comment by ghost** [comment]
Hi 01micko!

You're right, I checked in the dpup build and it also has the missing icon, and the ln -s line fixed it there too. Maybe a fallback in package-templates for "if no /usr/share/pixmaps/gparted.png exists but /usr/share/icons/hicolor/32x32/apps/gparted.png does, create a symlink" would work, and/or an edit to the petbuild, and/or a dedicated icon for it in rootfs-skeleton or the theme like you said.

Screenshot

edit: I guess the package-templates idea wouldn't work for 14.0 because in this one it actually seems to be a pet, in dpup stretch it comes from a deb from the dpup repository though.

**Comment by ghost** [comment]
Here's the original icon for both though if anyone wants it :woman_artist: 

gparted

**Comment by 01micko** [comment]
I'm pretty sure we could make a nice icon that fits the pixmap/puppy design but that may not be the solution. Is the dpup version a pet or deb?  Maybe more options are needed in `gparted_shell`

relevant snippet, with a bug.. and maybe the problem?

```shell
[ -f /usr/share/pixmaps/gparted.xpm ] & gpicon=/usr/share/pixmaps/gparted.xpm
[ -f /usr/share/pixmaps/gparted.png ] & gpicon=/usr/share/pixmaps/gparted.png
[ -z $gpicon ] && gpicon=/usr/share/pixmaps/puppy/harddisk_scsi.svg
```

Unquoted variable in test is the bug. Result will be undefined.

**Comment by ghost** [comment]
Interesting! I did not realize it was script (I thought icon was hardcoded in binary). :laughing:

I tried changing & to && and changing -z to ! and it seems to work now for both cases?

```
[ -f /usr/share/pixmaps/gparted.xpm ] && gpicon=/usr/share/pixmaps/gparted.xpm
[ -f /usr/share/pixmaps/gparted.png ] && gpicon=/usr/share/pixmaps/gparted.png
[ ! $gpicon ] && gpicon=/usr/share/pixmaps/puppy/harddisk_scsi.svg
```

**Comment by ghost** [comment]
Basically, with this new code, it picks gparted.png if you have it, if not it falls back to gparted.xpm, and if both don't exist it falls back to harddisk_scsi.svg. I've tested all combinations I could think of and it worked as expected. With the old code, dpup had both gparted.xpm and harddisk_scsi.svg and it didn't pick any of them. I think this is good enough to merge, but feel free to review and test if you like ;)

**Comment by 01micko** [comment]
Looks ok to me :+1:

**Pull request merged**
