### PR TITLE
Replace {f,e}grep with grep -{F,E}

### PR DESCRIPTION
**Pull request by dimkr**
https://www.phoronix.com/news/GNU-Grep-3.8-Stop-egrep-fgrep

### CODE REVIEW

**Review by 01micko — APPROVED** [review]

**Comment by 01micko** [comment]
Funny, I started coding in shell around 2007 and never used egrep/fgrep simply because I knew about -E/-F

**Comment by dimkr** [comment]
> Funny, I started coding in shell around 2007 and never used egrep/fgrep simply because I knew about -E/-F

I started around that time too, and I'm using fgrep for 2-3 years I think 😊

**Comment by peabee** [comment]
FYI - Slackware "comment":
a/grep-3.8-i586-2.txz:  Rebuilt.
  Folks, I rarely veto upstream, but I'm not going to entertain this nonsense.
  The egrep and fgrep commands were part of Unix since the 70s, continue to be
  included with the BSDs, and frankly, aren't hurting anything. GNU grep
  declared them deprecated in 2007 and when they were changed into shell
  scripts around 8 years ago I figured that's where it would end. I can see no
  logical justification to have these scripts start making noise and then to
  eventually pull the rug out from under any code that might be using them, so
  I've placed non-noisy versions of them into the package sources and will be
  installing those during the build. Given that the -F and -E options are part
  of the POSIX standard, these scripts will continue to work fine. That said,
  we will be continuing to change our own code over to the recommended syntax
  to avoid the minimal overhead incurred compared to using grep directly.

**Comment by 01micko** [comment]
@peabee I agree with PV's sentiment but woof supports more than Slackware.

**Pull request merged**
