### PR TITLE
Move icon packages to petbuilds and add them to all builds

### PR DESCRIPTION
**Pull request by dimkr**
@01micko: I cleaned up the petbuilds (simplified download() a bit + ignored file modification timestamps on GitHub Actions), and enabled the 3 petbuilds in all build configurations.

Let's delete the icon packages under rootfs-packages in a separate PR, so we can review the changes properly.

### CODE REVIEW

**Review by peabee — CHANGES_REQUESTED** [review]
Seems OK as long as petbuilds can be made to work for all build combinations of host and target....
However - think it would be much better and cleaner and clearer if all definition of components included in a build could be found in one place - preferably DISTRO_PKGS_SPECS-*
i.e both this new _00build.conf content and also /support/rootfs-packages.conf should be moved to DISTRO_PKGS_SPECS-*
and
it might be useful to have a "do not include" syntax as well as an "include" syntax?

**Comment by 01micko** [comment]
> Seems OK as long as petbuilds can be made to work for all build combinations of host and target....
> However - think it would be much better and cleaner and clearer if all definition of components included in a build could be found in one place - preferably DISTRO_PKGS_SPECS-*
> i.e both this new _00build.conf content and also /support/rootfs-packages.conf should be moved to DISTRO_PKGS_SPECS-*
> and
> it might be useful to have a "do not include" syntax as well as an "include" syntax?

I would say that there are 2 separate entities here - downloaded packages and woof packages, so lumping them all in one configuration file presents certain difficulties from a coding complexity perspective, however one place where there should be consistencyis in the way we handle `rootfs-*` type packages.

Using an array makes things simple from a coding perspective. So it makes sense to use them in configs for rootfs  stuff. Perhaps, we can ditch the `_00build_2.conf` and use 'includes' in the `_00build.conf`, such as 'rootfs-petbuilds.conf' and 'rootfs-packages.conf'. That shouldn't be too difficult at all using the CLI, but what about the GUI?

Sidenote: IMHO, if one must use a GUI to build a distro, one has no business building a distro!

**Comment by dimkr** [comment]
> Seems OK as long as petbuilds can be made to work for all build combinations of host and target....

It's already implemented. Builds are done in a chroot when building for the same architecture, or when it's x86_64 to x86. In all other combinations, they are compiled without cross-compilation, using qemu-user-static emulation.

> However - think it would be much better and cleaner and clearer if all definition of components included in a build could be found in one place - preferably DISTRO_PKGS_SPECS-*

Do you have a proposal how to do this? We can't use the packages table for this, because petbuilds can happen only later in the build, when we have rootfs-complete and devx, and it's ugly to patch 1download, 2createpackages, etc' to skip the petbuild packages. On the other hand, moving PETBUILDS= to a different file doesn't make this solution elegant or easier to use, in my mind.

> it might be useful to have a "do not include" syntax as well as an "include" syntax?

I think there's no need for that. If no petbuilds are auto-selected and the petbuild selection is chosen explicitly, there's no need to exclude petbuilds.

**Comment by peabee** [comment]
> > Seems OK as long as petbuilds can be made to work for all build combinations of host and target....
> 
> It's already implemented. Builds are done in a chroot when building for the same architecture, 

Checked 32-bit build (slacko32-8.2.2) on 32-bit host (slacko32-8.2.2-54 with devx-8.2.2-54) and it fails............
[060821-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6944548/060821-false.gz)

**Comment by dimkr** [comment]
> Checked 32-bit build (slacko32-8.2.2) on 32-bit host (slacko32-8.2.2-54 with devx-8.2.2-54) and it fails............

I think you should try some stable Puppy on the host, and try the stock kernel if you're using some custom kernel. Something about your setup is weird, if the same woof-output directory worked on my machine.

**Comment by peabee** [comment]
slacko32-8.2.2-54 does have a 5.4 "stock kernel" doesn't it?

Happy to try a different 32-bit host - @01micko did not like me using ScPup32 - which 32-bit "stable Puppy" do you suggest to build a slacko system???

Were you using a 64-bit or 32-bit host? A 64-bit host does build OK. A 32-bit does not.

**Comment by dimkr** [comment]
> slacko32-8.2.2-54 does have a 5.4 "stock kernel" doesn't it?

Is the kernel configuration identical to kernel-kit/configs_x86/DOTconfig-5.4.129-i686-pae?

**Comment by peabee** [comment]
Not 100%:

```
# diff DOTconfig-5.4.129-i686-pae.txt DOTconfig-5.4.137-020821 
3c3
< # Linux/x86 5.4.129 Kernel Configuration
---
> # Linux/x86 5.4.0 Kernel Configuration
7c7
< # Compiler: gcc (GCC) 10.3.0
---
> # Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
10c10
< CONFIG_GCC_VERSION=100300
---
> CONFIG_GCC_VERSION=90300
783c783
< CONFIG_PLUGIN_HOSTCC="g++"
---
> CONFIG_PLUGIN_HOSTCC=""
785d784
< # CONFIG_GCC_PLUGINS is not set
4118a4118
> # CONFIG_BATTERY_RT5033 is not set

```

**Comment by peabee** [comment]
@dimkr @01micko 
Could it be that aufs-util are being built for 64-bit in 32-bit kernels???
This is probably because kernel-kit is being run on a 64-bit host?
```
# pwd
zdrv_slacko_8.2.2-54.sfs/sbin
# file mount.aufs 
mount.aufs: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=09c345ecc83a0fdafd5516ccb3fecc3712a51eb5, stripped
```

**Comment by peabee** [comment]
Well it's definitely part of the problem but not the whole answer..........
Using the ScPup32 kernel (which does have 32-bit aufs-utils) in slacko32-8.22.-54 gets further in that a complete chroot is constructed

see below

**Comment by dimkr** [comment]
@peabee I think you want to remove that `/`, the directory is inside sandbox3, your working directory, not at / (`ls petbuild-rootfs-complete-busybox`).

**Comment by peabee** [comment]
Sorry - ls problem was red herring.....

With slacko32-8.2.2.-54 + ScPup32 5.4.109 kernel (with 32-bit aufs-utils) + devx-8.2.2-54
petbuilds build OK
but 3builddistro does not complete fully giving error at "Please wait while microcode is downloaded and built":

```
Now building initial ramdisk...
+ cp rootfs-complete/etc/DISTRO_SPECS ../initrd-progs/DISTRO_SPECS
+ rm -f 'build/initrd.[gx]z' '../initrd-progs/initrd.[gx]z'
+ cd ../initrd-progs/
+ ./build.sh -prebuilt -auto -arch x86
* Extracting initrd_progs-20210401-static.tar.xz...


***        INITRD: initrd.gz [i686]
*** /DISTRO_SPECS: Slacko Puppy 8.2.2 x86
+ mv -fv ../initrd-progs/initrd.gz build/
renamed '../initrd-progs/initrd.gz' -> 'build/initrd.gz'
+ case $WOOF_TARGETARCH in
+ cp -fv ../initrd-progs/0initrd/README.txt build/
'../initrd-progs/0initrd/README.txt' -> 'build/README.txt'
+ case $WOOF_TARGETARCH in
+ '[' -n ../support/latest_microcode.sh ']'
+ ../support/latest_microcode.sh
Please wait while microcode is downloaded and built
tar: Old option 'f' requires an argument.
Try 'tar --help' or 'tar --usage' for more information.
+ exit 1

```

**Comment by dimkr** [comment]
This can happen if `curl` failed - try again maybe? Check your internet connection?

**Comment by dimkr** [comment]
Double-checked and everything works fine here, even without mount.aufs present. I don't think the 64-bit executable is a problem, but I opened #2437.

EDIT: try the latest build, it should have a 32-bit mount.aufs

**Comment by peabee** [comment]
Using slacko-8.2.2-55.iso & devx_slacko_8.2.2-55.sfs
BUILD_FROM_WOOF='testing;e86ff11e0;2021-08-08 07:33:47 +0100'

zdrv_slacko_8.2.2-55.sfs does not have any aufs-util

however - petbuilds complete ok - hoorah!

but microcode error is permanent and aborts build 
so microcode removed from 00build.conf
and build then completes (but .iso does not include fdrv)

```
Now building initial ramdisk...
* Extracting initrd_progs-20210401-static.tar.xz...


***        INITRD: initrd.gz [i686]
*** /DISTRO_SPECS: Slacko Puppy 8.2.2 x86
renamed '../initrd-progs/initrd.gz' -> 'build/initrd.gz'
'../initrd-progs/0initrd/README.txt' -> 'build/README.txt'
Please wait while microcode is downloaded and built
tar: Old option 'f' requires an argument.
Try 'tar --help' or 'tar --usage' for more information.

```

**Review by 01micko — APPROVED** [review]

**Comment by 01micko** [comment]
@peabee , getting back to the original PR.. are your objections satisfied or do you still want changes?

**Comment by peabee** [comment]
I can live with the consequences.

**Comment by 01micko** [comment]
I fixed conflicts with `testing` and merged so this PR is now ready to merge @dimkr

**Comment by dimkr** [comment]
> I fixed conflicts with `testing` and merged so this PR is now ready to merge @dimkr

@01micko I'm waiting for your and/or @peabee's to approve and merge. Then, I'll open a separate PR where I only delete the icons from rootfs-packages.

**Comment by 01micko** [comment]
> @01micko I'm waiting for your and/or @peabee's to approve and merge. Then, I'll open a separate PR where I only delete the icons from rootfs-packages.

https://github.com/puppylinux-woof-CE/woof-CE/pull/2432#issuecomment-904552811

@peabee can live with it.

I approved above so I'll merge then.

**Comment by dimkr** [comment]
Triggered https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/1176761763. I'll make sure Slacko 7.x, bionic and focal64 are not broken.

**Pull request merged**
