### PR TITLE
xterm: user bash specific syntax

### PR DESCRIPTION
**Pull request by wdlkmpx**
This speeds up xterm by replacing external programs with bash builtin functions.

I know I've been playing in git with this script, but I needed to make sure this is ok,
but now I can attest that this works the same as before

### CODE REVIEW

**Comment by mavrothal** [comment]
I have no problem with the change, I just wonder what problem does it solve? What is the speed impact? Could you give an example of the effect before and after?

**Comment by wdlkmpx** [comment]
Actually it could even be slower hahaha. I guess it just qualifies as a coding style change

But something like this edited new2dir is like 15-20 times faster
http://pastebin.com/dZiWkDc5

**Comment by mavrothal** [comment]
Interesting. Do you have any numbers?
I tried to run it on a dir (as it says it can do) and it totally failed.

**Comment by mavrothal** [comment]
Also tried it after a compile. Looks OK but if you call dir2pet at the end it quits after the first pet regardless if you split the files in doc, dev, exe etc.

**Comment by wdlkmpx** [comment]
It's not finished, but you can defintely compile with it. I lost interest some months ago. Just try something like 

./configure
make
new2dir release

I have 2 companion scripts
- compile
- configure

With these 3 I usually only give one URL or local file to 'compile' and it does the rest

**Comment by wdlkmpx** [comment]
You have to compile something that installs hundreds or thousands of files, there you can compare how fast ca be, in my experience with this almost PentiumIII, the difference is insane

**Comment by 01micko** [comment]
Regarding `new2dir` .. mabe you should apply the magic to [petbuilds}(https://github.com/puppylinux-woof-CE/petbuilds)

Also, installwatch is unmaintained and only a matter of time before it dies from bitrot. `find` can do a more than adequate job. Plus nearly all souces support  `DESTDIR` so perhaps testing the Makefile(s) for this is a good idea and will speed stuff up considerably.

**Comment by wdlkmpx** [comment]
I always use tar, I forgot to test the final part properly

UHmm micko I have my own "build system", take a look
http://pastebin.com/KMBFbLs2

It can be updated and fixed, you think it can go there?

**Comment by 01micko** [comment]
>UHmm micko I have my own "build system", take a look
http://pastebin.com/KMBFbLs2

Looks nice. I might cherry pick some ideas if you don't mind.

**Comment by wdlkmpx** [comment]
There other scripts you might find useful:

'configure'
http://pastebin.com/ezBPfzpk

'whichgcc'
http://pastebin.com/dGFDtcst

qt4 (qt4 environment (/opt/4.8))
http://pastebin.com/74csS0gr
(this is to compile and run qt4 apps, you con adapt it to compile qt5 apps)


This is an example of pkgs.sh , the generic script used by 'compile', located in $PROJECT_DIR 
http://pastebin.com/1qBtQ3am

**Pull request closed without merging**
