### PR TITLE
minor path fix

### PR DESCRIPTION
**Pull request by ghost**
whoops, forgot to change this part for when building

### CODE REVIEW

**Comment by ghost** [comment]
Re-open if you want

**Comment by wdlkmpx** [comment]
ln -s usr/share/icons/hicolor/32x32/apps/gparted.png usr/share/pixmaps/gparted.png

It's ln -s /usr/...32x32/apps/gparted.png usr/share/..png .. symlink with absolute path

**Comment by ghost** [comment]
Thanks wdlkmpx. Now I think I know why I chose relative path for the 7z one instead :laughing: (which doesn't seem to be needed any more).

**Comment by ghost** [comment]
I also saw a warning in 3builddistro-Z about "--update.cache.so" not found after I believe it was trying to do something with the gtk themes. Do you know what might be causing that, or where I can find the missing file? I'll post a screenshot of the warning next time I try it if you want.

edit: It *might* come from this, that doesn't seem to like parameters added
Screenshot

**Pull request merged**
