### PR TITLE
Update pipewire_FIXUPHACK: Added bluez workaround

### PR DESCRIPTION
**Pull request by rizalmart**
Added bluez workaround

See [https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3828](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3828)

### CODE REVIEW

**Comment by peabee** [comment]
@dimkr - any comments?

**Comment by dimkr** [comment]
@peabee Frankly - I don't see the need for this, because Bluetooth audio works great on dpup without this

**Comment by peabee** [comment]
@rizalmart 
Is this fix specific to your builds?
If so it should be fixed by a build specific mechanism rather than being applied to all builds at the Woof-CE level.
Please let us know why you need it and why you think it needs to be a Woof-CE level fix. Thanks.

**Comment by lakshayrohila** [comment]
Whenever I try to connect to my Bluetooth dev in Jammy64, I get the `br-connection-timeout` error. I'll see if this fixes it for me and report.

**Comment by rizalmart** [comment]
> @rizalmart Is this fix specific to your builds? If so it should be fixed by a build specific mechanism rather than being applied to all builds at the Woof-CE level. Please let us know why you need it and why you think it needs to be a Woof-CE level fix. Thanks.

Because wireplumber-0.5 onwards now looks for active login session in order to make bluez work on pipewire otherwise bluetooth device will not work on pipewire

See [https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3828](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3828)

**Comment by rizalmart** [comment]
> @peabee Frankly - I don't see the need for this, because Bluetooth audio works great on dpup without this

Because you are using lower version of wireplumber.

**Comment by peabee** [comment]
This should be a change to wireplumber_FIXUPHACK ? rather than pipewire_FIXUPHACK

**Pull request closed without merging**
