### PR TITLE
add initrd-progs

### PR DESCRIPTION
**Pull request by wdlkmpx**
- merge the work done in the initrd_progs repo
- edited merge2out and 3builddistro-Z (minimal edits) so that initrd-progs is copied to woof-out* and used.
- deleted directories with static binaries used in the initrd
- woof-code/boot/initrd-tree0 is now initrd-progs/0initrd

### CODE REVIEW

**Comment by wdlkmpx** [comment]
it was easier and less traumatic than i thought and it just looks right, it's time to build a puppy to see if it reaches the final stage

**Comment by ninaholic** [comment]
I think a test build checking everything is good idea too.  I tried symlinking find to busybox find and now it does not show pfind results correctly :bomb:

**Comment by wdlkmpx** [comment]
Yes I'm going to test this, but right now I'm dealing with the build scripts, the heaviest seems to be 2createpackages. I'm trying to speed up things since I'm actually building in a pentium4 2.66ghz with a 20gb HD hahaha. I'm not sure, i think I'll merge this anyways but undoing the last 5 commits of this pull. 

The busybox find is still behind the full version, however it seems to work ok for the initrd, it has all the switches used there, but that does not apply to a full distro where more. Although it hasn't been tested that much, we'll find out for sure soon.

**Comment by ninaholic** [comment]
Your build machine is about the same speed and age as mine hahah :smile: * high five *

Wikipedia thinks it would be a close race anyway:
> Pentium M runs at a lower clock speed than the laptop version of the Pentium 4 (The Pentium 4-Mobile, or P4-M), but with similar performance - a 1.6 GHz Pentium M can typically attain or even surpass the performance of a 2.4 GHz Pentium 4-M

2createpackages is the killer! I try to keep backup of folder then shoehorn in newer stuff only lol

**Comment by wdlkmpx** [comment]
It actually can be at least 20 times faster. All the scripts used to be slow as hell, iguleder sped up some stuff to the max.

For example, this code is 30+ times faster https://github.com/puppylinux-woof-CE/woof-CE/commit/435ed20ba3c71a9aa8c62d0b2643da7db0028ef8 . And the whole thing needs a redesign, it takes time to underand thousand of lines. Other things to are remove some hacks fix the packages/files instead, there's a lot of things to be do, it's not possible to achieve half of that, but going on a deleting rampage can help a bit..

**Comment by wdlkmpx** [comment]
In a few days you might want to build again and see some improvements and report bugs of course...  that is in "rationalise".

**Comment by wdlkmpx** [comment]
I undid the offending commits and I'm merging this, i'll spend some time editing the build scripts and deleting stuff before i can build a puppy and test initrd-progs within woof

**Pull request merged**
