### PR TITLE
Allow the user to disable the firewall now and on boot (fixes #2883)

### LINKED ISSUE #2883: firewall_ng starts the firewall when asked to stop it

### PR DESCRIPTION
**Pull request by dimkr**
I did my best to minimize changes to firewall_ng. It's messy and in bad shape.

EDIT: after looking the code again, I'm not sure I understand this UI. What does the "Your firewall is configured" checkbox do? If it's disabled, is it supposed to setup a firewall that blocks everything except the selected ports? That's not what it does.

### CODE REVIEW

**Comment by 01micko** [comment]
> EDIT: after looking the code again, I'm not sure I understand this UI. What does the "Your firewall is configured" checkbox do? If it's disabled, is it supposed to setup a firewall that blocks everything except the selected ports?

It only appears after you have configured the firewall so you can add extra ports or change stuff with extra ports. I'm not using the very latest that you committed to but that's what it does and it works.

**Review by 01micko — APPROVED** [review]

**Comment by 01micko** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/blob/80f2b4489295179847cb4fb270f463a9f2cba242/woof-code/rootfs-packages/firewall_ng/usr/sbin/firewall_ng#L1358

While on this file can you change this line to use `xterm` or you want me to issue a separate PR?

**Comment by dimkr** [comment]
> > 
> 
> It only appears after you have configured the firewall so you can add extra ports or change stuff with extra ports. I'm not using the very latest that you committed to but that's what it does and it works.

If the checkbox must be ticked to customize the port selection, how do you disable the firewall? Only using the tray icon?

**Comment by dimkr** [comment]
> While on this file can you change this line to use `xterm` or you want me to issue a separate PR?

I can do it.

**Comment by 01micko** [comment]
> > > 
> > 
> > 
> > It only appears after you have configured the firewall so you can add extra ports or change stuff with extra ports. I'm not using the very latest that you committed to but that's what it does and it works.
> 
> If the checkbox must be ticked to customize the port selection, how do you disable the firewall? Only using the tray icon?

Good point. They were developed in tandem a while ago so no consideration was given to wayland support. That checkbox can be deleted.

**Comment by dimkr** [comment]
Closing this one, firewall_ng needs more UX work. It's misleading and unclear.

**Pull request closed without merging**
