### PR TITLE
tahrpup64 build recipe

### PR DESCRIPTION
**Pull request by mrfricks**
here's the build recipe so far for tahrpup64
note that merge2out & 0setup need editing for it to work.... see #570

### CODE REVIEW

**Comment by 01micko** [comment]
Ok.. 3rd time lucky?

**Comment by mrfricks** [comment]
he he ....  hopefully!!

**Comment by 01micko** [comment]
Oh I see it was 4th!

**Comment by mrfricks** [comment]
grrrr ...it's still not bloody right  but will do for now.

**Comment by 01micko** [comment]
Just fix and do another pull request.

**Pull request merged**
