### PR TITLE
Add support for Ubuntu -updates and -security repos

### PR DESCRIPTION
**Pull request by dimkr**
@lakshayrohila This will make apt work more reliably

### CODE REVIEW

**Review by lakshayrohila — COMMENTED** [review]
Thanks a lot for this! If you want someone to review this for bugs, you'll have to get it reviewed by someone else (I am, currently, **not very good** at coding). Can you please build a jammy64 with this and tell if https://github.com/puppylinux-woof-CE/woof-CE/issues/3699 is fixed by this PR?

**Comment by dimkr** [comment]
> Can you please build a jammy64 with this and tell if https://github.com/puppylinux-woof-CE/woof-CE/issues/3699 is fixed by this PR?

This is irrelevant, it won't fix that issue.

**Comment by lakshayrohila** [comment]
> > Can you please build a jammy64 with this and tell if #3699 is fixed by this PR?
> 
> This is irrelevant, it won't fix that issue.

Thanks! At least, the PR will make apt work more reliably... is a great thing. :+1:

**Comment by dimkr** [comment]
Whooho, seems to work great. Now Ubuntu 22.04 updates are picked up by woof-CE correctly:

```
-:alsa-lib:|alsa-ucm-conf_1.2.6.3|alsa-ucm-conf_1.2.6.3-1ubuntu1_all.deb
+:alsa-lib:|alsa-ucm-conf_1.2.6.3|alsa-ucm-conf_1.2.6.3-1ubuntu1.1_all.deb
-:cmake:|cmake-curses-gui_3.22.1|cmake-curses-gui_3.22.1-1ubuntu1_amd64.deb
-:cmake:|cmake-data_3.22.1|cmake-data_3.22.1-1ubuntu1_all.deb
-:cmake:|cmake_3.22.1|cmake_3.22.1-1ubuntu1_amd64.deb
-:e2fsprogs:|comerr-dev_2.1-1.46.5|comerr-dev_2.1-1.46.5-2ubuntu1_amd64.deb
+:cmake:|cmake-curses-gui_3.22.1|cmake-curses-gui_3.22.1-1ubuntu1.22.04.1_amd64.deb
+:cmake:|cmake-data_3.22.1|cmake-data_3.22.1-1ubuntu1.22.04.1_all.deb
+:cmake:|cmake_3.22.1|cmake_3.22.1-1ubuntu1.22.04.1_amd64.deb
+:e2fsprogs:|comerr-dev_2.1-1.46.5|comerr-dev_2.1-1.46.5-2ubuntu1.1_amd64.deb
-:curl:|curl_7.81.0-1|curl_7.81.0-1_amd64.deb
+:curl:|curl_7.81.0|curl_7.81.0-1ubuntu1.6_amd64.deb
-:dbus-user-session:|dbus-user-session_1.12.20|dbus-user-session_1.12.20-2ubuntu4_amd64.deb
-:dbus:|dbus-x11_1.12.20|dbus-x11_1.12.20-2ubuntu4_amd64.deb
-:dbus:|dbus_1.12.20|dbus_1.12.20-2ubuntu4_amd64.deb
+:dbus-user-session:|dbus-user-session_1.12.20|dbus-user-session_1.12.20-2ubuntu4.1_amd64.deb
+:dbus:|dbus-x11_1.12.20|dbus-x11_1.12.20-2ubuntu4.1_amd64.deb
+:dbus:|dbus_1.12.20|dbus_1.12.20-2ubuntu4.1_amd64.deb
-:dmidecode:|dmidecode_3.3-3|dmidecode_3.3-3_amd64.deb
+:dmidecode:|dmidecode_3.3|dmidecode_3.3-3ubuntu0.1_amd64.deb
-:e2fsprogs:|e2fsprogs_1.46.5|e2fsprogs_1.46.5-2ubuntu1_amd64.deb
+:e2fsprogs:|e2fsprogs_1.46.5|e2fsprogs_1.46.5-2ubuntu1.1_amd64.deb
-:ghostscript:|ghostscript-x_9.55.0|ghostscript-x_9.55.0~dfsg1-0ubuntu5_amd64.deb
-:ghostscript:|ghostscript_9.55.0|ghostscript_9.55.0~dfsg1-0ubuntu5_amd64.deb
+:ghostscript:|ghostscript-x_9.55.0|ghostscript-x_9.55.0~dfsg1-0ubuntu5.1_amd64.deb
+:ghostscript:|ghostscript_9.55.0|ghostscript_9.55.0~dfsg1-0ubuntu5.1_amd64.deb
-:blueman:|gir1.2-gdkpixbuf-2.0_2.42.8+dfsg-1|gir1.2-gdkpixbuf-2.0_2.42.8+dfsg-1_amd64.deb
+:blueman:|gir1.2-gdkpixbuf-2.0_2.42.8+dfsg|gir1.2-gdkpixbuf-2.0_2.42.8+dfsg-1ubuntu0.2_amd64.deb
-:harfbuzz:|gir1.2-harfbuzz-0.0_2.7.4|gir1.2-harfbuzz-0.0_2.7.4-1ubuntu3_amd64.deb
+:harfbuzz:|gir1.2-harfbuzz-0.0_2.7.4|gir1.2-harfbuzz-0.0_2.7.4-1ubuntu3.1_amd64.deb
-:git:|git-man_2.34.1|git-man_2.34.1-1ubuntu1_all.deb
-:git:|git_2.34.1|git_2.34.1-1ubuntu1_amd64.deb
+:git:|git-man_2.34.1|git-man_2.34.1-1ubuntu1.5_all.deb
+:git:|git_2.34.1|git_2.34.1-1ubuntu1.5_amd64.deb
-:shim-signed:|grub-efi-amd64-bin_2.06|grub-efi-amd64-bin_2.06-2ubuntu7_amd64.deb
+:shim-signed:|grub-efi-amd64-bin_2.06|grub-efi-amd64-bin_2.06-2ubuntu10_amd64.deb
-:shim-signed:|grub-efi-amd64_2.06|grub-efi-amd64_2.06-2ubuntu7_amd64.deb
+:shim-signed:|grub-efi-amd64_2.06|grub-efi-amd64_2.06-2ubuntu10_amd64.deb
-:dbus:|libapparmor1_3.0.4|libapparmor1_3.0.4-2ubuntu2_amd64.deb
+:dbus:|libapparmor1_3.0.4|libapparmor1_3.0.4-2ubuntu2.1_amd64.deb
-:dwarves:|libbpf0_0.5.0-1|libbpf0_0.5.0-1_amd64.deb
+:dwarves:|libbpf0_0.5.0|libbpf0_0.5.0-1ubuntu22.04.1_amd64.deb
-:glibc:|libc-bin_2.35|libc-bin_2.35-0ubuntu3_amd64.deb
-:glibc:|libc-dev-bin_2.35|libc-dev-bin_2.35-0ubuntu3_amd64.deb
-:glibc:|libc6-dev_2.35|libc6-dev_2.35-0ubuntu3_amd64.deb
-:glibc:|libc6_2.35|libc6_2.35-0ubuntu3_amd64.deb
+:glibc:|libc-bin_2.35|libc-bin_2.35-0ubuntu3.1_amd64.deb
+:glibc:|libc-dev-bin_2.35|libc-dev-bin_2.35-0ubuntu3.1_amd64.deb
+:glibc:|libc6-dev_2.35|libc6-dev_2.35-0ubuntu3.1_amd64.deb
+:glibc:|libc6_2.35|libc6_2.35-0ubuntu3.1_amd64.deb
-:e2fsprogs:|libcom-err2_1.46.5|libcom-err2_1.46.5-2ubuntu1_amd64.deb
+:e2fsprogs:|libcom-err2_1.46.5|libcom-err2_1.46.5-2ubuntu1.1_amd64.deb
-:ghostscript:|libcups2_2.4.1op1|libcups2_2.4.1op1-1ubuntu4_amd64.deb
-:libcurl3-gnutls:|libcurl3-gnutls_7.81.0-1|libcurl3-gnutls_7.81.0-1_amd64.deb
-:curl:|libcurl4-openssl-dev_7.81.0-1|libcurl4-openssl-dev_7.81.0-1_amd64.deb
-:curl:|libcurl4_7.81.0-1|libcurl4_7.81.0-1_amd64.deb
+:ghostscript:|libcups2_2.4.1op1|libcups2_2.4.1op1-1ubuntu4.1_amd64.deb
+:libcurl3-gnutls:|libcurl3-gnutls_7.81.0|libcurl3-gnutls_7.81.0-1ubuntu1.6_amd64.deb
+:curl:|libcurl4-openssl-dev_7.81.0|libcurl4-openssl-dev_7.81.0-1ubuntu1.6_amd64.deb
+:curl:|libcurl4_7.81.0|libcurl4_7.81.0-1ubuntu1.6_amd64.deb
-:dbus:|libdbus-1-3_1.12.20|libdbus-1-3_1.12.20-2ubuntu4_amd64.deb
-:dbus:|libdbus-1-dev_1.12.20|libdbus-1-dev_1.12.20-2ubuntu4_amd64.deb
+:dbus:|libdbus-1-3_1.12.20|libdbus-1-3_1.12.20-2ubuntu4.1_amd64.deb
+:dbus:|libdbus-1-dev_1.12.20|libdbus-1-dev_1.12.20-2ubuntu4.1_amd64.deb
-:expat:|libexpat1-dev_2.4.7-1|libexpat1-dev_2.4.7-1_amd64.deb
-:expat:|libexpat1_2.4.7-1|libexpat1_2.4.7-1_amd64.deb
-:e2fsprogs:|libext2fs2_1.46.5|libext2fs2_1.46.5-2ubuntu1_amd64.deb
+:expat:|libexpat1-dev_2.4.7|libexpat1-dev_2.4.7-1ubuntu0.2_amd64.deb
+:expat:|libexpat1_2.4.7|libexpat1_2.4.7-1ubuntu0.2_amd64.deb
+:e2fsprogs:|libext2fs2_1.46.5|libext2fs2_1.46.5-2ubuntu1.1_amd64.deb
-:fribidi:|libfribidi-dev_1.0.8|libfribidi-dev_1.0.8-2ubuntu3_amd64.deb
-:fribidi:|libfribidi0_1.0.8|libfribidi0_1.0.8-2ubuntu3_amd64.deb
+:fribidi:|libfribidi-dev_1.0.8|libfribidi-dev_1.0.8-2ubuntu3.1_amd64.deb
+:fribidi:|libfribidi0_1.0.8|libfribidi0_1.0.8-2ubuntu3.1_amd64.deb
-:gdk-pixbuf:|libgdk-pixbuf-2.0-0_2.42.8+dfsg-1|libgdk-pixbuf-2.0-0_2.42.8+dfsg-1_amd64.deb
-:gdk-pixbuf:|libgdk-pixbuf-2.0-dev_2.42.8+dfsg-1|libgdk-pixbuf-2.0-dev_2.42.8+dfsg-1_amd64.deb
+:gdk-pixbuf:|libgdk-pixbuf-2.0-0_2.42.8+dfsg|libgdk-pixbuf-2.0-0_2.42.8+dfsg-1ubuntu0.2_amd64.deb
+:gdk-pixbuf:|libgdk-pixbuf-2.0-dev_2.42.8+dfsg|libgdk-pixbuf-2.0-dev_2.42.8+dfsg-1ubuntu0.2_amd64.deb
-:gdk-pixbuf:|libgdk-pixbuf2.0-bin_2.42.8+dfsg-1|libgdk-pixbuf2.0-bin_2.42.8+dfsg-1_amd64.deb
-:gdk-pixbuf:|libgdk-pixbuf2.0-common_2.42.8+dfsg-1|libgdk-pixbuf2.0-common_2.42.8+dfsg-1_all.deb
+:gdk-pixbuf:|libgdk-pixbuf2.0-bin_2.42.8+dfsg|libgdk-pixbuf2.0-bin_2.42.8+dfsg-1ubuntu0.2_amd64.deb
+:gdk-pixbuf:|libgdk-pixbuf2.0-common_2.42.8+dfsg|libgdk-pixbuf2.0-common_2.42.8+dfsg-1ubuntu0.2_all.deb
-:gnutls:|libgnutls-dane0_3.7.3|libgnutls-dane0_3.7.3-4ubuntu1_amd64.deb
-:gnutls:|libgnutls-openssl27_3.7.3|libgnutls-openssl27_3.7.3-4ubuntu1_amd64.deb
-:gnutls:|libgnutls28-dev_3.7.3|libgnutls28-dev_3.7.3-4ubuntu1_amd64.deb
-:gnutls:|libgnutls30_3.7.3|libgnutls30_3.7.3-4ubuntu1_amd64.deb
-:gnutls:|libgnutlsxx28_3.7.3|libgnutlsxx28_3.7.3-4ubuntu1_amd64.deb
+:gnutls:|libgnutls-dane0_3.7.3|libgnutls-dane0_3.7.3-4ubuntu1.1_amd64.deb
+:gnutls:|libgnutls-openssl27_3.7.3|libgnutls-openssl27_3.7.3-4ubuntu1.1_amd64.deb
+:gnutls:|libgnutls28-dev_3.7.3|libgnutls28-dev_3.7.3-4ubuntu1.1_amd64.deb
+:gnutls:|libgnutls30_3.7.3|libgnutls30_3.7.3-4ubuntu1.1_amd64.deb
+:gnutls:|libgnutlsxx28_3.7.3|libgnutlsxx28_3.7.3-4ubuntu1.1_amd64.deb
-:ghostscript:|libgs-dev_9.55.0|libgs-dev_9.55.0~dfsg1-0ubuntu5_amd64.deb
-:ghostscript:|libgs9-common_9.55.0|libgs9-common_9.55.0~dfsg1-0ubuntu5_all.deb
-:ghostscript:|libgs9_9.55.0|libgs9_9.55.0~dfsg1-0ubuntu5_amd64.deb
+:ghostscript:|libgs-dev_9.55.0|libgs-dev_9.55.0~dfsg1-0ubuntu5.1_amd64.deb
+:ghostscript:|libgs9-common_9.55.0|libgs9-common_9.55.0~dfsg1-0ubuntu5.1_all.deb
+:ghostscript:|libgs9_9.55.0|libgs9_9.55.0~dfsg1-0ubuntu5.1_amd64.deb
-:harfbuzz:|libharfbuzz-dev_2.7.4|libharfbuzz-dev_2.7.4-1ubuntu3_amd64.deb
-:harfbuzz:|libharfbuzz-gobject0_2.7.4|libharfbuzz-gobject0_2.7.4-1ubuntu3_amd64.deb
-:harfbuzz:|libharfbuzz-icu0_2.7.4|libharfbuzz-icu0_2.7.4-1ubuntu3_amd64.deb
-:harfbuzz:|libharfbuzz0b_2.7.4|libharfbuzz0b_2.7.4-1ubuntu3_amd64.deb
+:harfbuzz:|libharfbuzz-dev_2.7.4|libharfbuzz-dev_2.7.4-1ubuntu3.1_amd64.deb
+:harfbuzz:|libharfbuzz-gobject0_2.7.4|libharfbuzz-gobject0_2.7.4-1ubuntu3.1_amd64.deb
+:harfbuzz:|libharfbuzz-icu0_2.7.4|libharfbuzz-icu0_2.7.4-1ubuntu3.1_amd64.deb
+:harfbuzz:|libharfbuzz0b_2.7.4|libharfbuzz0b_2.7.4-1ubuntu3.1_amd64.deb
-:libinput:|libinput-bin_1.20.0-1|libinput-bin_1.20.0-1_amd64.deb
-:libinput:|libinput-dev_1.20.0-1|libinput-dev_1.20.0-1_amd64.deb
-:libinput:|libinput10_1.20.0-1|libinput10_1.20.0-1_amd64.deb
+:libinput:|libinput-bin_1.20.0|libinput-bin_1.20.0-1ubuntu0.1_amd64.deb
+:libinput:|libinput-dev_1.20.0|libinput-dev_1.20.0-1ubuntu0.1_amd64.deb
+:libinput:|libinput10_1.20.0|libinput10_1.20.0-1ubuntu0.1_amd64.deb
-:xorg_dri:|libllvm13_13.0.1|libllvm13_13.0.1-2ubuntu2_amd64.deb
+:xorg_dri:|libllvm13_13.0.1|libllvm13_13.0.1-2ubuntu2.1_amd64.deb
-:evince:|libnss3_3.68.2|libnss3_3.68.2-0ubuntu1_amd64.deb
-:ntfs-3g:|libntfs-3g89_2021.8.22|libntfs-3g89_2021.8.22-3ubuntu1_amd64.deb
+:evince:|libnss3_3.68.2|libnss3_3.68.2-0ubuntu1.1_amd64.deb
+:ntfs-3g:|libntfs-3g89_2021.8.22|libntfs-3g89_2021.8.22-3ubuntu1.2_amd64.deb
-:perl:|libperl5.34_5.34.0|libperl5.34_5.34.0-3ubuntu1_amd64.deb
+:perl:|libperl5.34_5.34.0|libperl5.34_5.34.0-3ubuntu1.1_amd64.deb
-:evince:|libpoppler-glib8_22.02.0-2|libpoppler-glib8_22.02.0-2_amd64.deb
-:evince:|libpoppler118_22.02.0-2|libpoppler118_22.02.0-2_amd64.deb
+:evince:|libpoppler-glib8_22.02.0|libpoppler-glib8_22.02.0-2ubuntu0.1_amd64.deb
+:evince:|libpoppler118_22.02.0|libpoppler118_22.02.0-2ubuntu0.1_amd64.deb
-:sqlite:|libsqlite3-0_3.37.2-2|libsqlite3-0_3.37.2-2_amd64.deb
+:sqlite:|libsqlite3-0_3.37.2|libsqlite3-0_3.37.2-2ubuntu0.1_amd64.deb
-:e2fsprogs:|libss2_1.46.5|libss2_1.46.5-2ubuntu1_amd64.deb
+:e2fsprogs:|libss2_1.46.5|libss2_1.46.5-2ubuntu1.1_amd64.deb
-:openssl:|libssl-dev_3.0.2|libssl-dev_3.0.2-0ubuntu1_amd64.deb
-:openssl:|libssl3_3.0.2|libssl3_3.0.2-0ubuntu1_amd64.deb
+:openssl:|libssl-dev_3.0.2|libssl-dev_3.0.2-0ubuntu1.7_amd64.deb
+:openssl:|libssl3_3.0.2|libssl3_3.0.2-0ubuntu1.7_amd64.deb
-:libsystemd:|libsystemd-dev_249.11|libsystemd-dev_249.11-0ubuntu3_amd64.deb
-:libsystemd:|libsystemd0_249.11|libsystemd0_249.11-0ubuntu3_amd64.deb
+:libsystemd:|libsystemd-dev_249.11|libsystemd-dev_249.11-0ubuntu3.6_amd64.deb
+:libsystemd:|libsystemd0_249.11|libsystemd0_249.11-0ubuntu3.6_amd64.deb
-:gdk-pixbuf:|libtiff-dev_4.3.0-6|libtiff-dev_4.3.0-6_amd64.deb
-:evince:|libtiff5_4.3.0-6|libtiff5_4.3.0-6_amd64.deb
-:gdk-pixbuf:|libtiffxx5_4.3.0-6|libtiffxx5_4.3.0-6_amd64.deb
+:gdk-pixbuf:|libtiff-dev_4.3.0|libtiff-dev_4.3.0-6ubuntu0.3_amd64.deb
+:evince:|libtiff5_4.3.0|libtiff5_4.3.0-6ubuntu0.3_amd64.deb
+:gdk-pixbuf:|libtiffxx5_4.3.0|libtiffxx5_4.3.0-6ubuntu0.3_amd64.deb
-:libudev:|libudev-dev_249.11|libudev-dev_249.11-0ubuntu3_amd64.deb
-:libudev:|libudev1_249.11|libudev1_249.11-0ubuntu3_amd64.deb
+:libudev:|libudev-dev_249.11|libudev-dev_249.11-0ubuntu3.6_amd64.deb
+:libudev:|libudev1_249.11|libudev1_249.11-0ubuntu3.6_amd64.deb
-:libunbound:|libunbound8_1.13.1|libunbound8_1.13.1-1ubuntu5_amd64.deb
+:libunbound:|libunbound8_1.13.1|libunbound8_1.13.1-1ubuntu5.3_amd64.deb
-:wayland-dev:|libwayland-bin_1.20.0-1|libwayland-bin_1.20.0-1_amd64.deb
-:wayland:|libwayland-client0_1.20.0-1|libwayland-client0_1.20.0-1_amd64.deb
-:wayland:|libwayland-cursor0_1.20.0-1|libwayland-cursor0_1.20.0-1_amd64.deb
-:wayland-dev:|libwayland-dev_1.20.0-1|libwayland-dev_1.20.0-1_amd64.deb
-:mesa:|libwayland-egl1_1.20.0-1|libwayland-egl1_1.20.0-1_amd64.deb
-:mesa:|libwayland-server0_1.20.0-1|libwayland-server0_1.20.0-1_amd64.deb
+:wayland-dev:|libwayland-bin_1.20.0|libwayland-bin_1.20.0-1ubuntu0.1_amd64.deb
+:wayland:|libwayland-client0_1.20.0|libwayland-client0_1.20.0-1ubuntu0.1_amd64.deb
+:wayland:|libwayland-cursor0_1.20.0|libwayland-cursor0_1.20.0-1ubuntu0.1_amd64.deb
+:wayland-dev:|libwayland-dev_1.20.0|libwayland-dev_1.20.0-1ubuntu0.1_amd64.deb
+:mesa:|libwayland-egl1_1.20.0|libwayland-egl1_1.20.0-1ubuntu0.1_amd64.deb
+:mesa:|libwayland-server0_1.20.0|libwayland-server0_1.20.0-1ubuntu0.1_amd64.deb
-:glibc_locales:|locales_2.35|locales_2.35-0ubuntu3_all.deb
-:login:|login_4.8.1|login_4.8.1-2ubuntu2_amd64.deb
-:e2fsprogs:|logsave_1.46.5|logsave_1.46.5-2ubuntu1_amd64.deb
+:glibc_locales:|locales_2.35|locales_2.35-0ubuntu3.1_all.deb
+:login:|login_4.8.1|login_4.8.1-2ubuntu2.1_amd64.deb
+:e2fsprogs:|logsave_1.46.5|logsave_1.46.5-2ubuntu1.1_amd64.deb
-:ntfs-3g:|ntfs-3g_2021.8.22|ntfs-3g_2021.8.22-3ubuntu1_amd64.deb
+:ntfs-3g:|ntfs-3g_2021.8.22|ntfs-3g_2021.8.22-3ubuntu1.2_amd64.deb
-:openssl:|openssl_3.0.2|openssl_3.0.2-0ubuntu1_amd64.deb
+:openssl:|openssl_3.0.2|openssl_3.0.2-0ubuntu1.7_amd64.deb
-:passwd:|passwd_4.8.1|passwd_4.8.1-2ubuntu2_amd64.deb
+:passwd:|passwd_4.8.1|passwd_4.8.1-2ubuntu2.1_amd64.deb
-:perl:|perl-base_5.34.0|perl-base_5.34.0-3ubuntu1_amd64.deb
-:perl:|perl-modules-5.34_5.34.0|perl-modules-5.34_5.34.0-3ubuntu1_all.deb
-:perl:|perl_5.34.0|perl_5.34.0-3ubuntu1_amd64.deb
+:perl:|perl-base_5.34.0|perl-base_5.34.0-3ubuntu1.1_amd64.deb
+:perl:|perl-modules-5.34_5.34.0|perl-modules-5.34_5.34.0-3ubuntu1.1_all.deb
+:perl:|perl_5.34.0|perl_5.34.0-3ubuntu1.1_amd64.deb
-:xserver_xorg:|python3-apport_2.20.11|python3-apport_2.20.11-0ubuntu82_all.deb
+:xserver_xorg:|python3-apport_2.20.11|python3-apport_2.20.11-0ubuntu82.2_all.deb
-:xserver_xorg:|python3-jwt_2.3.0-1|python3-jwt_2.3.0-1_all.deb
+:xserver_xorg:|python3-jwt_2.3.0|python3-jwt_2.3.0-1ubuntu0.2_all.deb
-:xserver_xorg:|python3-oauthlib_3.2.0-1|python3-oauthlib_3.2.0-1_all.deb
+:xserver_xorg:|python3-oauthlib_3.2.0|python3-oauthlib_3.2.0-1ubuntu0.1_all.deb
-:xserver_xorg:|python3-problem-report_2.20.11|python3-problem-report_2.20.11-0ubuntu82_all.deb
+:xserver_xorg:|python3-problem-report_2.20.11|python3-problem-report_2.20.11-0ubuntu82.2_all.deb
-:rsync:|rsync_3.2.3|rsync_3.2.3-8ubuntu3_amd64.deb
+:rsync:|rsync_3.2.3|rsync_3.2.3-8ubuntu3.1_amd64.deb
-:e2fsprogs:|ss-dev_2.0-1.46.5|ss-dev_2.0-1.46.5-2ubuntu1_amd64.deb
+:e2fsprogs:|ss-dev_2.0-1.46.5|ss-dev_2.0-1.46.5-2ubuntu1.1_amd64.deb
-:udev:|udev_249.11|udev_249.11-0ubuntu3_amd64.deb
+:udev:|udev_249.11|udev_249.11-0ubuntu3.6_amd64.deb
-:unzip:|unzip_6.0|unzip_6.0-26ubuntu3_amd64.deb
+:unzip:|unzip_6.0|unzip_6.0-26ubuntu3.1_amd64.deb
-:wpa_supplicant:|wpasupplicant_2.10-6|wpasupplicant_2.10-6_amd64.deb
+:wpa_supplicant:|wpasupplicant_2.10|wpasupplicant_2.10-6ubuntu2_amd64.deb
-:xserver_xorg:|xserver-common_21.1.3|xserver-common_21.1.3-2ubuntu2_all.deb
-:xserver_xorg:|xserver-xorg-core_21.1.3|xserver-xorg-core_21.1.3-2ubuntu2_amd64.deb
+:xserver_xorg:|xserver-common_21.1.3|xserver-common_21.1.3-2ubuntu2.4_all.deb
+:xserver_xorg:|xserver-xorg-core_21.1.3|xserver-xorg-core_21.1.3-2ubuntu2.4_amd64.deb
-:zlib:|zlib1g-dev_1.2.11.dfsg|zlib1g-dev_1.2.11.dfsg-2ubuntu9_amd64.deb
-:zlib:|zlib1g_1.2.11.dfsg|zlib1g_1.2.11.dfsg-2ubuntu9_amd64.deb
+:zlib:|zlib1g-dev_1.2.11.dfsg|zlib1g-dev_1.2.11.dfsg-2ubuntu9.2_amd64.deb
+:zlib:|zlib1g_1.2.11.dfsg|zlib1g_1.2.11.dfsg-2ubuntu9.2_amd64.deb
```

**Pull request merged**
