### PR TITLE
Change to CONFIG_FUSE_FS=y, to make ntfs-3g work

### LINKED ISSUE #3058: ntfs boot failure with kernels 5.10 and 5.15
Even after #3056 
slacko-8.2.2-174.iso  ([build-x86-slackware-15.0-174])
fails to boot from an ntfs formatted boot partition
5.10 and 5.15 both fail
5.4 is OK

### PR DESCRIPTION
**Pull request by dimkr**
This _should_ fix #3058.

### CODE REVIEW

**Review by peabee — CHANGES_REQUESTED** [review]
5.4 has both
CONFIG_FUSE_FS=y
and
CONFIG_NTFS_FS=y
[hash] CONFIG_NTFS_DEBUG is not set
CONFIG_NTFS_RW=y

Shouldn't 5.10 and 5.15 be the same??

**Comment by dimkr** [comment]
CONFIG_NTFS_FS=y doesn't matter, because Puppy uses ntfs-3g (a FUSE-based file system). #3056 didn't do anything.

**Comment by peabee** [comment]
Lets try it - but I do feel that 5.4 5.10 and 5.15 should be as consistent as possible

**Note**: 5.15.36 aufs patches need an update and so 5.15 build will fail until released:
https://github.com/sfjro/aufs5-standalone/issues/12#issuecomment-1114352961

**Comment by dimkr** [comment]
> Lets try it - but I do feel that 5.4 5.10 and 5.15 should be as consistent as possible

I disagree, the 5.4.x configuration has many unused drivers, like the NTFS one. It's a very crude configuration file.

**Pull request merged**
