### PR TITLE
puppyapps: remove unused gui code

### PR DESCRIPTION
**Pull request by wdlkmpx**

### CODE REVIEW

**Comment by wdlkmpx** [comment]
In commit https://github.com/wdlkmpx/woof-CE/commit/bd330942b2801b07e5731af7e02ed4f20725da56 I added another critical improvement for the gui

**Comment by wdlkmpx** [comment]
zigbert, do you think we can remove barehtmlviewer and musicplayer and add torrent[client] and presentation

**Comment by zigbert** [comment]
go on

**Comment by zigbert** [comment]
I rewrite pMusic to reduce subshells and have one bash question:
It is easy to grab the first/last field of a string by ie. ${VAR##*|}, but how to easy grab field nr 12 (pMusic's file format contains 21 columns with | as separator) with only using internal bash. I am using cut/awk but I see how much faster things can run if it is possible to use bash's own commands.

**Comment by wdlkmpx** [comment]
Well, you can create with bash functions to do anything, but that requires thinking more like a C programmer, if you want to keep it simple just the use read builtin command

read -r var1 var2 < inputfile
read -r var1 var2 <<< "$var"
read -r var1 var2 <<< "$(function)"

	str="a b c d"
	
	read var1 var2 var3 var4 <<< "$str"
	var1=a
	var2=b
	var3=c
	var4=d

	read var1 var2  <<< "$str"
	var1=a
	var2=b c d

We'll apply the same logic, but using | as delimiter

	FSI=$IFS
	IFS='|'
	
	str="a|b|c|d"
	
	read var1 var2 var3 var4 <<< "$str"
	var1=a
	var2=b
	var3=c
	var4=d

	read var1 var2 <<< "$str"
	var1=a
	var2=b|c|d
	
	IFS=$FSI

Now with 21 fields, this will assign all fields to a variable just choose which to use later


	entry="field01|field02|field03|field04|field05|field06|field07|field08|field09|field10|field11|field12|field13|field14|field15|field16|field17|field18|field19|field20|field21|"

	FSI=$IFS
	IFS='|'
	read -r one two three four five six seven eight \
	nine ten eleven twelve thirteen fourteen fifteen \
	sixteen seventeen eighteen nineteen twenty twenty1 <<< "$entry"
	IFS=$FSI

	echo "$one
	$two
	$three
	$four
	$five
	$six
	$seven
	$eight
	$nine
	$ten
	$eleven
	$twelve
	$thirteen
	$fourteen
	$fifteen
	$sixteen
	$seventeen
	$eighteen
	$nineteen
	$twenty
	$twenty1"

-

**Comment by zigbert** [comment]
Thanks a lot!

**Comment by 01micko** [comment]
You can change IFS on the line of the `read` command and it is changed only for that read command. no need to store old IFS

**Comment by zigbert** [comment]
wonderful!
I will become a better coder.

**Pull request merged**
