### PR TITLE
Allow merge2out-gui to be scrollable

### PR DESCRIPTION
**Pull request by lakshayrohila**
`merge2out-gui` currently doesn't use scrollbar, and hence there is no way that users may be able to see all of the options/buttons due to this. Nor does `gtkdialog` window resize or move on some (or all) versions.

This PR makes `merge2out-gui` use scrollbar to resolve this issue.

This PR also resolves (https://github.com/puppylinux-woof-CE/woof-CE/issues/3590).

### CODE REVIEW

**Comment by lakshayrohila** [comment]
Is there anything I need to reconsider here, @dimkr?

**Comment by dimkr** [comment]
Nope, looks fine IMO

**Comment by lakshayrohila** [comment]
> Nope, looks fine IMO

Ok, thanks! I thought that the PR was not being accepted because of it having some issues. Relieved that there wasn't any.

**Comment by dimkr** [comment]
I'm doing my best not to break stuff during @01micko's absence. It's always good to have a second pair of eyes before changes are merged.

I'll abuse my merge rights again, because these are two single-line changes.

**Pull request merged**
