### PR TITLE
Legacy network managers: Accommodate ConnMan, PeasyWiFi, gtk3, plus refinements

### PR DESCRIPTION
**Pull request by rserwin1**
(Title entered as comment by mistake.)

### CODE REVIEW

**Comment by rserwin1** [comment]
Frisbee, NetWiz & SNS were tested by multiple users of BookWormPup64, with no unresolved complaints, and also by the developer on F96CE, NoblePup32, FossaPup64,BionicPup64 and XenialPup64.

Some changes were adapted from EasyOS modifications, although the managers were then removed in EasyOS.

**Comment by rserwin1** [comment]
Change log since last PR for Frisbee:
2.0.2 - Use GTK+ 2 version of gtkdialog, to work around gtk+ 3 sizing issue.
2.0.3 - Export GTKDIALOG for functions run by dialogs; correct wireless check (in get_interfaces), because 'iw' may detect only devices with drivers that use nl80211, not those using wext. 
2.0.4 - Improve already-running response to avoid subsequent connectwizard prompt and to kill possible remaining xdialog.

**Comment by rserwin1** [comment]
Change log since last PR for Network Wizard:
2.3:
 - Remove unnecessary sleep after validateWpaAuthentication that overrides exit status.
 - Remove "Puppy" from text messages.
 - /usr/local/network-wizard/rc.network renamed to rc.wiznetwork.
 - Change to gettext; remove ndiswrapper; write to /tmp/network-wizard.
 - Remove iwconfig; replace ifconfig with busybox ip.
 - Use gtk+ 2 version of gtkdialog, to work around gtk+ 3 sizing issue.
 - Add check for already running; add Xdialog --wmclass netwiz to identify for cleanup by connectwizard-exec.
 
3.0:
 - Resolve most shellcheck issues.
 - Replace ethtool with ip-show test for LOWER_UP.
 - Unsuppress sysout from CleanupInterface, to allow trace of it.
 - Recode ip -oneline commands because option not supported by BionicPup busybox.
 - Accept upper case interface MAC addresses in interface .conf names.
 - Add check for wayland graphical environment.
 
3.0.1:
 - Replace unreliable pidof with pgrep.
 - Merge duplicate tests for already running; improve already-running response to avoid subsequent connectwizard prompt and to kill possible remaining dialog.
 
3.0.2:
 - Change pinstall.sh to avoid removing obsolete /etc/rc.d/rc.network if peasywifi's rc.network is installed.

**Comment by rserwin1** [comment]
Change log since last PR for Simple Network Setup:
v3.3.2:
 - /usr/local/simple_network_setup/rc.network renamed to rc.snsnetwork; log names changed to match; simplified already-running check.
 - Ongoing wpa_supplicant log.
 - Removed "Barry's ..." from window title; removed "Puppy" from messages.
 - Chmod 600 /etc/simple_network_setup/connections so non-root apps cannot see it.
 - Fix for tainted module, for which modinfo doesn't work.

v3.4:
 - Refine ensure_driver_modules_loaded and elsewhere; always wait for wired connection (revert from 211231); running check improved.  
 - For gtkdialog '-p SNS_' argumemt, use long option for connectwizard_exec to find; running check improved; use profile security key if none entered; rc.snsnetwork updated; build_modulelist updated.
 - Change and rename driver-detection rule to avoid relying on MODALIAS variable, passing driver name to build_udevmodulelist and improving reliability; simplify preferences to avoid using modprobe; support either net/staging or pci... subsystem rules.

v3.5:
 - Use gtk+ 2 version of gtkdialog, to work around gtk+ 3 sizing issue.
 - Add checks for wayland graphical environment.
 - Add frisbee to check for dhcpcd running.
 - Refine wpa_supplicant test to confine instances to those for SNS.
 - Remove tests of /etc/resolv.conf, dhcpcd, udhcpc in find_usable_interfaces.
 - Reset resolv.conf before dhcpcd.
 - Add message if active connection by another network manager.
 - Reimplement registering change to sns upon connect/disconnect to accommodate switching from connman or peasywifi, which starts netmon_wce.

v3.5.1:
 - Replace unreliable pidof with pgrep.
 - Improve already-running response to avoid subsequent connectwizard prompt and to kill possible remaining xdialog.

v3.5.2:
 - Add use of gtk2dialog by all dialogs; add GTKDIALOG_BUILD to utilize gtk2 theming.

**Comment by techrockedge** [comment]
looks good.

**Comment by peabee** [comment]
Thanks Richard

**Pull request merged**
