### PR TITLE
kernel-kit: add 5.13 DOTconfig and build.conf

### LINKED ISSUE #2403: Linux 5.12 is EOL
We need a config for 5.13

### PR DESCRIPTION
**Pull request by 01micko**
fix funcs.sh for 5.13
closes #2403

### CODE REVIEW

**Comment by dimkr** [comment]
How about removing the 5.12 files?

**Comment by 01micko** [comment]
> How about removing the 5.12 files?

file? 

Yes, while I'm at it I'll remove the 'cherrytrail' one too.

**Comment by dimkr** [comment]
> file?

Whoops, missed the renaming of kernel-kit/5.12.x-x86_64-build.conf 😊

**Comment by 01micko** [comment]
I miss stuff all the time. Try not to, but that's why we use PRs for important stuff.

**Pull request merged**
