### PR TITLE
xorgwizard: Add startx option

### PR DESCRIPTION
**Pull request by rizalmart**
Add start X option in xorgwizard commandline menu

### CODE REVIEW

**Comment by wdlkmpx** [comment]
This breaks the shutdown sequence in dpup and probably in all wce pxps

**Comment by rizalmart** [comment]
Can you give me some details why it breaks shutdown sequence?

**Comment by wdlkmpx** [comment]
xwin or something.. will reply tomorrow.. cellphone running out of battery 2%

**Comment by wdlkmpx** [comment]
When I select `Start X Window System` Xorg starts fine.

But when I want to reboot, it only drops to the console and xauth is missing, and I need to type reboot again.

I think it's because it's bypassing xwin or something.

**Comment by rizalmart** [comment]
That's weird. startx should start Desktop Environment normally. I modified now the script. instead of using startx to start DE, it uses xwin command

**Comment by wdlkmpx** [comment]
It works fine now. Well there some outstanding anomalies. It should be fixed by deleting most of the codebase.

**Pull request merged**
