### PR TITLE
Fdrv is in reasonable shape to be merged.

### PR DESCRIPTION
**Pull request by 01micko**
I have brought fdrv up to date and believe we can merge it. It works well, and maybe @wdlkmpx might like to look at the `kernel-kit/firmware.sh`, just for fun, or not :8ball:

### CODE REVIEW

**Comment by mavrothal** [comment]
Looks fine to me.
After this (and the rest of the changes in testing) I guess puppies from testing should get at least a minor version bump.

**Comment by 01micko** [comment]
Yeah, I'm nearly finished with pupdial/pgprs2 which were the major bugs in slacko.. fdrv will fix RSH/Lazy Puppy's issues I believe.

I'll be a couple of weeks though, a bit busy.

**Comment by 01micko** [comment]
Ok, so no objections? 
If any, then post in the next 24 hours. After that I'm merging. :cat:

**Comment by mavrothal** [comment]
:+1:

**Comment by wdlkmpx** [comment]
If you can also merge pull request #605

**Comment by 01micko** [comment]
Yeah, should've been merged at the time (#605). After I merge this (there's a few hours left) I'll take a look. I did test a build from 605 and it was fine. I think I was way busy getting slacko up to release standard at that time and anything else got shoved to the back burner.

**Pull request merged**
