### PR TITLE
Improve contrast in the Breeze JWM theme (fixes #3706)

### LINKED ISSUE #3706: Poor contrast in the Breeze JWM theme
The window title and the buttons of inactive windows blend into the background:

image

### PR DESCRIPTION
**Pull request by dimkr**
@lakshayrohila Did I ruin your theme?

### CODE REVIEW

**Comment by lakshayrohila** [comment]
Can you provide a screenshot for this. I think only the background and foreground for inactive processes needed to be changed, still I want to take a look.

**Comment by dimkr** [comment]
The contrast between the selected menu item and the background is better and inactive windows use dark title bars.

Here's how the theme behaves without this PR:

**Comment by lakshayrohila** [comment]
> 
> 
> The contrast between the selected menu item and the background is better and inactive windows use dark title bars.
> 
> Here's how the theme behaves without this PR:
> 
> 

Sorry for that. I didn't actually look at the background color previously. Your modification is great! (Read https://github.com/dimkr/woof-CE/commit/d39a7b8b01834e4a252f301dec2200dab629fbc7#commitcomment-92267230).

**Review by lakshayrohila — APPROVED** [review]
Tested the theme on my puppy as well. Seems great now.

**Comment by dimkr** [comment]
@lakshayrohila Let me know if you change your mind, there's nothing that can't be fixed or changed

**Pull request merged**
