### PR TITLE
Create psynclient

### PR DESCRIPTION
**Pull request by rizalmart**
psynclient is a gui frontend of synclient for configuring synaptic touchpads. It works the same as flsynclient but it has advanced options, extremely lightweight, and architecture independent.

### CODE REVIEW

**Comment by peabee** [comment]
flSynclient is not in rootfs-skeleton.........

this should be in rootfs-packages?

**Comment by peabee** [comment]
other apps will break if flsynclient is not in the build

**Comment by peabee** [comment]
also........ libinput is replacing synclient......... so synclient is not in every build.

**Comment by rizalmart** [comment]
@peebee right now Im trying to add the libinput support for psynclient. However I have to deal with some matrix data types in libinput device properties.

**Comment by wdlkmpx** [comment]
I'll merge this. Take your time to test it properly and fix as many issues as you can. You'll need feedback.

flSynclient requires fltk... a toolkit that looks really bad. With this flsynclient and fltk can be removed. A smaller build.

Googling I found this:
http://45.33.15.200/puppy/viewtopic.php?t=117245&sid=5a8deb1db0b3c7dfaa52c8ea13b48d0f

http://www.murga-linux.com/puppy/viewtopic.php?t=117240

So everyone help rizalmart test this app that WILL replace flsynclient in the future.

**Comment by peabee** [comment]
rcrsn51 has done some work on libinput control of touchpads:
http://murga-linux.com/puppy/viewtopic.php?p=1039748#1039748

**Comment by rizalmart** [comment]
@peabee I already saw that script, however it was manipulation of an xorg conf file. Much better if libinput configuration works like synclient which was on the fly setup. It was possible through xinput. The real problem was matrix data type (two values returned by the libinput properties). I need some help to parse properly that kind of data type came from xinput

**Comment by wdlkmpx** [comment]
This page explains how to add/update noarch packages

https://github.com/puppylinux-woof-CE/woof-CE/wiki/Adding-or-Updating-noarch-packages

**Comment by rizalmart** [comment]
I cant upload pet packages. It shows this error message on github

"Uploads are disabled.
File uploads require push access to this repository."

**Comment by wdlkmpx** [comment]
Check your email
Screenshot(15)

**Comment by rizalmart** [comment]
psynclient and pupmixer is now uploaded

**Pull request closed without merging**
