### PR TITLE
Update DISTRO_PKGS_SPECS-ubuntu-bionic

### PR DESCRIPTION
**Pull request by rizalmart**
Added desktop-file-utils

### CODE REVIEW

**Comment by peabee** [comment]
What are these utils and why are you adding them?? What problem are you trying to solve???

**Comment by peabee** [comment]
Are they compatible with the Puppy menu structure???

**Comment by rizalmart** [comment]
desktop-file-utils is a vital component to any xdg-compliant file manager like pcmanfm, thunar, etc for file associations. Without that, file associations for new added package or loaded sfs modules will just simply dont work on those xdg-compliant file management. One of the flaws in Puppy that needed to be fix. XenialPup has desktop-file-utils by default  but it seems not yet utilize in Puppy's Package Management in its peak release. It was lately implemented when I start to contribute here

**Comment by mavrothal** [comment]
desktop-file-utils is included in Phil's pups. However, without a call from PPM or SFS_load is not going to be very useful.
You might want to do a proper pull and put all spec changes together and also add call to ```update-desktop-database```  in places where ```fixmenus``` is called. Preferably only when other than the ROX-filer file manager is also running.

**Comment by rizalmart** [comment]
mavrothal my pull request about calling update-desktop-database on PPM and sfs_load is already merged in woof-ce (take a look on the commit history). One of the downside of the ROX-Filer is that rox is not xdg-compliant, instead it has own file association management. I wonder if woodenshoe-wi can modify ROX-Filer and make it xdg-desktop compliant

**Comment by wdlkmpx** [comment]
I remember mimeinfo.cache was a problematic file while using pcmanfm and my list of file associations

update-desktop-database creates  $XDG_DATA_DIRS/applications/mimeinfo.cache 

I have this line in a script
rm -fv ${SYSROOT}/usr/share/applications/mimeinfo.cache #this file is always trouble

https://bbs.archlinux.org/viewtopic.php?id=97886

**Comment by rizalmart** [comment]
mimeinfo.cache its just a raw database of file associations. But it can be easily override by placing custom default file association in mimeapps.list in $HOME/.config or in $HOME/.local/share/applications it will read it first before mimeinfo.cache for searching default file association

**Comment by wdlkmpx** [comment]
I think i tried to create d4fault file associations for all users in /usr/share/applications/mimeapps.list, but with mimeinfo.cache present it ignored everything

**Comment by rizalmart** [comment]
@wdlkmpx you can also try /usr/share/applications/defaults.list

**Comment by wdlkmpx** [comment]
Mimeapps.list is the file that worked fine with pcmanfm,for default
applications and file associations.

This will certainly break some code and configurations, have to change
paths, i have an extensive list of file associations. this wilL probably
break pmime

**Comment by rizalmart** [comment]
what paths are needed to change? and what files that are affected?

**Pull request closed without merging**
