### PR TITLE
Bluetooth audio support in focal64

### PR DESCRIPTION
**Pull request by dimkr**
This is https://github.com/puppylinux-woof-CE/woof-CE/pull/2349, but for focal64. Now, PulseAudio works for both root and spot, with Bluetooth audio support.

### CODE REVIEW

**Review by 01micko — APPROVED** [review]
looks fine to me

**Comment by mrfricks** [comment]
happy to see how blueman / pulseaudio compares to bluez-alsa.

**Review by mrfricks — APPROVED** [review]

**Comment by dimkr** [comment]
@mrfricks I'm leaving the decision whether or not to merge this PR, to you.

The main benefit of using Blueman is the use of PulseAudio. Because most graphical audio editors, browsers, mixers, etc' use PulseAudio noawadays, it's more elegant (in some ways) to use PulseAudio across the board and avoid direct use of ALSA. For example, the way woof-CE handles PulseAudio now makes audio work for spot too, and both spot and root can see Bluetooth output devices. It's non-trivial to achieve this consistency with ALSA, as far as I'm aware.

It's true that PulseAudio pulls in some dependencies, and it's an extra daemon that needs to run, but I think it's not too bad because 1) it's just one process for both root and spot and 2) you need bluetoothd anyway 3) Bluetooth is ubiquitous and that's enough to justify good support for it, even if it costs extra RAM.

**Comment by rizalmart** [comment]
@mrfricks 

> happy to see how blueman / pulseaudio compares to bluez-alsa.

I used blueman and pulseaudio, it works nicely and easy to setup bluetooth audio devices

**Comment by 01micko** [comment]
Ok, I'm happy to merge this. If no objection by the weekend I will do so.

**Pull request merged**
