### PR TITLE
update puppy.xml

### PR DESCRIPTION
**Pull request by wdlkmpx**

### CODE REVIEW

**Comment by wdlkmpx** [comment]
Now it only adds *.ext2 *.ext3 *.ext4, which are widely used

**Comment by mavrothal** [comment]
But ext2-4 are already in puppy.xml.
All I see see changed is white space. BTW there is no return after the last line.

**Comment by wdlkmpx** [comment]
This will allow puppy to recognize and mount *.extX files from other
distros, *.4fs is only used in puppy as far as I know

**Comment by mavrothal** [comment]
Maybe I'm not clear. Your pull request does not have any new code that I can see. All the differences in the patch, are in whitespace.

**Comment by wdlkmpx** [comment]
Well you must be blind

**Comment by mavrothal** [comment]
That's what I see in your commit (before removing the webm).
Is there anything else that I suppose to see?

commit

**Comment by wdlkmpx** [comment]
I see *.ext2 *.ext3 *.ext4 file extensions that will be recognized by puppy after running update-mime-database /usr/share/mime

**Comment by mavrothal** [comment]
Oh, these ones!
I really missed them among the white space changes.
Sorry.
But are there any files with ext[2-4] extension?

**Comment by mavrothal** [comment]
BTW I posted a question yesterday in your other pull about defaultfm.
Please take a look

**Comment by wdlkmpx** [comment]
Yes. Actually *.4fs *.3fs *.2fs are not used anywhere but puppy.

rootfs.ext2-4
https://community.freescale.com/thread/318651
http://unix.stackexchange.com/questions/212825/how-does-rootfs-ext3-image-file-work
https://www.olimex.com/forum/index.php?topic=1519.5;wap2

**Pull request closed without merging**
