### PR TITLE
Use Debian firmware packages in dpup

### PR DESCRIPTION
**Pull request by dimkr**
Now the fdrv includes stuff like iwlwifi non-free firmware, often requested by users.

### CODE REVIEW

**Comment by 01micko** [comment]
IDK about this because I'm in the process of fixing the firmware script in kernel-kit.

@ iwlwifi firmwares are not copied because they are different versions to what `modinfo` asks for , particularly `iwlwifi-6000-6.ucode` Green Geek's issue will be solved if the 4 version is included going on his dmesg log. The version in the kernel.org firmware repo is `iwlwifi-6000-4.ucode` so I am making a case for that in the script, and when the actual `iwlwifi-6000-6.ucode` version does land in the firmware repo then that version will be picked. I notice Debian includes the `iwlwifi-6000-4.ucode`version going on the package list.

**Comment by dimkr** [comment]
@01micko I don't see iwlwifi-6000-6.ucode in https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/. Are you sure the missing file isn't coming from one of the tarballs in https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi?

**Comment by 01micko** [comment]
It's definitely not, but the 4 version is there. And my code works. Also moving code for B43 and ipw firmwares to kernelkit, doing test build now and will show the `firmware.lst.$kver`

If 6 lands in git tree my code will pick that instead.

**Comment by 01micko** [comment]
Ok, closed. I'll post my PR in about an hour or two.

Here are the relevant parts of the firmware list:
```sh
atsc_denver.inp                                      missing
av7110/bootcode.bin
b43/ucode11.fw
b43/ucode13.fw
b43/ucode14.fw
b43/ucode15.fw
b43/ucode16_lp.fw
b43/ucode16_mimo.fw
b43/ucode24_lcn.fw
b43/ucode25_lcn.fw
b43/ucode25_mimo.fw
b43/ucode26_mimo.fw
b43/ucode29_mimo.fw
b43/ucode30_mimo.fw
b43/ucode33_lcn40.fw
b43/ucode40.fw
b43/ucode42.fw
b43/ucode5.fw
b43/ucode9.fw
b43legacy/ucode2.fw
b43legacy/ucode4.fw
bfubase.frm                                          missing
bnx2/bnx2-mips-06-6.2.3.fw
bnx2/bnx2-mips-09-6.2.1b.fw
bnx2/bnx2-rv2p-06-6.0.15.fw
bnx2/bnx2-rv2p-09-6.0.17.fw
```

```
intel/ibt-12-16.sfi
intel/ice/ddp/ice.pkg                                missing
ipw2100-1.3-i.fw
ipw2100-1.3-p.fw
ipw2100-1.3.fw
ipw2200-bss.fw
ipw2200-ibss.fw
ipw2200-sniffer.fw
isci/isci_firmware.bin
isdbt_nova_12mhz.inp
isdbt_nova_12mhz_b0.inp
isdbt_pele.inp                                       missing
isdbt_rio.inp
isight.fw                                            missing
isl3877                                              missing
isl3886                                              missing
isl3886pci                                           missing
isl3886usb                                           missing
isl3887usb                                           missing
isl3890                                              missing
iwlwifi-100-5.ucode
iwlwifi-1000-5.ucode
iwlwifi-105-6.ucode
iwlwifi-135-6.ucode
iwlwifi-2000-6.ucode
iwlwifi-2030-6.ucode
iwlwifi-3160-17.ucode
iwlwifi-3168-29.ucode
iwlwifi-3945-2.ucode
iwlwifi-4965-2.ucode
iwlwifi-5000-5.ucode
iwlwifi-5150-2.ucode
iwlwifi-6000-4.ucode #this one will work for green geek
iwlwifi-6000-6.ucode                                 missing
iwlwifi-6000g2a-6.ucode
iwlwifi-6000g2b-6.ucode
iwlwifi-6050-5.ucode
iwlwifi-7260-17.ucode
iwlwifi-7265-17.ucode
iwlwifi-7265D-29.ucode
iwlwifi-8000C-36.ucode
iwlwifi-8265-36.ucode
iwlwifi-9000-pu-b0-jf-b0-46.ucode
iwlwifi-9260-th-b0-jf-b0-46.ucode
iwlwifi-Qu-a0-hr-a0-50.ucode                         missing
iwlwifi-Qu-a0-jf-b0-50.ucode                         missing
iwlwifi-Qu-b0-jf-b0-50.ucode
iwlwifi-Qu-c0-hr-b0-50.ucode
iwlwifi-QuQnj-a0-hr-a0-50.ucode                      missing
iwlwifi-QuQnj-b0-hr-b0-50.ucode                      missing
iwlwifi-QuQnj-b0-jf-b0-50.ucode                      missing
iwlwifi-QuQnj-f0-hr-a0-50.ucode                      missing
iwlwifi-QuZ-a0-hr-b0-50.ucode
iwlwifi-QuZ-a0-jf-b0-50.ucode
iwlwifi-cc-a0-50.ucode
iwlwifi-so-a0-gf-a0-50.ucode                         missing
iwlwifi-so-a0-hr-b0-50.ucode                         missing
iwlwifi-so-a0-jf-b0-50.ucode                         missing
iwlwifi-ty-a0-gf-a0-50.ucode                         missing
kaweth/new_code.bin
kaweth/new_code_fix.bin
kaweth/trigger_code.bin
kaweth/trigger_code_fix.bin
```

**Comment by 01micko** [comment]
..and the whole file 
[firmware.lst.tar.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6643316/firmware.lst.tar.gz)

**Comment by dimkr** [comment]
Thanks @01micko, I've prepared https://github.com/puppylinux-woof-CE/woof-CE/compare/testing...dimkr:bugfix/iwlwifi-firmware-versioning?expand=1 as well, but this probably was a waste of time.

**Comment by 01micko** [comment]
Yeah I'm making a branch `fw-fixes` (or similar) and it will have several commits as I will make the extra firmware optional, plus I have to find the right licences for the b43 to include. The user has to be made aware so a short splash at the quicksetup stage (if those fw are included) should be enough (legal reasons).

**Pull request closed without merging**
