### PR TITLE
removepreview.sh: Added layer evaluation

### PR DESCRIPTION
**Pull request by rizalmart**
Upon removal of packages. Evaluate the layered root filesystem for non PUPMODE 2 setup

### CODE REVIEW

**Comment by sc0ttj** [comment]
Why? What does this fix? What was the problem before this change?

(Should I include it in Pkg?)

**Comment by rizalmart** [comment]
I was playing with lxpupsc. I tried to remove a whiteout file of a builtin file on /initrd/pup_rw the builtin file doesn't show on top layer immediately. Unless issue with that command. I noticed also that udba=reval was called upon adding a package where the package contents go to save file instead of /initrd/pup_rw. So its better to call udba=reval after package removal to refresh the top layer in case it is not yet updated

**Comment by 01micko** [comment]
@sc0ttj does that answer your question?

**Comment by sc0ttj** [comment]
I think so... so this fixes the list of packages to be removed?

If so, sounds like we need it in PPM I guess (and prob in Pkg too).

**Pull request merged**
