### PR TITLE
Add palemoon petbuild.

### PR DESCRIPTION
**Pull request by lakshayrohila**
This PR tries to add palemoon petbuild.

### CODE REVIEW

**Review by dimkr — APPROVED** [review]
Looks fine to me. I'd add this to PETBUILDS (in _00build.conf) in focal64 and jammy64, then drop the old Pale Moon .pet package and Netsurf, respectively.

**Comment by dimkr** [comment]
Oh, another thing: consider adding pinstall.sh that sets defaultbrowser. I think it's safe to assume those who use this petbuild want Pale Moon as the default (and only) browser.

**Comment by lakshayrohila** [comment]
> Looks fine to me. I'd add this to PETBUILDS (in _00build.conf) in focal64 and jammy64, then drop the old Pale Moon .pet package and Netsurf, respectively.

Note that to make this work in jammy64, you'd need to add package `libdbus-glib` as well. I was just taking a look at my build of jammy64.

I also wanted to ask if `pet.specs` is fine. I don't know its syntax. Copied a bit of part from `claws-mail` petbuild.

**Comment by lakshayrohila** [comment]
> Oh, another thing: consider adding pinstall.sh that sets defaultbrowser. I think it's safe to assume those who use this petbuild want Pale Moon as the default (and only) browser.

Will do it. Thanks!

**Comment by dimkr** [comment]
> Note that to make this work in jammy64, you'd need to add package `libdbus-glib` as well. I was just taking a look at my build of jammy64.

Makes sense, it's a dependency of Firefox as well and Pale Moon is a fork of old Firefox.

> I also wanted to ask if `pet.specs` is fine. I don't know its syntax. Copied a bit of part from `claws-mail` petbuild.

Looks fine to me.

**Comment by dimkr** [comment]
Why like this?

**Comment by lakshayrohila** [comment]
@dimkr I renamed the branch. Hence the PR closed. Here is a new one- https://github.com/puppylinux-woof-CE/woof-CE/pull/3637.

**Pull request closed without merging**
