### PR TITLE
New version

### PR DESCRIPTION
**Pull request by peabee**
Test build done - seems OK. Uploaded to ibiblio - should maybe be relocated to github??

### CODE REVIEW

**Comment by 01micko** [comment]
New version of what?

**Comment by peabee** [comment]
INITRD_STATIC='initrd_progs-20210323-static.tar.xz'

**Comment by 01micko** [comment]
Did you build the binaries? Were they tested on all 4 target arches? (arm, aarch64, i?86, x86_64)

**Comment by peabee** [comment]
wdlkmpx built the binaries
i?86, x86_64 tested
others should test arm, aarch64

**Comment by 01micko** [comment]
Ok, I did test in arm, tested a few busybox applets - mainly `fdisk` (it's critical that syntax is similar to old version in initrd.gz) and `dc` which has troubled us before. Both OK. What did annoy me is that at some point @wdlkmpx disabled the `vi` applet and since we don't ship `mp` or `nano` (static in initrd bloated) we have no editor apart from `sed` or `awk`, not friendly at all. Yes I know this is a bit of a developer feature but I think it's necessary.

Anyway, I rebuilt the whole 4 with `vi` busybox enabled. It works in 64 and arm. Tested making a file and editing a file and saving it.

I also tested arm `ntfs-3g` and it mounts fine rw.
Tested arm fsck.fat working fine. 

Do you want to add this updated busybox version with vi enabled? I can upload if you want. You can issue a new PR with a descriptive title :-)

**Comment by 01micko** [comment]
Uploaded to my site

http://01micko.com/initrd_tarballs/initrd_progs-20210401-static.tar.xz
http://01micko.com/initrd_tarballs/initrd_progs-20210401-static.tar.xz.md5.txt

**Comment by 01micko** [comment]
PS: if you do I'll commit changes to `initrd_progs`. Not a great deal, mainly the busybox DOTconfig

**Pull request closed without merging**
