### PR TITLE
Update 3builddistro-Z: update main cache files

### PR DESCRIPTION
**Pull request by rizalmart**
update the cache files for the last time before proceeding to create the main sfs

### CODE REVIEW

**Comment by peabee** [comment]
This will slow things down? Why is it needed? I have seen no problems with the existing process??

**Comment by rizalmart** [comment]
To make puppy more reliable. It does not slow things down. gdk-pixbuf, glib, gio, pango, gtkim, iconv, mime, xdg file association requires cache file unless it will not work properly.

**Comment by peabee** [comment]
When has it been unreliable???? All needed cache files have been created previously haven't they?

**Comment by rizalmart** [comment]
This process is simply just to make sure that those cache files was created properly. All modules or files must be well defined in the system cache file.

**Comment by ghost** [comment]
I try update-cache.sh in slacko 14.0 and this was the output (maybe my puppy is too old? :older_woman: )

Screenshot(1)

The first time I ran it the script took about 20 seconds to end, the 2nd time about 5 seconds.

**Comment by ghost** [comment]
Apparently mine use a different name instead

Screenshot(2)

I guess something like this might work

Screenshot(4)

And similar for pango,  but I don't know if this does the same thing or not (just guessing) :laughing:

**Comment by wdlkmpx** [comment]
This guy keeps adding code without reading or understanding the build scripts

**Comment by rizalmart** [comment]
Before I deploy the code here on github. I already tested that code.

**Comment by wdlkmpx** [comment]
This introduces duplicate code, i don't have enough time to fix everything for you

**Comment by wdlkmpx** [comment]
Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/abbf7e4f2a8a45f83dd613d17002f953a17f7cd3 merges this PR.

It also adds the suggested fixes for slacko 14.0, ninaholic might want to build a slacko 14.0 and see if everything's ok.

I see i was being a bit rude, i'm hearing a strong hissing sound in my right ear, they call it Tinnitus, there's a python 3.7 in my head. that's my excuse. sorry.

**Comment by rizalmart** [comment]
if it is a duplicate code can you tell me what part of code it is? So I will try to improve the existing one

**Comment by ghost** [comment]
Thanks wdlkmpx. Looks like it worked :+1: 

Screenshot

@rizalmart if you want me to build an iso for you with latest woof-ce so you can test if all the cache stuff is set up properly in it, just let know which distro and version to build :octocat:

**Comment by Butterfly** [comment]
> if it is a duplicate code can you tell me what part of code it is? So I will try to improve the existing one

Hi, @rizalmart, it sounds like it's all good. My interpretation was that it had something to do with hissing snakes. :snake: :snake:

Is now merged per [above comment](https://github.com/puppylinux-woof-CE/woof-CE/pull/1489#issuecomment-510967797) :+1: :+1: :+1:

**Comment by Butterfly** [comment]
> @rizalmart if you want me to build an iso for you with latest woof-ce so you can test if all the cache stuff is set up properly in it, just let know which distro and version to build :octocat:

Cool. Since you opened the barn door (about obtaining a base copy).. Are you building by `git`'ing what's here on Github, or are you pulling from somewhere else?

I've never had success building *anything* from Github, but I'm fixin' to try yet again. The issue has been about dialup not allowing the `yarn`/`npm` process to finish without breaking up and falling apart.

I `git`'ed the **woof-CE** files last week but plan on repeating to have as fresh a copy as possible. If I *FINALLY* get it built once the latest is downloaded, is that enough to keep up with what you all are doing? Or are you all getting your working copies from something else? This has been a *MAJOR* lingering question all this time I've been following Puppy..

#ThankYou in advance! :smile:

**Comment by wdlkmpx** [comment]
@rizalmart  Ok. 3builddistro-Z calls `chroot ....rc.update w` only when the host and target architectures are the same.

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/3builddistro-Z#L583

rc.update also had duplicate code, the commit that merged this PR unified extended_update & update_cache_files().. something you added.

Looking at some PRs, it seems that you were testing in some other distro, and then added a fix to make it woofce compliant or something.

Woofce supports several architectures, several distro versions, and (and 2 build systems and) is shifting to improve support for a cli-only build... the distro to look for interesting changes is fatdog, woofce is implementing some changes fatdog implemented like 8 years ago, although with different code, but you get the idea. When the agent gives some advice you get signal.

@Butterfly 
https://github.com/puppylinux-woof-CE/woof-CE/wiki/Builds

Unfortunately it's currently empty, i also deleted the old raspup build. I'll compile the latest kernel for the raspis 0 1 2 3 and produce a new build.. probably

However as @ninaholic is willing to build isos, i can add those isos to that page.. links can be posted here or in https://github.com/wdlkmpx/w/issues (some privacy).. i'll update links in the wiki when a new build is produced.. and i'm notified.. unless it's possible to give write access to the wiki, i don't know

So https://github.com/puppylinux-woof-CE/woof-CE/wiki/Builds
will have links to recent builds.. the builds may be updated anytime, and the expiration date is 15/30/60/90 days, depends on the git repo activity... very minimal activity: 90 days.

**Pull request closed without merging**
