### PR TITLE
fixes for perl_tiny & file templates

### PR DESCRIPTION
**Pull request by mrfricks**
added extra perl modules to perl_tiny template ...needed by pplog

'file' template altered , needed if you are using file & libmagic from ubuntu repos

### CODE REVIEW

**Comment by mavrothal** [comment]
Would it be a problem if building from another distro?

**Comment by mrfricks** [comment]
concerning perl_tiny, i had a look at  slacko & dpup iso's and slacko has overloading.pm & utf8.pm,  dpup has base.pm & utf8.pm so evidently they are needed.

with 'file'  with tahr64  i needed to use the version from the ubuntu repos.  most pups use a .pet but the option is in DISTRO_PKGS_SPECS to use the one from the repos.  the devuan build uses the repo packages and so would have the /usr/share/bug folder stripped  this might not matter,  but the  /usr/share/misc/magic symlink that is also stripped probably would matter,

**Comment by mavrothal** [comment]
BTW, you should be able to pull yourself ;)

**Comment by 01micko** [comment]
@mrfricks did you get those 2 perl libs I mentioned in the tahr64 thread?
libintl-perl and one other.

**Comment by mrfricks** [comment]
01micko  .... thanks, almost missed that ...added them to the devx

**Pull request merged**
