### PR TITLE
sns: Set key entry visibility to 'false'.

### PR DESCRIPTION
**Pull request by Mr-Kumar-Abhishek**
Erm.. minor patch for SNS to hide the characters when user enters the network key. 

I was having problems of people snooping over my network passwords while logging in, please accept. :pray:

### CODE REVIEW

**Comment by ninaholic** [comment]
I always thought that was strange too. Your fix is working for me :)

**Comment by Mr-Kumar-Abhishek** [comment]
Thank you for testing it @ninaholic . I just got into this. One of my friend told me to look into [*gtkdialog*](https://code.google.com/archive/p/gtkdialog/) repository to fix this. I have tested it indirectly with my machine (running on puppy Linux). It could have a better user experience too I suppose, such as having a Checkbox to show and hide passwords. But I don't have much Idea on how to properly test this platform. Any pointers would help. And I will try to add those features too. ( It has a bit of learning curve, so am learning :smile: ) I presume for now this would acceptable.

**Comment by wdlkmpx** [comment]
I could do that, I was editing Network Wizard and added a checkbox, I
guess I can copy and paste that code in SNS

**Comment by Mr-Kumar-Abhishek** [comment]
Go for it then.

**Comment by Mr-Kumar-Abhishek** [comment]
@wdlkmpx if you decide to copy paste, I will close this PR as it has no use.  :stuck_out_tongue_closed_eyes: ~

**Comment by wdlkmpx** [comment]
Don't close it yet. I wonder where the checkbox should go. Looking at
the docs I can't find a way to switch states (masked, unmasked) in the
same dialog, it can't be done I guess.

it should go in a previous dialog asking to confirm whether you want a
masked or masked text box, then that setting would be saved
permanently. Or in the main dialog add a button "Called settings", the
add a check box to the dialog "Show masked passwords" or something
like that (other settings could be added in the future).

So... what do you think is the best approach?

**Comment by Mr-Kumar-Abhishek** [comment]
:neckbeard:  I was pondering over the exact same thing, before I made the pull request. I don't know where the docs are so, I was learning by reading [woof-CE's code](https://github.com/puppylinux-woof-CE/woof-CE). You could read [eventmanager's](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/eventmanager) script, that is what I would have done. :innocent:

**Comment by wdlkmpx** [comment]
Unless there is a trick to do that, it can't be done in the same dialog, this "advanced example" shows everything you can do with a text entry:

https://searchcode.com/codesearch/raw/11892037/

**Comment by Mr-Kumar-Abhishek** [comment]
Thank  you for the example :smile: ! it helps a lot ! hmm... I suppose it can't be done, and conjuring up this trick would require some thought if it could be done. 

Meanwhile.. this is a temporary solution against people looking over you network passwords till some other settings could be added in future. In general passwords shouldn't be shown while typing, yes ?

(in between got some [docs](http://xpt.sourceforge.net/techdocs/language/gtkdialog/gtkde02-GtkdialogExamples/single/) to read.)

**Comment by wdlkmpx** [comment]
Yes I agree, but i can't do anything. So what do you think, should I
add a button in the main dialog or a small confimation dialog before
the wifi network list is displayed?

**Comment by 01micko** [comment]
> Looking at
the docs I can't find a way to switch states (masked, unmasked) in the
same dialog, it can't be done I guess.

Take a look at the frisbee code; there is checkbox in the ssid password dialog that toggles hidden state.

**Comment by JakeSFR** [comment]
> a Checkbox to show and hide passwords

Hmm, what a coincidence - a few days ago I was wondering how to implement such a thing in Gtkdialog and found a (tricky, as usual) way.
Btw, if I'm not mistaken, Frisbee uses Xdialog for this, where this feature is built-in; it's not so trivial in Gtkdialog, though. ;)

Anyway, here's an example, hope it will be helpful:

```
#!/bin/sh

export MAIN='
<window>
  <vbox>
  
    <notebook show-tabs="false" show-border="false" visible="false">
      
      <vbox>
        <entry caps-lock-warning="true" visibility="false">
          <variable>PASS_SHOWN</variable>
          <input>echo "$PASS_HIDDEN"</input>
          <action>refresh:PASS_HIDDEN</action>
        </entry>
      </vbox>
      
      <vbox>
        <entry caps-lock-warning="true" visibility="true">
          <variable>PASS_HIDDEN</variable>
          <input>echo "$PASS_SHOWN"</input>
          <action>refresh:PASS_SHOWN</action>
        </entry>
      </vbox>
      
      <variable>SWITCH</variable>
      <input>echo $(( (SWITCH+1) &1 ))</input>
    </notebook>
    
    <checkbox>
      <label>Show password</label>
      <action>refresh:SWITCH</action>
    </checkbox>
    
    <button ok></button>
    
  </vbox>
  
  <action signal="map-event">show:SWITCH</action>
  <action signal="map-event">grabfocus:PASS_HIDDEN</action>
</window>'

gtkdialog -p MAIN
```

In the above example I set 'visible' state of 'notebook' widget to "false" at start, because without it the window contains an empty, useless piece space at the bottom, what looks ugly (just set it to "true" to see what I mean).
It might be not necessary in SNS, though, where there are other widgets around, in which case both 'action' lines at the very bottom should be thrown away, too.

Cheers!

**Comment by 01micko** [comment]
> Btw, if I'm not mistaken, Frisbee uses Xdialog for this

:doh: !

You're quite right!

Your solution works fine here @JakeSFR

**Comment by Mr-Kumar-Abhishek** [comment]
Well, I have tested it,  sadly this seems to.. erm .. I suppose cause some 'anomaly' ?
```
           <hbox space-expand="true" space-fill="true">
               <vbox>
                   <text space-expand="false" space-fill="false"><label>'$(gettext 'Key:')'</label></text>
               </vbox>
               <vbox>
                 <notebook show-tabs="false" show-border="false" visible="true">
                   <vbox>
                     <entry space-expand="true" space-fill="true" visibility="false">
                       <variable>BOX_KEY</variable>
                       <input> echo $BOX_KEY_SHOWN </input>
                       <action signal="activate" type="activate">BTN_CONNECT</action>
                       <action>refresh:BOX_KEY_SHOWN</action>
                     </entry>
                   </vbox>
                   <vbox>
                     <entry space-expand="true" space-fill="true" visibility="true">
                       <variable>BOX_KEY_SHOWN</variable>
                       <input> echo $BOX_KEY </input>
                       <action signal="activate" type="action">BTN_CONNECT</action>
                       <action>refresh:BOX_KEY</action>
                     </entry>
                   </vbox>
                   <variable>SWITCH</variable>
                   <input>echo $(( (SWITCH+1) &1 ))</input>
                 </notebook>
                 <checkbox>
                   <label>Show password</label>
                   <action>refresh:SWITCH</action>
                 </checkbox>
               </vbox>
           </hbox>
```
after these changes, the profile list gets messed up..

capture3103

Check the last two entries , I have tested the script tahrpup. I must be stepping over something here.. @wdlkmpx have you checked this out ??

**Comment by JakeSFR** [comment]
> Your solution works fine here @JakeSFR

Thanks for confirmation.


> after these changes, the profile list gets messed up..

Are you sure it has something to do with those changes?
Long ago I fixed similar issue for 'Network' and 'Security' fields: https://github.com/puppylinux-woof-CE/woof-CE/commit/6974d3a3399dddb8837de2c590101cb3ac95e6e0
Basically it happens when one (or more) of bottom fields are empty ("logmetomeshnet" on the scrsht) - alignment goes nuts then...
Can you check again with unaltered version, but the same network configuration?

Also, try to add this (2nd line) in 'sns':
```
MAC_P="`echo -n "$ONECONNECTION" | cut -f 6 -d '|'`"
[ "$MAC_P" ] || MAC_P=" " # to fix alignment if MAC_P is empty
```

**Comment by Mr-Kumar-Abhishek** [comment]
Hi, I have checked with the unaltered version at this commit 8ed2187, with same network configuration. Profile lists were fine.

capture30309

"logmetomesnet" is actually the password for the network which shouldn't come up in the profile list in the first place. 

I would try to fix the alignment and see how it goes.

**Comment by Mr-Kumar-Abhishek** [comment]
Alright, so got some help from someone .. so the`etc/simple_network_setup/connections` stores all the profile information... hmm.. and `ssid` and `psk` in directory `etc/simple_network_setup`

**Comment by Mr-Kumar-Abhishek** [comment]
I see now..so the key was recorded twice in `etc/simple_network_setup/connections` :smile:

**Comment by 01micko** [comment]
looks like #774 trumps this one.

Thanks for your work @Mr-Kumar-Abhishek ! :+1:

**Pull request closed without merging**
