### PR TITLE
rox: mimetypes for defaultaudioplayer & defaultmediaplayer

### PR DESCRIPTION
**Pull request by wdlkmpx**
Nowadays audio players like deadbeef can play almost any audio formats
Nowadays video players like mplayer can play almost any video formats

This will make everything easier, I bet many users add file associations manually when they try to play a specific audio or video format.

This will (probably) not affect anything, as users may have their own files to overwrite these ones, that's what I've always done: add and add file associations and then store them somewhere to apply them again.

### CODE REVIEW

**Comment by wdlkmpx** [comment]
I think the correct description for this and other commits is "mime associations"

**Comment by mavrothal** [comment]
BTW "woof members", as you might have noticed I'm reluctant to pull anything that is not a "bug fix", just before tahr and libre are released and slacko may get a bugfix point release.
However, if you think that something must be pulled before even if is not in the above category, do pull. I have no problem what so ever with that. Puppy does not have "freeze" period :wink:

**Comment by 01micko** [comment]
>BTW "woof members", as you might have noticed I'm reluctant to pull anything that is not a "bug fix", just before tahr and libre are released and slacko may get a bugfix point release.
However, if you think that something must be pulled before even if is not in the above category, do pull. I have no problem what so ever with that. Puppy does not have "freeze" period :wink:

:+1:

**Comment by zigbert** [comment]
>BTW "woof members", as you might have noticed I'm reluctant to pull anything that is not a "bug fix", just before tahr and libre are released and slacko may get a bugfix point release.
However, if you think that something must be pulled before even if is not in the above category, do pull. I have no problem what so ever with that. Puppy does not have "freeze" period :wink:

:+1:

**Comment by mavrothal** [comment]
OK we all agree. Now what? :open_mouth:

**Comment by wdlkmpx** [comment]
Maybe I should close these "defaultapps" pull requests? The files are here

http://murga-linux.com/puppy/viewtopic.php?mode=attach&id=92792

Maybe most of them should go elsewhere, perhaps packages-templates

**Comment by mavrothal** [comment]
I do not think you need to close it unless you think is not valid or in a valid place.
It just may stay open for some time till we get into "testing mode" again

**Comment by zigbert** [comment]
Mime handling seems like a mess. I see 3 different approaches in Woof
- usr/local/bin/defaulthandler
- usr/share/applications/defaults.list
- root/Choices/MIME-types/

Can anyone explain what/when to use?

**Comment by 01micko** [comment]
>Mime handling seems like a mess. I see 3 different approaches in Woof

It's not easy. We have to update the shared mime data too (see /usr/share/mime* in your running distro). GTK, Firefox (and others), file managers and many other programs depend on it.

I think we are still at 0.7 for the mime database? I attempted to update it for slacko64 but had too many issues. This is something that has to be done on a case for case (distro for distro) basis. probably needs a petbuild for `shared-mime-info`.

**Comment by wdlkmpx** [comment]
These files contain ROX mime associations for old and updated
mimetypes. When dealing with this a person might get bored, but many
working for the same goal make it easy.

Upgrading is not easy, but it can be done easily.

Here are mime associations for pcmanfm, etc. Ready to be pasted here:

	/root/.local/share/applications/mimeapps.list
	[Default Applications]

or here

	/usr/share/applications/defaults.list
	[Default Applications]

-

	# grep defaultaudio * | sed -e 's|:.*||' -e 's|_|/|' -e
's|$|=defaultaudioplayer.desktop|'
	audio/aac=defaultaudioplayer.desktop
	audio/ac3=defaultaudioplayer.desktop
	audio/amr=defaultaudioplayer.desktop
	audio/AMR=defaultaudioplayer.desktop
	audio/amr-wb=defaultaudioplayer.desktop
	audio/AMR-WB=defaultaudioplayer.desktop
	audio/annodex=defaultaudioplayer.desktop
	audio/basic=defaultaudioplayer.desktop
	audio/flac=defaultaudioplayer.desktop
	audio/midi=defaultaudioplayer.desktop
	audio/mp2=defaultaudioplayer.desktop
	audio/mp4=defaultaudioplayer.desktop
	audio/mpeg=defaultaudioplayer.desktop
	audio/ogg=defaultaudioplayer.desktop
	audio/prs.sid=defaultaudioplayer.desktop
	audio/vnd.dts=defaultaudioplayer.desktop
	audio/vnd.dts.hd=defaultaudioplayer.desktop
	audio/vnd.rn-realaudio=defaultaudioplayer.desktop
	audio/webm=defaultaudioplayer.desktop
	audio/x-adpcm=defaultaudioplayer.desktop
	audio/x-aifc=defaultaudioplayer.desktop
	audio/x-aiff=defaultaudioplayer.desktop
	audio/x-aiffc=defaultaudioplayer.desktop
	audio/x-amzxml=defaultaudioplayer.desktop
	audio/x-ape=defaultaudioplayer.desktop
	audio/x-flac=defaultaudioplayer.desktop
	audio/x-flac+ogg=defaultaudioplayer.desktop
	audio/x-gsm=defaultaudioplayer.desktop
	audio/x-iriver-pla=defaultaudioplayer.desktop
	audio/x-it=defaultaudioplayer.desktop
	audio/x-m4b=defaultaudioplayer.desktop
	audio/x-matroska=defaultaudioplayer.desktop
	audio/x-minipsf=defaultaudioplayer.desktop
	audio/x-mo3=defaultaudioplayer.desktop
	audio/x-mod=defaultaudioplayer.desktop
	audio/x-mpegurl=defaultaudioplayer.desktop
	audio/x-ms-asx=defaultaudioplayer.desktop
	audio/x-ms-wma=defaultaudioplayer.desktop
	audio/x-musepack=defaultaudioplayer.desktop
	audio/x-opus+ogg=defaultaudioplayer.desktop
	audio/x-psf=defaultaudioplayer.desktop
	audio/x-psflib=defaultaudioplayer.desktop
	audio/x-riff=defaultaudioplayer.desktop
	audio/x-s3m=defaultaudioplayer.desktop
	audio/x-scpls=defaultaudioplayer.desktop
	audio/x-speex=defaultaudioplayer.desktop
	audio/x-speex+ogg=defaultaudioplayer.desktop
	audio/x-stm=defaultaudioplayer.desktop
	audio/x-tta=defaultaudioplayer.desktop
	audio/x-voc=defaultaudioplayer.desktop
	audio/x-vorbis+ogg=defaultaudioplayer.desktop
	audio/x-wav=defaultaudioplayer.desktop
	audio/x-wavpack=defaultaudioplayer.desktop
	audio/x-wavpack-correction=defaultaudioplayer.desktop
	audio/x-xi=defaultaudioplayer.desktop
	audio/x-xm=defaultaudioplayer.desktop
	audio/x-xmf=defaultaudioplayer.desktop

-

	# grep defaultmediaplayer.desktop * | sed -e 's|:.*||' -e 's|_|/|' -e
's|$|=defaultmediaplayer.desktop|'
	video/3gpp=defaultmediaplayer.desktop
	video/3gpp2=defaultmediaplayer.desktop
	video/annodex=defaultmediaplayer.desktop
	video/dv=defaultmediaplayer.desktop
	video/isivideo=defaultmediaplayer.desktop
	video/mp2t=defaultmediaplayer.desktop
	video/mp4=defaultmediaplayer.desktop
	video/mpeg=defaultmediaplayer.desktop
	video/ogg=defaultmediaplayer.desktop
	video/quicktime=defaultmediaplayer.desktop
	video/vivo=defaultmediaplayer.desktop
	video/vnd.mpegurl=defaultmediaplayer.desktop
	video/vnd.rn-realvideo=defaultmediaplayer.desktop
	video/wavelet=defaultmediaplayer.desktop
	video/webm=defaultmediaplayer.desktop
	video/x-anim=defaultmediaplayer.desktop
	video/x-flic=defaultmediaplayer.desktop
	video/x-flv=defaultmediaplayer.desktop
	video/x-javafx=defaultmediaplayer.desktop
	video/x-matroska=defaultmediaplayer.desktop
	video/x-matroska-3d=defaultmediaplayer.desktop
	video/x-mng=defaultmediaplayer.desktop
	video/x-ms-asf=defaultmediaplayer.desktop
	video/x-msvideo=defaultmediaplayer.desktop
	video/x-ms-wmv=defaultmediaplayer.desktop
	video/x-nsv=defaultmediaplayer.desktop
	video/x-ogm+ogg=defaultmediaplayer.desktop
	video/x-sgi-movie=defaultmediaplayer.desktop
	video/x-theora+ogg=defaultmediaplayer.desktop

-

**Comment by wdlkmpx** [comment]
Well, there is only one way you can make mime associations work, and
it's following what the specs say, in that case defaulthandler should
be associated with as many mimetypes as possible.

Besides, I don't see this anywhere in woof-code:

update-mime-database /usr/share/mime

That line should go somewhere in 3builddistro, you should add that

**Comment by wdlkmpx** [comment]
OK this is how things work:

/usr/share/applications/defaults.list - mime associtaions for pcmanfm and other file managers
/root/Choices

/root/Choices/MIME-types/ - there are used by ROX  and possibly is the fallback of other file managers, but I think it's only used by rox by now.

defaulthandler... that thing shouldn't exist.

Mimetypes are defined by packages (xlm text files), which are placed in /usr/share/mime/packages

With the /usr/share/mime/packages/*.xml files alone is possible to populate /usr/share/mime/* with mimetypes by using:

update-mime-datebase /usr/share/mime

Now, you can create your own mimetypes 'package' and make it work by updating the mime database and adding mime associations for rox, pcmanfm, thunar, etc. I think most  file managers use the same stuff except rox.

When you install a package it sometimes come with /usr/share/mime/packages/package.xml, that does nothing if update-mime-database is not called.

Many extensions are specific to a program, if that program does not come with mimetypes and there's no mime associations either, it just must be used manually, and that is not friendly.

That's why having as many mime associations as possible is
 not bad, because at least it will tell you what specific program is missing when you encounter and audacity project for example, yes audacity not found, and because adding mimetypes is truly something tiring, then any contribution should be accepted.

Perhaps if it's not possible to have as many mime associations as possible in rootfs-skeleton, then place them all packages-templates/rox_filer or something like tthat, besides ROX needs to be forked and the its most annoying bugs be fixed, otherwise I just can't use it.

**Comment by jamesbond3142** [comment]
> Mime handling seems like a mess. I see 3 different approaches in Woof
- /usr/local/bin/defaulthandler
- /usr/share/applications/defaults.list
- /root/Choices/MIME-types/

Don't forget /etc/mailcap and its friends $HOME/.mailcap

> Well, there is only one way you can make mime associations work, and
it's following what the specs say, in that case defaulthandler should
be associated with as many mimetypes as possible.

The problem is that there are multiple competing "standards". The best way forward is to sync all of them so that they behave in the same way.

**Comment by zigbert** [comment]
>in that case defaulthandler should be associated with as many mimetypes as possible.

>defaulthandler... that thing shouldn't exist.

I am trying to follow, but it's hard... :)

**Comment by wdlkmpx** [comment]
zigbert, well you mentioned defaulthandler and I thought you wrote it

These are the places it's used

	woof-code/rootfs-skeleton/usr/sbin/xf86svga336wizard:  defaulthandler file:///usr/share/doc/xf86_svga.txt &
	woof-code/rootfs-skeleton/usr/local/bin/xdg-open:#110115 xdg-open used to be a symlink to defaulthandler.
	woof-code/VCSMETADATA:rootfs-skeleton/usr/local/bin/defaulthandler:777:root:root

note that #110115 xdg-open used to be a symlink to defaulthandler.

That xdg-open script is very wrong, look:

	#!/bin/sh
	#this script created by Jemimah. see: http://murga-linux.com/puppy/viewtopic.php?t=63400&start=150
	#110115 xdg-open used to be a symlink to defaulthandler.

	#!/bin/bash
	case "$1" in 
			'') exit
					;;
			*://*) exec rox -U "$1"
					;;
			*@*.*) exec rox -U "mailto:${1}"
					;;
			*) exec rox "$1"
					;;
	esac

rox does not have a -U switch, I think it's safe to delete that xdg-open

and defaulthandler is assuming some primitive logic

**Comment by jamesbond3142** [comment]
> rox does not have a -U switch, I think it's safe to delete that xdg-open

Which rox version are you using? Because mine definitely has it
```
# rox --help
Usage: ROX-Filer/AppRun [OPTION]... [FILE]...
Open each directory or file listed, or the current working
directory if no arguments are given.

  -b, --border=PANEL	open PANEL as a border panel
  -B, --bottom=PANEL	open PAN as a bottom-edge panel
  -c, --client-id=ID	used for session management
  -d, --dir=DIR		open DIR as directory (not application)
  -D, --close=DIR	close DIR and its subdirectories
  -h, --help		display this help and exit
  -l, --left=PANEL	open PAN as a left-edge panel
  -m, --mime-type=FILE	print MIME type of FILE and exit
  -n, --new		start new copy; for debugging the filer
  -p, --pinboard=PIN	use pinboard PIN as the pinboard
  -r, --right=PANEL	open PAN as a right-edge panel
  -R, --RPC		invoke method call read from stdin
  -s, --show=FILE	open a directory showing FILE
  -S, --rox-session	use default panel and pinboard options, and -n
  -t, --top=PANEL	open PANEL as a top-edge panel
  -u, --user		show user name in each window 
  -U, --url=URL		open file or directory in URI form
  -v, --version		display the version information and exit
  -x, --examine=FILE	FILE has changed - re-examine it

Report bugs to <rox-devel@lists.sourceforge.net>.
Home page (including updated versions): http://rox.sourceforge.net/
```

If you want to follow the standard, then instead of ditching xdg-open, you should keep it, and re-write it not to depend on Rox, because "xdg-open" is actually the standard desktop-agnostic way to launch an application; and perhaps re-direct all the other ad-hoc scripts to use xdg-open instead (after making sure xdg-open works). There is a full version of xdg-open script here: http://portland.freedesktop.org/download/ although I can't tell how well that script will cope with the situation we have in puppy right now.

By the way I'm sure you know the standard-gods hath spoken that that defaults.list is *already deprecated*, the replacement being *mimeapps.list*; though in theory both are still supported (actual support and implementation details such as which one will take precedence if *both* exist depends on the file manager you use). 

So which one again do you want to use? My guess: since you use pcmanfm, your answer will be - whatever pcmanfm supports. And no, I'm not incriminating you for using pcmanfm; I'm just pointing out that previous decisions (e.g. why xdg-open uses Rox) were made because Rox was the *default* file manager; if we want the situation to get better we must ensure that we don't fall into the same trap again and only try to support the file manager that we currently use.

And as I said previously, some serious applications uses /etc/mailcap (you will be surprised to know which ones, but I'll leave it as an exercise :hamster: ).

**Comment by wdlkmpx** [comment]
I actually have installed the original xdg-open. 

Well, in my experiencie a desktop environment comes with tools and stuff to finetune your stuff, but to be honest I have never used such things, my brother who introduced me to LXDE and Arch Linux has made too many changes manually that he considers his design a new distro, even in his ignorance he must be right. A Windows 7 look alike, almost a perfect one.

So, to be honest, I really do not think that cluttering woofce with mime associations for every possible DE or file manager is something bad, because because because when you install a DE it's possible that everything will be overwritten. Or you can just remove 1, 2 or 3 files (.list), then the desktop environment works on its own terms.

In fact, that's really good, so good that when you install just some elements of a desktop environment (such as a FILE MANAGER), everything will still work the same if you have the same mime associations for different standards, then you can you really choose a file manager, and it's good.

Now it's time to look at the icon theme, for it be the same in rox and any other file managers.

**Comment by wdlkmpx** [comment]
I think everything is clear now. This can go into packages-tenplates/rox_filer or where it is now.

I have 3 working combinations here:
- icewm + pcmanfm
- jwm + pcmanfm
- openbox + pcmanfm + lxpanel (no lxde)
- LXDE (lxpup)

The PuppyPin is visible, on top of pcman's desktop.

The more visual and professional (and slow and outdated) being icewm + pcmanfm

I type 'roxfiler' when I want to launch rox, both rox and pcmanfm basically have the same mime assoctiations and use the same icon theme.

All of them are using the Puppy "desktop environment" behind the courtains.

I think there's nothing else to be done here, but in Woof CE.

**Pull request closed without merging**
