### PR TITLE
01mickos fix needed to build 64bit ubuntu pups

### PR DESCRIPTION
**Pull request by mrfricks**
this was discussed here https://github.com/puppylinux-woof-CE/woof-CE/issues/570

### CODE REVIEW

**Comment by mavrothal** [comment]
Noticed that in #594 that your build failed. Is it related to this one or something entirely different? ie do the original templates work fine in 64bit ubuntu or should be modified to get the libs in  /usr/lib/x86_64-linux-gnu?

**Comment by 01micko** [comment]
@mavrothal we are using they symlink in debian/ubuntu builds so /lib64, /usr/lib64 technically shouldn't exist in these builds. It's up to @mrfricks if he wants to go the whole hog and change libdirs to  /usr/lib/x86_64-linux-gnu or /usr/lib/i386-linux-gnu, but I think @dimkr might want some input on that.

**Comment by mavrothal** [comment]
@01micko so do we pull or not?

**Comment by dimkr** [comment]
@01micko I think /lib and /usr/lib should be links to /lib64 and /usr/lib64, respectively, with x864-linux-gnu and i386-linux-gnu as links to .., so stuff like ldconfig doesn't get messed up. Otherwise, many package templates (FIXUPHACK and pinstall.sh stuff) need to be fixed.

**Comment by 01micko** [comment]
Will the idea of this pull request is such that it doesn't need to touch the FIXUPHACKS. No harm in having the {/usr}/lib64 link though.

I vote pull it!

**Comment by 01micko** [comment]
And by the way, I prefer not to have lib64 links for slacko purposes.

For best compat with upstream it would be better if they are real directories, but whatever. I'll adapt to whatever the flow is. :v:

**Comment by mavrothal** [comment]
a) You can pull too ;)
b) why not get a 'case' statement and change dirs according to the $binarycompat instead of links and horseshoe'ing?

**Comment by 01micko** [comment]
That doesn't fix the hard coded templates though.

For now I'll go with a)

**Comment by mavrothal** [comment]
> That doesn't fix the hard coded templates though.

But couldn't the ```case``` call a function to ```sed``` through them as needed?

**Comment by peabee** [comment]
I believe that there may be problems with sfs-load which try to
install contents into lib64 if it is a link..... 

For instance the
Chromium64 sfs will not install without amendment onto Tahrpup64 which
has lib64 as a link 

Cheers 

peebee 

On 08/10/2015 9:16, Mick Amadio
wrote: 

> And by the way, I prefer not to have lib64 links for slacko
purposes. 
> 
> For best compat with upstream it would be better if they
are real directories, but whatever. I'll adapt to whatever the flow is.

> 
> --
> Reply to this email directly or view it on GitHub [1].

--

PB.............
 

Links:
------
[1]
https://github.com/puppylinux-woof-CE/woof-CE/pull/593#issuecomment-146452758

**Pull request merged**
