### PR TITLE
Remove pmirror if rsync is missing

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by zigbert** [comment]
pMirror is depending on mirdir - not rsync

**Comment by dimkr** [comment]
> pMirror is depending on mirdir - not rsync

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/pmirror#L11
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/pmirror#L140

@zigbert Please correct me if I'm wrong

**Comment by zigbert** [comment]
Whot!? - This is not the pMirror I made...
History log explains it... rewritten by wdlkmpx in 2019.
Maybe it should have another name - it is actually another app... cloned gui - different backend
But... who cares...

**Comment by CollaboratorGCM** [comment]
In addition, isn't "rsync" a part of the standard PUP command set? Why would it be missing. That's almost like "cp" or a similar command is missing???

Merely a comment.

**Comment by dimkr** [comment]
> In addition, isn't "rsync" a part of the standard PUP command set?

I don't know what "PUP" means, but I rarely use rsync and prefer to be able to leave it out.

**Pull request merged**
