### PR TITLE
include radeon_firmware

### PR DESCRIPTION
**Pull request by Linux-is-king**
include radeon_firmware, it take up very little space and enables amd gpus to work very well !

### CODE REVIEW

**Review by lakshayrohila — APPROVED** [review]
I have no issues. Maybe @dimkr?

**Comment by lakshayrohila** [comment]
@Linux-is-king, please also build jammy64 and check whether everything works fine with the changes.

I have approval for the intended idea.

**Comment by dimkr** [comment]
As far as I understand this firmware should be already present in fdrv. If not, this is a probably a bug in kernel-kit/firmware_picker.sh.

Adding radeon_firmware is not a good solution because this is an old .pet package uploaded by somebody - maybe it will work for some hardware, but not for new hardware. And it will collide with fdrv and Ubuntu firmware packages.

Which firmware files are missing? I can add it to fdrv.

EDIT: double-checked. All firmware files in the Fossapup radeon_firmware package are present in my fdrv.

EDIT: triple-checked, this time with fdrv from jammy64 and radeon_firmware-120829.pet. fdrv already includes all files in the .pet package plus more, and it's up-to-date.

```
+lib/firmware/licences/LICENSE.radeon
 lib/firmware/radeon
+lib/firmware/radeon/ARUBA_me.bin
+lib/firmware/radeon/ARUBA_pfp.bin
+lib/firmware/radeon/ARUBA_rlc.bin
+lib/firmware/radeon/banks_k_2_smc.bin
 lib/firmware/radeon/BARTS_mc.bin
 lib/firmware/radeon/BARTS_me.bin
 lib/firmware/radeon/BARTS_pfp.bin
+lib/firmware/radeon/BARTS_smc.bin
+lib/firmware/radeon/bonaire_ce.bin
+lib/firmware/radeon/BONAIRE_ce.bin
+lib/firmware/radeon/bonaire_k_smc.bin
+lib/firmware/radeon/BONAIRE_mc2.bin
+lib/firmware/radeon/bonaire_mc.bin
+lib/firmware/radeon/BONAIRE_mc.bin
+lib/firmware/radeon/bonaire_me.bin
+lib/firmware/radeon/BONAIRE_me.bin
+lib/firmware/radeon/bonaire_mec.bin
+lib/firmware/radeon/BONAIRE_mec.bin
+lib/firmware/radeon/bonaire_pfp.bin
+lib/firmware/radeon/BONAIRE_pfp.bin
+lib/firmware/radeon/bonaire_rlc.bin
+lib/firmware/radeon/BONAIRE_rlc.bin
+lib/firmware/radeon/bonaire_sdma.bin
+lib/firmware/radeon/BONAIRE_sdma.bin
+lib/firmware/radeon/bonaire_smc.bin
+lib/firmware/radeon/BONAIRE_smc.bin
+lib/firmware/radeon/bonaire_uvd.bin
+lib/firmware/radeon/BONAIRE_uvd.bin
+lib/firmware/radeon/BONAIRE_vce.bin
 lib/firmware/radeon/BTC_rlc.bin
 lib/firmware/radeon/CAICOS_mc.bin
 lib/firmware/radeon/CAICOS_me.bin
 lib/firmware/radeon/CAICOS_pfp.bin
+lib/firmware/radeon/CAICOS_smc.bin
 lib/firmware/radeon/CAYMAN_mc.bin
 lib/firmware/radeon/CAYMAN_me.bin
 lib/firmware/radeon/CAYMAN_pfp.bin
 lib/firmware/radeon/CAYMAN_rlc.bin
+lib/firmware/radeon/CAYMAN_smc.bin
 lib/firmware/radeon/CEDAR_me.bin
 lib/firmware/radeon/CEDAR_pfp.bin
 lib/firmware/radeon/CEDAR_rlc.bin
+lib/firmware/radeon/CEDAR_smc.bin
 lib/firmware/radeon/CYPRESS_me.bin
 lib/firmware/radeon/CYPRESS_pfp.bin
 lib/firmware/radeon/CYPRESS_rlc.bin
+lib/firmware/radeon/CYPRESS_smc.bin
+lib/firmware/radeon/CYPRESS_uvd.bin
+lib/firmware/radeon/hainan_ce.bin
+lib/firmware/radeon/HAINAN_ce.bin
+lib/firmware/radeon/hainan_k_smc.bin
+lib/firmware/radeon/HAINAN_mc2.bin
+lib/firmware/radeon/hainan_mc.bin
+lib/firmware/radeon/HAINAN_mc.bin
+lib/firmware/radeon/hainan_me.bin
+lib/firmware/radeon/HAINAN_me.bin
+lib/firmware/radeon/hainan_pfp.bin
+lib/firmware/radeon/HAINAN_pfp.bin
+lib/firmware/radeon/hainan_rlc.bin
+lib/firmware/radeon/HAINAN_rlc.bin
+lib/firmware/radeon/hainan_smc.bin
+lib/firmware/radeon/HAINAN_smc.bin
+lib/firmware/radeon/hawaii_ce.bin
+lib/firmware/radeon/HAWAII_ce.bin
+lib/firmware/radeon/hawaii_k_smc.bin
+lib/firmware/radeon/HAWAII_mc2.bin
+lib/firmware/radeon/hawaii_mc.bin
+lib/firmware/radeon/HAWAII_mc.bin
+lib/firmware/radeon/hawaii_me.bin
+lib/firmware/radeon/HAWAII_me.bin
+lib/firmware/radeon/hawaii_mec.bin
+lib/firmware/radeon/HAWAII_mec.bin
+lib/firmware/radeon/hawaii_pfp.bin
+lib/firmware/radeon/HAWAII_pfp.bin
+lib/firmware/radeon/hawaii_rlc.bin
+lib/firmware/radeon/HAWAII_rlc.bin
+lib/firmware/radeon/hawaii_sdma.bin
+lib/firmware/radeon/HAWAII_sdma.bin
+lib/firmware/radeon/hawaii_smc.bin
+lib/firmware/radeon/HAWAII_smc.bin
 lib/firmware/radeon/JUNIPER_me.bin
 lib/firmware/radeon/JUNIPER_pfp.bin
 lib/firmware/radeon/JUNIPER_rlc.bin
-lib/firmware/radeon/LICENSE.radeon
+lib/firmware/radeon/JUNIPER_smc.bin
+lib/firmware/radeon/kabini_ce.bin
+lib/firmware/radeon/KABINI_ce.bin
+lib/firmware/radeon/kabini_me.bin
+lib/firmware/radeon/KABINI_me.bin
+lib/firmware/radeon/kabini_mec.bin
+lib/firmware/radeon/KABINI_mec.bin
+lib/firmware/radeon/kabini_pfp.bin
+lib/firmware/radeon/KABINI_pfp.bin
+lib/firmware/radeon/kabini_rlc.bin
+lib/firmware/radeon/KABINI_rlc.bin
+lib/firmware/radeon/kabini_sdma.bin
+lib/firmware/radeon/KABINI_sdma.bin
+lib/firmware/radeon/kaveri_ce.bin
+lib/firmware/radeon/KAVERI_ce.bin
+lib/firmware/radeon/kaveri_me.bin
+lib/firmware/radeon/KAVERI_me.bin
+lib/firmware/radeon/kaveri_mec2.bin
+lib/firmware/radeon/kaveri_mec.bin
+lib/firmware/radeon/KAVERI_mec.bin
+lib/firmware/radeon/kaveri_pfp.bin
+lib/firmware/radeon/KAVERI_pfp.bin
+lib/firmware/radeon/kaveri_rlc.bin
+lib/firmware/radeon/KAVERI_rlc.bin
+lib/firmware/radeon/kaveri_sdma.bin
+lib/firmware/radeon/KAVERI_sdma.bin
+lib/firmware/radeon/mullins_ce.bin
+lib/firmware/radeon/MULLINS_ce.bin
+lib/firmware/radeon/mullins_me.bin
+lib/firmware/radeon/MULLINS_me.bin
+lib/firmware/radeon/mullins_mec.bin
+lib/firmware/radeon/MULLINS_mec.bin
+lib/firmware/radeon/mullins_pfp.bin
+lib/firmware/radeon/MULLINS_pfp.bin
+lib/firmware/radeon/mullins_rlc.bin
+lib/firmware/radeon/MULLINS_rlc.bin
+lib/firmware/radeon/mullins_sdma.bin
+lib/firmware/radeon/MULLINS_sdma.bin
+lib/firmware/radeon/oland_ce.bin
+lib/firmware/radeon/OLAND_ce.bin
+lib/firmware/radeon/oland_k_smc.bin
+lib/firmware/radeon/OLAND_mc2.bin
+lib/firmware/radeon/oland_mc.bin
+lib/firmware/radeon/OLAND_mc.bin
+lib/firmware/radeon/oland_me.bin
+lib/firmware/radeon/OLAND_me.bin
+lib/firmware/radeon/oland_pfp.bin
+lib/firmware/radeon/OLAND_pfp.bin
+lib/firmware/radeon/oland_rlc.bin
+lib/firmware/radeon/OLAND_rlc.bin
+lib/firmware/radeon/oland_smc.bin
+lib/firmware/radeon/OLAND_smc.bin
 lib/firmware/radeon/PALM_me.bin
 lib/firmware/radeon/PALM_pfp.bin
+lib/firmware/radeon/pitcairn_ce.bin
+lib/firmware/radeon/PITCAIRN_ce.bin
+lib/firmware/radeon/pitcairn_k_smc.bin
+lib/firmware/radeon/PITCAIRN_mc2.bin
+lib/firmware/radeon/pitcairn_mc.bin
+lib/firmware/radeon/PITCAIRN_mc.bin
+lib/firmware/radeon/pitcairn_me.bin
+lib/firmware/radeon/PITCAIRN_me.bin
+lib/firmware/radeon/pitcairn_pfp.bin
+lib/firmware/radeon/PITCAIRN_pfp.bin
+lib/firmware/radeon/pitcairn_rlc.bin
+lib/firmware/radeon/PITCAIRN_rlc.bin
+lib/firmware/radeon/pitcairn_smc.bin
+lib/firmware/radeon/PITCAIRN_smc.bin
+lib/firmware/radeon/R100_cp.bin
+lib/firmware/radeon/R200_cp.bin
+lib/firmware/radeon/R300_cp.bin
+lib/firmware/radeon/R420_cp.bin
+lib/firmware/radeon/R520_cp.bin
+lib/firmware/radeon/R600_me.bin
+lib/firmware/radeon/R600_pfp.bin
 lib/firmware/radeon/R600_rlc.bin
+lib/firmware/radeon/R600_uvd.bin
 lib/firmware/radeon/R700_rlc.bin
 lib/firmware/radeon/REDWOOD_me.bin
 lib/firmware/radeon/REDWOOD_pfp.bin
 lib/firmware/radeon/REDWOOD_rlc.bin
+lib/firmware/radeon/REDWOOD_smc.bin
+lib/firmware/radeon/RS600_cp.bin
+lib/firmware/radeon/RS690_cp.bin
+lib/firmware/radeon/RS780_me.bin
+lib/firmware/radeon/RS780_pfp.bin
+lib/firmware/radeon/RS780_uvd.bin
+lib/firmware/radeon/RV610_me.bin
+lib/firmware/radeon/RV610_pfp.bin
+lib/firmware/radeon/RV620_me.bin
+lib/firmware/radeon/RV620_pfp.bin
+lib/firmware/radeon/RV630_me.bin
+lib/firmware/radeon/RV630_pfp.bin
+lib/firmware/radeon/RV635_me.bin
+lib/firmware/radeon/RV635_pfp.bin
+lib/firmware/radeon/RV670_me.bin
+lib/firmware/radeon/RV670_pfp.bin
+lib/firmware/radeon/RV710_me.bin
+lib/firmware/radeon/RV710_pfp.bin
+lib/firmware/radeon/RV710_smc.bin
+lib/firmware/radeon/RV710_uvd.bin
+lib/firmware/radeon/RV730_me.bin
+lib/firmware/radeon/RV730_pfp.bin
+lib/firmware/radeon/RV730_smc.bin
+lib/firmware/radeon/RV740_smc.bin
+lib/firmware/radeon/RV770_me.bin
+lib/firmware/radeon/RV770_pfp.bin
+lib/firmware/radeon/RV770_smc.bin
+lib/firmware/radeon/RV770_uvd.bin
+lib/firmware/radeon/si58_mc.bin
+lib/firmware/radeon/SUMO2_me.bin
+lib/firmware/radeon/SUMO2_pfp.bin
+lib/firmware/radeon/SUMO_me.bin
+lib/firmware/radeon/SUMO_pfp.bin
 lib/firmware/radeon/SUMO_rlc.bin
+lib/firmware/radeon/SUMO_uvd.bin
+lib/firmware/radeon/tahiti_ce.bin
+lib/firmware/radeon/TAHITI_ce.bin
+lib/firmware/radeon/TAHITI_mc2.bin
+lib/firmware/radeon/tahiti_mc.bin
+lib/firmware/radeon/TAHITI_mc.bin
+lib/firmware/radeon/tahiti_me.bin
+lib/firmware/radeon/TAHITI_me.bin
+lib/firmware/radeon/tahiti_pfp.bin
+lib/firmware/radeon/TAHITI_pfp.bin
+lib/firmware/radeon/tahiti_rlc.bin
+lib/firmware/radeon/TAHITI_rlc.bin
+lib/firmware/radeon/tahiti_smc.bin
+lib/firmware/radeon/TAHITI_smc.bin
+lib/firmware/radeon/TAHITI_uvd.bin
+lib/firmware/radeon/TAHITI_vce.bin
 lib/firmware/radeon/TURKS_mc.bin
 lib/firmware/radeon/TURKS_me.bin
 lib/firmware/radeon/TURKS_pfp.bin
+lib/firmware/radeon/TURKS_smc.bin
+lib/firmware/radeon/verde_ce.bin
+lib/firmware/radeon/VERDE_ce.bin
+lib/firmware/radeon/verde_k_smc.bin
+lib/firmware/radeon/VERDE_mc2.bin
+lib/firmware/radeon/verde_mc.bin
+lib/firmware/radeon/VERDE_mc.bin
+lib/firmware/radeon/verde_me.bin
+lib/firmware/radeon/VERDE_me.bin
+lib/firmware/radeon/verde_pfp.bin
+lib/firmware/radeon/VERDE_pfp.bin
+lib/firmware/radeon/verde_rlc.bin
+lib/firmware/radeon/VERDE_rlc.bin
+lib/firmware/radeon/verde_smc.bin
+lib/firmware/radeon/VERDE_smc.bin
```

**Comment by dimkr** [comment]
@Linux-is-king please confirm that this PR is unneeded (doesn't add any firmware files, only replaces some with 3-4 year old firmware), or provide a list of missing firmware files so I can see why kernel-kit/firmware_picker.sh doesn't add them to fdrv.

**Comment by Linux-is-king** [comment]
So I'm not sure if there is more, but dimgrey_cavefish_{ce,me,mec2,rlc,smc,ta,dmcub,mec,pfp,sdma,sos,vcn}.bin is missing. This supports Rx6600 and Rx6600xt

**Comment by dimkr** [comment]
@Linux-is-king Which Puppy release and which kernel are you using?

I have all these and I'm using kernel 6.1.x from https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/3950311726, without any modifications. fdrv is built correctly.

```
$ ls /initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_{ce,me,mec2,rlc,smc,ta,dmcub,m
ec,pfp,sdma,sos,vcn}.bin 
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_ce.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_dmcub.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_me.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_mec2.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_mec.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_pfp.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_rlc.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_sdma.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_smc.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_sos.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_ta.bin
/initrd/pup_f/usr/lib/firmware/amdgpu/dimgrey_cavefish_vcn.bin
```

EDIT: also checked fdrv from the latest jammy64 build with 5.15.x - all these files are present.

**Comment by Linux-is-king** [comment]
I see the following are missing from your list. 
RX6600 /6600xt:

dimgrey_cavefish_

Bellow is a more complete list: 

No GPU listed ? 

R9 Fury, R9 Fury X, R9 Nano, Pro Duo
fiji_

	R9 285, R9 380, R9 380X
tonga_

	R7 M260, R7 M265, R7 M340, R7 M360, R7 M360, R7 M370, R7 M440, R7 M445, R7 M460, R7 M465
topaz_

RX 470, RX 480, RX 570, RX 580, RX 590
POLARIS10_

	RX 460, RX 550 640SP, RX 560
POLARIS11_

RX 540, RX 550
POLARIS12_

Raven 2 Vega Mobile
vega12_

Renoir APU series
renoir_

Cezanne (Zen 3; Renoir)
green_sardine_

RX 5600, RX 5600 XT, RX 5700, RX 5700 XT
NAVI10_

	RX 5500 XT
navi_14

RX 6800, RX 6800 XT, RX 6900 XT
sienna_cichlid_

RX 6700 XT
navy_flounder_

	RX 6600, RX 6600 XT
dimgrey_cavefish_

RX 6400, RX 6500 XT
beige_goby_

RX 7900 XT
I believe is also missing but I can't find the driver ...

**Comment by Linux-is-king** [comment]
Please over look the "no GPU listed line" I was reading from my phone and the format slightly confused me.

**Comment by Linux-is-king** [comment]
Also I didn't really look into where they came from yet, I just knew I had problem with all the new puppies the only one that worked out of the box was FossaPup64 9.5 .
Did we ever find out what's causing the apt problems ? It's an issue in both debian and Ubuntu based puppies. So I done a little more digging and it is actually deleting everything out of the save file when attempting a re-install. I can also confirm that apt is missing from both the save folder as well as the compressed folder. Could this possibly be another install issue ? When was the last time you knew it worked ? There was an update to apt today, not really sure if that caused it. This has been an issue for a week and idk when the last release was before this one.

**Comment by dimkr** [comment]
Please try https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/3926156912. I think something is wrong with the Puppy you're using because the firmware for all models you've listed is present.

**Comment by Linux-is-king** [comment]
Also I haven't really checked if it adds the specific files, but if it appears to work both monitors came on and appeared to be the correct resolution. Where as before with vanilla dpup it did not ( nor any other current official pup..) FossaPup64 worked with only one screen. I have mostly been focus on the apt bug ..

**Comment by dimkr** [comment]
I'm not sure what the "apt bug" is, but let's focus on GPU firmware here and discuss that elsewhere (open an issue?).

Regarding Vanilla Dpup - there's a big difference between 9.3.x and 10.0.x because the latter has a much newer kernel and a much newer amdgpu. If you use 9.3.x with a relatively new AMD GPU, it won't surprise me if it doesn't work.

**Comment by dimkr** [comment]
Opened #3868 (still testing it), which adds some missing files. Besides this short list of files, Puppy's fdrv has all amdgpu firmware that's present in Debian's package. If your GPU still doesn't work after this fix, the kernel you're using is probably too old and doesn't support your GPU. (Specifically, Fossapup is very outdated by now.)

I still don't know what the problem with your GPU is, but the old radeon_firmware package is definitely not going to solve it in jammy64: it doesn't update any firmware and doesn't add any missing firmware.

**Comment by Linux-is-king** [comment]
As stated once I enabled Radeon gpu it worked, before it didn't (with any of the current ( void pup, s15pup, Dpup 9.2 or 9.3 I checked both.. ) so the apt bug I'm working on when puppy is installed to a hard drive (in frugal mode of course) the above issue happens. To sum it up though apt works when puppy is booted to install (to hard drive, I haven't tried USB yet. The bug happens when you power back on, apt no longer works, it isn't in /bin. If you attempt to reinstall it will delete everything in /bin ( and possibly else where I didn't check )... I will download the newest Dpup when I get a chance and let you know though !

**Comment by dimkr** [comment]
I don't know you install Puppy, but make sure you have all SFSs in the ISO.

**Comment by lakshayrohila** [comment]
@Linux-is-king, can you please explain what the "apt bug" is?

**Comment by Linux-is-king** [comment]
Well I explained it above but basically, before you install puppy to a hard drive ( in frugal)  apt works correctly, after the install and reboot, apt is gone, attempting to pull one from the puppy package manager will result in a crash. (It will delete everything in the save folder).

**Comment by dimkr** [comment]
How do you install Puppy? Which Puppy? What version?

**Comment by lakshayrohila** [comment]
> Well I explained it above but basically, before you install puppy to a hard drive ( in frugal) apt works correctly, after the install and reboot, apt is gone, attempting to pull one from the puppy package manager will result in a crash. (It will delete everything in the save folder).

Deletion of `/bin` is not an apt bug, but a PPM problem. PPM is now nearly retired and you cannot expect anything better from it. apt is present in the bdrv.sfs and it seems that your installation didn't copy bdrv.

You can read https://github.com/puppylinux-woof-CE/woof-CE/issues/3639 for more info on the PPM problem.

Whenever bdrv is enabled, PPM is not allowed to install any ubuntu/debian packages because of the same reason.

Please try installing your puppy correctly and it will work.

**Comment by Linux-is-king** [comment]
Hmm 🤔 I will check into the bdrv.sfs. this was a bud on multiple puppies though. I tried an iso without pkg but not ppm... I will try that though thanks!

**Comment by dimkr** [comment]
If you install jammy64 (or any dpup) to a flash drive using bootflash, it will "just work". Other installers can be problematic, at least some of them don't copy the bdrv SFS (where apt is) or don't configure loading of ucode.cpio, among other problems.

**Comment by Linux-is-king** [comment]
So turning bdrv SFS off should fix the problem? I mean I get it, most people probably don't use puppy Linux every day, but at one time I did and honestly I really would like to again. Apparently this is a relatively new feature I didn't know about, thanks for the help guys !

**Comment by dimkr** [comment]
> So turning bdrv SFS off should fix the problem? 

The opposite. apt is inside bdrv. If apt has disappeared, it's probably because the installer you used didn't copy bdrv, or because you removed bdrv.

**Comment by lakshayrohila** [comment]
> So turning bdrv SFS off should fix the problem?

You are misunderstanding this. Please note:

1. **bdrv.sfs contains apt**
2. **PPM is a waste to use as it is un-updated**
3. **you will need to load bdrv.sfs in your Puppy for apt support**
4. **apt (should) always work as expected, and will certainly not cause deletion of files on installation of any package - unlike PPM**

**Comment by Linux-is-king** [comment]
Thanks, I understood though ( when I said "turn it off" I kind figured there would be other things I would have to change as well .. ) I seen that FossaPup64 doesn't use it (and is way less buggy)... I thought it was perhaps an apt problem the whole bdrv thing is kinda new, so it threw me off. I now understand thanks for the help! The bdrv is also causing issues... Anyways thanks for the help !

**Comment by dimkr** [comment]
Fossapup was built 2+ years before bdrv was introduced. If you find any issues with bdrv, please open a separate issue, describe each problem clearly (with details like which Puppy version and steps to reproduce the issue). Everything can be fixed, but it's much easier when it's clear and organized.

**Comment by dimkr** [comment]
If there's any missing amdgpu firmware missing in jammy64 (unlikely), 2255fe8 should fix this. If your GPU still doesn't work with a newly built kernel, it's probably too new for the 5.15.x kernel series.

**Pull request closed without merging**
