### PR TITLE
update powerapplet_tray.c for newer kernels

### PR DESCRIPTION
**Pull request by 01micko**
- in newer kernels CONFIG_ACPI_PROCFS_POWER is removed so the applet fails from linux 5.9 and upwards
- as a result of this the code looking in /proc/acpi/battery is removed because the newer code looking /sys/class/power_supply is sufficient at least back until linux 4.9 and probably much early
- CONFIG_ACPI_PROCFS_POWER was deprecated a decade ago and /sys/class/power_supply/ has been there since before then
- see  https://patchwork.kernel.org/project/linux-acpi/patch/1300844063.31379.4.camel@rui/
- hard coding to BAT0 needs fixing
re #2206

### CODE REVIEW

**Comment by dimkr** [comment]
TODO:
- [x] Update pet.specs
- [ ] Test on ARM
- [x] Remove `pmtype`, always use sysfs and see if it works on both x86_64 and ARM

**Comment by 01micko** [comment]
Code is about half the size now.

`/sys/class/power_supply/` exists in raspi, no battery of course, linux 5.4 so hoping the chromebook's battery is there.

**Comment by dimkr** [comment]
> Code is about half the size now.
> 
> `/sys/class/power_supply/` exists in raspi, no battery of course, linux 5.4 so hoping the chromebook's battery is there.

The TODOs are mostly reminders for me. I think I'll be able to test tomorrow.

**Comment by 01micko** [comment]
Holiday here today, so I had time.. now back to work! (real work )

**Comment by dimkr** [comment]
Building in https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/718962296

**Comment by 01micko** [comment]
Oops - powerapplet shows on my desktop and in qemu! Need a test for that. :beetle:

**Comment by peabee** [comment]
Running: slacko64 #673: Manually run by 01micko

Battery indicator shows in systray on my desktop as Charging 100% even though there is no battery.........

**Comment by 01micko** [comment]
> Running: slacko64 #673: Manually run by 01micko
> 
> Battery indicator shows in systray on my desktop as Charging 100% even though there is no battery.........

yep known bug, fixed soon

**Comment by 01micko** [comment]
Ok, @peabee @dimkr fixed that stupid 'desktop bug' .. pushing fix soon.

**Comment by dimkr** [comment]
Started testing on my ARM laptop, will report back soon.

**Comment by 01micko** [comment]
@dimkr would you like the dubious honour of merging this PR?

**Pull request merged**
