### PR TITLE
Allow the user to manually switch from Xwayland to X.Org

### PR DESCRIPTION
**Pull request by dimkr**
xorg
restart
xwayland

### CODE REVIEW

**Review by 01micko — APPROVED** [review]

**Comment by 01micko** [comment]
Guess what I'm running

xwayland-slacko

**Comment by 01micko** [comment]
Had to unplug a screen though. Cage/Xwayland isn't so good with dual monitors. Radeon graphics hardware, AMD ryzen processor on my desktop.

All build fine in slacko64 once I added the correct deps. Seems to run well and looks nicer somehow. :thinking:

**Comment by dimkr** [comment]
It's a bug, this button shouldn't appear if you don't have it installed. I'll take a look.

EDIT: silly me, I thought it's a bug and you have this button on Slacko, when using X.Org 😊

**Comment by 01micko** [comment]
How can we move forward with the dual monitor issue? Is it a `jwm` bug? Cage, Xwayland? I don't mind testing in dpup or slacko64, or both.

**Comment by dimkr** [comment]
I'll be able to start debugging it on Thursday. I'll start with looking at Cage. Isolating the issue may require building another compositor for comparison, comparing to behavior on a pure Wayland desktop (without the fullscreen Xwayland), trying a window manager other than JWM, and so on.

EDIT: the loop in https://github.com/swaywm/sway/blob/5fd5d6434e9ebbc453dde33bf58fea931ea2975a/sway/config/output.c#L386 is missing after https://github.com/Hjdskes/cage/blob/d1367b1c461de95e3698a8f994b9b89bf2505d40/output.c#L469 - with my problematic TV, this could be related

**Comment by 01micko** [comment]
Ok, perhaps I should start a new issue. And, perhaps I should do some further testing on my slacko64-cage and refine a little and release to the masses with the warning about some graphics setups.

**Comment by dimkr** [comment]
It will probably take some time until we have feature parity with X.Org. Some things don't work, and some don't work well (i.e. mouse acceleration in Steam games).

For now, X.Org should be the default (or the only option) in any Puppy other than dpup, our testing bed 😉

EDIT: created https://github.com/puppylinux-woof-CE/woof-CE/projects/1

**Pull request merged**
