### PR TITLE
add larger fontsizes for old eyes

### PR DESCRIPTION
**Pull request by mrfricks**
larger font sizes were requested in the tahrpup development thread for an older gentleman with poor eye sight

### CODE REVIEW

**Comment by 01micko** [comment]
Not being rude, but was it suggested to him to change screen resolution?

**Comment by mrfricks** [comment]
that's one solution but you lose a lot of screen real estate.
surely the better solution is to use the fontmanager as that's what it's for

**Comment by mavrothal** [comment]
Actually might be useful in more than poor sight. Xorg is bad in handling automatically modern high resolutions screens. 150 is good for a 200dpi screen (XO's for example) and for "retina" you need even more (FD701 is a pain in my macbook). I do not see any issue with the fontmanager UI either, so I would pull if no further arguments.

**Comment by 01micko** [comment]
Ok, tested it out and it works fine. Merging.

**Pull request merged**
