### PR TITLE
"Darn Adobe at it again with their URL changes"

### PR DESCRIPTION
**Pull request by ninaholic**
Courtesy of 01micko :laughing:
http://www.murga-linux.com/puppy/viewtopic.php?p=928449#928449

Might change again soon if Flash 23 npapi goes stable?

### CODE REVIEW

**Comment by ninaholic** [comment]
With .643 it is now Type=2732. I'm just using @rserwin1 pet instead
http://www.murga-linux.com/puppy/viewtopic.php?p=929390#929390

**Comment by wdlkmpx** [comment]
http://arstechnica.com/information-technology/2015/10/firefox-dropping-npapi-plugins-by-the-end-of-2016except-for-flash/

At this point it might be better to send that file to this location:
http://distro.ibiblio.org/puppylinux/pet_packages-noarch/

... and delete the woofce ''getflash" rootfs-package

**Comment by wdlkmpx** [comment]
peebee or somebody should upload rerwin's pet pkg to noarch and add a corresponding entry

i'll delete the rootfs-package if micko doesn't mind.. unless there is another plan..

**Comment by rserwin1** [comment]
I can do that, unless someone else wants to.  Just give me the go-ahead.
rserwin1


wdlkmpx wrote:

**Comment by rserwin1** [comment]
I misunderstood what was being requested.  I cannot do what I offered.
rserwin1

wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
well, the pkg is available for new builds: https://github.com/puppylinux-woof-CE/woof-CE/commit/8f2fd6062e71a8bad1334e3306c2668034868cd7

if the rootfs-pkg is going to stay, maybe an hybrid between the 2 the makes sense, or just replace it with the pet pkg from the repo

**Comment by peabee** [comment]
I think I'm going to replace getflash in my build with a prompt to download the latest .pet from noarch......

**Comment by wdlkmpx** [comment]
so what does micko think.. should i replace the rootfs-pkg with
rerwin's code or maybe should i delete it?...

**Comment by peabee** [comment]
getflash in rootfs-pkg was already at version 1.5.8 so the new version really needs to be 1.5.9.....

**Comment by rserwin1** [comment]
I bumped the version to 1.6 because the method of accessing the adobe 
site got changed to Geoffrey's technique.  I think the 1.5-? format has 
gotten overworked.  My version is based on 1.5-6, without the 
enhancement of the automatic bootup-time that seems to be treated as a 
minor fix, in 1.5-7, which it isn't.

I recommend that we wait for Argolance's integration of the automatic 
feature and new flash into 1.6 and call it 1.7. because it is a 
significant upgrade from 1.5-6 and 1.6.
rserwin1


PB wrote:

**Comment by ninaholic** [comment]
The v1.6.1 pet is working for me, and downloaded and installed flashplayer-24.0.0.194 successfully.
http://www.murga-linux.com/puppy/viewtopic.php?p=936597#936597

I think replacing v1.5.8 one with v1.6.1 in Woof-CE is a good idea now that 24 is "stable", so that when you select "getflash" in ./3builddistro-Z it actually works. :laughing:

**Pull request merged**
