### PR TITLE
javaif: upgrade for openJDK support & new Java packaging structure

### PR DESCRIPTION
**Pull request by rserwin1**
Because Oracle now charges for downloading of its proprietary versions of Java and has removed network (JNLP) support, this fix adds support for the open-source OpenJDK and IcedTea-netx (JNLP) packages.

Each Ubuntu/Debian-based distro includes .deb packages of them for PPM installation.  The Slackos have older such packages that don't seem to work.  However, the AdoptOpenJDK web site appears to provide up-to-date versions of 64-bit JDK/JRE and IcedTea-web packages, which I have made into SFS and .pet files (in my MediaFire account).  They are candidates for wherever woof-CE keeps downloadable SFSs and pets.

I also have an update to the 64-bit DISTRO_PKGS_SPECS-ubuntu-bionic in the form of a patch file, but am unsure how to submit it.  The additions are icedtea-netx and default-jre (which resolves to JDK 11 JRE).  Once submission is worked out, I plan to add them to the other ubuntu and debian SPECS, as well.  Please advise.

The javaif components have tested successfully in both Bionics, DpupBuster64, Xenial and ScPup (using the SFSs).  BionicPup32 has JDK 11 available, so is current as of that LTS release.

I have not updated get_java because it is not needed to allow users to download from Oracle. The open-source packages from AdoptOpenJDK are free to distribute, thus allowing my pre-built SFS/.pet packages.

### CODE REVIEW

**Comment by wdlkmpx** [comment]
> I also have an update to the 64-bit DISTRO_PKGS_SPECS-ubuntu-bionic in the form of a patch file, but am unsure how to submit it. The additions are icedtea-netx and default-jre (which resolves to JDK 11 JRE). Once submission is worked out, I plan to add them to the other ubuntu and debian SPECS, as well. Please advise.

I'm not fan of java, so i'd like to know how big those packages are, should they go in the main sfs or the devx?

For example something that is missing in the devx is valgrind.

Also, it's not a bad idea to keep jre or something in the official pet repos. Currently there is common32 and common64. 

The big packages should be updated once a year probably or maybe every 6 months.

I'll add palemoon and firefox to the common repos.

Also does javaif work in something other than x86? If it doesn't, it probably should be a noarch pet, see
https://github.com/puppylinux-woof-CE/woof-CE-noarch

There is a severe problem with communication and access to the repos, but at least the git noarch is available. 

There's also the need for a common32/64 sfs repo.

**Comment by wdlkmpx** [comment]
So I googled "rerwin openjdk" and found this:

http://www.murga-linux.com/puppy/viewtopic.php?t=116928&sid=ecf989d74a917f44da92d1b3236ae170

The files are here:
https://www.mediafire.com/folder/n1gwntca5dh12/Open_Java

I don't think java should be part of the default builds, but we can certainly use rerwin's packages, this pr will be merged but it will stay open a couple of days while discussion takes place. I'll show you how to upload packages using only words, it may be quite uncomfortable but there's no other way, it's all in the reflexes.

**Comment by wdlkmpx** [comment]
I think I have jre6/jre7/jre8 sfs's somewhere (in a dvd), but indeed, it's no longer possible to download jre https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Oracle vs Google = Kotlin

So it's not legal to redistribute jre .pets/sfs's, right? Java is a dead on the desktop, but I read it's used in some enterprises and the phone market. No kidding, java is dead on the desktop.

I think libreoffice requires jre, it's one of the most absurd things ever, that's why I use Softmaker free office, I used to use WPS office community, there are only x86_64 builds now.

I see the need to have python in the main sfs, because I use youtube-dl, I can't express how much I hate python but I use youtube-dl, so it must be installed. For jre I think I could only use it with jdownloader2, but I haven't used jdownloader2 in a long time.

These are just some random thoughts I have, you might want to share yours.

So the only option is a 64 bit openjdk, right?

**Comment by peabee** [comment]
AlienBob maintains Slackware versions of JDK & JRE....e.g.
https://alien.slackbook.org/blog/april-19-release-of-openjdk-8/

**Comment by wdlkmpx** [comment]
get_java doesn't work in dpup.

ERR    (397) err:=1, wget failed to get package information :: [get_java_version_and_download_url] [/usr/sbin/get_java]

what does that mean?

**Comment by wdlkmpx** [comment]
I guess these packages can be used for common32/common64

http://www.slackware.com/~alien/slackbuilds/openjdk/pkg/14.0/
http://www.slackware.com/~alien/slackbuilds/openjdk/pkg64/14.0/

Unless java uses libpng or something, if it only requires libc and other very basic libs, it should run in all woofce x86 builds.

rerwin might want to convert these packages to .pet.
- openjre-8u222_b10-i486-1alien.txt
- openjdk-8u222_b10-i486-1alien.txz

- openjre-8u222_b10-x86_64-1alien.txt
- openjdk-8u222_b10-x86_64-1alien.txz

And keep an eye on that slackware repo

The SFS's could go to a new repo... sfs/x86_64

But sfs's should be deletable really, when a new version is uploaded. But zczfd\sfskjehnwekj

**Comment by rserwin1** [comment]
In BionicPup64, the deb files total about 39 MB.  That includes 
openjdk--11-jre, which means that the development kit is not there, but 
is a separate package that would be appropriate for devx but can be left 
for users to install.  The runtime part needs to be in the operational 
group, in the main SFS.  I need the IcedTea (JNLP) part for a jnlp 
program that connects me remotely to a remote PC.

My SPEC entries are to make IcedTea/JRE available to developers for 
inclusion in the main SFS, although they could default to "no".

The (64-bit only) AdoptOpenJDK pets and SFS files would qualify for the 
puppy repos.  The Java release schedule is now 2 years for LTS releases 
and 6 months for other releases (now v12).  I think they would be useful 
for older puppies that do not have at least the LTS release 11.

Javaif is architecture-independent.  It is in the skeleton and should 
remain there; it is only 160K, expanded.  Its purpose is to allow use of 
any version or package of Java, by selecting the latest installed 
version and setting up the JAVA_HOME, PATH and LD_LIBRARY_PATH 
environment variables and making adjustments to avoid conflicts between 
multiple installed Javas.  It is now invisible to the user.

The menu item for the Java Control Panel is no longer in the menu for 
Java versions after 8, which is the repo version for pups older than 
BionicPup, as well as ScPup/slacko.  The reason is that the executable, 
jcontrol, has been dropped.  Javaif will enable that menu item only if 
jcontrol is present.  If we declare that 8 is no longer supported by 
Puppy, the menu item and javaif script could be deleted, saving about 
40KB.  But we would need to be sure that the Bionic version of Java 11 
will work in Xenial and ScPup.

I was unaware of alienbob's work on slackware Java packages.  I will 
test them with my javaif fix.

**Comment by rserwin1** [comment]
Before merging this PR, please wait for another commit with an 
additional fix.

**Comment by rserwin1** [comment]
Re: get_java doesn't work in dpup.

The Oracle web pages changed (again) such that the packages cannot be 
found.  I have created a corrected version of get_java but decided that 
using the open-source providers eliminates the need for it to download 
the packages.

Instead, I provided the already-built open-source pet and sfs packages 
and plan to eliminate get_java unless someone wants the part of it that 
makes pets or SFS files from already downloaded tarballs.




wdlkmpx wrote:
> get_java doesn't work in dpup.

**Comment by wdlkmpx** [comment]
Well I think java32/64 should be supported, 32bits is essential:
- jdk8/jre8  - 32/64  (slackware) or maybe only jre8 32
- jdk12/jre12 - 64 (adoptOpenJDK)

I don't know much about java (and am not interested), but is jre11 really needed?

But this support cannot be accumulative, if new packages are uploaded the old packages must be deleted (packages are not deleted from ibiblio and this is wrong), the jdk is too big, it should be only sfs, but there's not a common sfs repo.

The common32/common64 repos are not enabled by default (will fix this now), building an iso is quite easy, only one command.

I will delete get_java.

**Comment by rserwin1** [comment]
Re: but is jre11 really needed?

jre 11 (and jre 15 in 2021) are LTS, so will change every 2 years, for 
those who do not need the very latest release.  I expect that Ubuntu 
will release only the LTS versions.  Jre 12 (and 13 & 14) will have only 
6-month lives, so users would have to update more often, and many 
probably don't care about or need the absolute latest.

So, keeping both the LTS and latest releases seems warranted, for those 
who need to use SFSs.

Re: adding IcedTea and openjre to DISTRO_PKGS_SPECS

With Java "dying on the desktop", I concur that they should not be 
added.  We just need a way to inform users that IcedTea is needed for 
the JNLP support and that it and JRE and JDK are available in the PPM 
repos.  If a developer needs JDK, it can be installed with PPM as 
usual.  The latest JDK SFS file from AdoptOpenJDK could be retained in 
case needed.  Get_java could be modified and renamed to provide only the 
service to build SFSs and .pets from the downloaded AdoptOpenJDK and 
IcedTea packages (because the tarball components install java directly 
to the / level instead of to a sub-directory).

Re: 32-bit JREs

AFAIK, the Ubuntu repo is the only place to obtain the 32-bit JRE 11 and 
Iced Tea.  AdoptOpenJDK does not appear to support 32-bit versions.  I 
suppose the .deb files for them could be made into an SFS file.  
AlienBob's slackware JRE 8 packages would be needed for ScPup/slacko.


wdlkmpx wrote:
> but is jre11 really needed?

**Comment by wdlkmpx** [comment]
Well, oracle compiles stuff that it's supposed to work in all distros.

I'll test alien's packages in slacko 14.0, dpup stretch, slacko 14.2
and probably some other.

I'll see if those packages are self-contained or something, testing is
the only way to know.

This will take a few more days.

**Comment by wdlkmpx** [comment]
rerwin:
- delete the code that deals with the jcontrol menu item
- add your changes to the PKGS_SPECS.. disabled by default.. no|aaa|aaa..

Now talking about java LTS vs java non-LTS.. only LTS should stay in the repos, if you want to add non-LTS releases, they should be deleted when their life cycle finishes..

I see java as a trivial package that is worth deleting when a new revision is uploaded..

**Comment by wdlkmpx** [comment]
I built a new ISO and I see a 'Java Control Panel' in the Utility Menu
Screenshot(3)

You said that after java 8, jcontrol was removed. That's ok. I think that menu item (desktop file) should be provided by a java8 SFS or PET package...

Now, sfsget supports a config file where you can specify a sfs "repo", maybe a new entry in System or Setup could be created by 3builddistro for the i686/x86_64 common sfs repos.

I think it's easy to implement everything, and as I'm not interested in producing sfs's for specific compat distro versions, maybe I am the only who will use and update those repos, so maybe, this could be the place for those sfs repos: https://sourceforge.net/projects/wstuff/

But if we want to make it a bit more difficult, the repos can be placed here:
http://distro.ibiblio.org/puppylinux/sfs/i686
http://distro.ibiblio.org/puppylinux/sfs/x86_64

This is the possible repo for the jre/jdk pet packages:
http://distro.ibiblio.org/puppylinux/pet_packages-common64/

I haven't tested alien's jre8 or jdk8 yet, I guess support for jre8 can be "dropped" from javaif, because a pet or sfs package can fix that..

**Comment by rserwin1** [comment]
I think that the entire /usr/local/bin/javaif script, as well as 
jconsole.desktop, can be deleted because they apply to only release 8 
which has been superseded by release 11, even for 32-bit pups.  The 
newer releases have "jconsole" which seems to act differently from 
jcontrol.  I have not done anything about jconsole.  Release 8 is needed 
for only older pups; I see no need for the javaif GUI for them, as long 
as users can be made aware that JRE is available in the ubuntu repos.

I am attempting to deal with the java icon and related .png files to 
restore the icon for file names in Rox; In 8, links are set for files in 
the JRE package, but are not available later.

Re the "repos", OpenJDK and IcedTea-nets/web are already in the Ubuntu 
repos.  For the Puppy repos, I assume we are talking about the 
AdoptOpenJDK and IcedTea packages that I have built from their 
tarballs.  Those packages are useful as SFS files to avoid using pupsave 
space for the ubuntu .deb expansions.  Maybe get_java should be retained 
to convert the tarballs, although omitting the download part and its 
maintenance every time the download-site code gets changed.  It can 
instruct the users how to get the right download from AdoptOpenJDK.com.  
Maybe get_java does not need a menu item -- users would have to know to 
enter 'get_java' (or whatever it might be renamed to).

I concur that only one non-LTS adoptopenjdk package should be available 
in the Puppy repos.  Or we could not include them because a 
knowledgeable user could simply extract the AdoptOpenJDK non-LTS tarball 
directly into /opt/jre-something.
There are no 32-bit (i686) adoptopenjdk packages.  Maybe alienbob's 
32-bitter will work in ubuntu/debian pups.

Re AdoptOpenJDK compat for specific distros, I find that the package I 
built in ubuntu does work in ScPup.  Let's assume that distro-specific 
versions are not necessary.

Please wait further on merging, so I can fix the icon issue and strip 
out the jconsole code.




wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
I guess the keyword is `recipe`

I have a script called palemoon.sfsbuild.

When I run this script it automatically downloads palemoon for i686/x86_64 and creates a generic i686/x86_64 sfs, both architectures in a single sfs. But it can edited to create separate sfs's.

When I mean generic, it's something that runs in recent woofce isos, woofce has old distros, but even those have upgraded libs (slacko14.0-14.1). This logic only applies to woofce isos produced recently.

When I want to produce an updated palemoon sfs, I simply change the VERSION variable. ie: 28.7.0 -> 28.7.1

My solution for get_java and javaif.. it's a recipe for a sfs, then anybody can edit it an update sfs's... sounds like a good idea, doesn't it?.

Hosting.. sourceforge and/or ibiblio. It depends, bytes will flow

**Comment by wdlkmpx** [comment]
There is also get libreoffice and getflash. flashplayer is an open door to the system, specially with root privileges, something to think about.

I figured out that maybe sourceforge can be used to store sfs files.. that are updated. Just like git, project owners can add people who can edit/upload stuff. That's not something available in ibiblio, where there is only one password, one access, several people using the password. And a high probability of someone deleting the whole thing.

So rather than providing scripts to download, process and repackage stuff, it may be a good idea to provide (by 3builddistro?) a special script to access the special sfs repos which are updated. It's so cool eh?.

For example:

type this:
```
export SFS_REPOS=https://sourceforge.net/projects/wstuff/files/sfs/i686
sfsget
```

```
export SFS_REPOS=https://sourceforge.net/projects/wstuff/files/sfs/x86_64
sfsget
```
So what do you think... ibiblio, sourceforge, sfs repos vs scripts. Just tell me what you want and that will happen, with varying degrees of difficulty depending on your choice...

**Comment by rserwin1** [comment]
The benefit of the get-flash and (especially) get_libreoffice is that 
each user can download directly from the source, instead of depending on 
one of us to keep up with the latest releases and build SFS files of them.

I get the feeling that flashplayer is fading from popularity.  The next 
time the site changes force an update to get_flash, that would be the 
time to switch to making SFS files for it and storing them with the rest 
of the SFS inventory, wherever is easiest to maintain.  LibreOffice 
seems to require little maintenance of the get_libreoffice script.


wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
So what does that mean? Do you want to edit/rewrite get_java? The
openjdk pet and sfs files should be uploaded?, which ones, to which
repo?
Is this ready to be merged?

**Comment by rserwin1** [comment]
I am one commit away from being ready for merging.

I need to add some links to java.svg but do not know how to do that.  I suspect I need to add them in nine places:
  /woof-code/rootfs-packages/pmaterial_icons/usr/share/icons/PMaterial
  /woof-code/rootfs-packages/puppy_flat_icons/usr/share/icons/Puppy Flat
  /woof-code/rootfs-packages/puppy_standard_icons/usr/share/icons/Puppy Standard
and in each of those:
  /16/mimetypes
  /48/mimetypes
  scalable/mimetypes

The relative link to java.svg: application-x-java-jnlp-file.svg

How to I add the links and how are they included in a commit?  I use git-gui.

Regarding get_java, I think it should be deleted.  If it becomes apparent that a AdoptOpenJDK-tarball-to-sfs tool is needed, I can make a command-line tool that does just that.

For the SFS and pet files, the following can be copied from my mediafire account
  http://www.mediafire.com/folder/n1gwntca5dh12/Open_Java
to wherever you want to have the repo for them:
    icedtea-web-1.8.3
    OpenJDK11U-jre-11.0.4_11
    OpenJDK13U-jre-13_33
I doubt we need to include the full JDK packages, if we do not want to support the development of Java programs.  I have removed the "AdoptOpenJDK" part of the names of the SFS files; some of the .pets are unchanged because a change requires a rebuild of the .pet.

Please instruct me on how to contribute the symlinks for .jnlp files.

**Comment by wdlkmpx** [comment]
This is a preview, a pilot episode:

```
export SFS_REPOS=https://sourceforge.net/projects/wstuff/files/sfs/x86_64/
sfsget
```
Most sfs packages I'll upload will be very easy to update, with a .sfsbuild file. You're the maintainer of iced-tea and openjdk. 

Those rootfs-packages have a source:
https://github.com/puppylinux-woof-CE/puppy_icon_theme
https://github.com/puppylinux-woof-CE/puppy_flat_theme
https://github.com/puppylinux-woof-CE/Pmaterial

I don't have write access to those repos, PRs with possible correct changes..
https://github.com/puppylinux-woof-CE/puppy_icon_theme/pull/6
https://github.com/puppylinux-woof-CE/puppy_flat_theme/pull/1
https://github.com/puppylinux-woof-CE/Pmaterial/pull/1

should be a single package.

Commit that adds application-x-java-jnlp-file.svg directly to woofce->rootfs-packages:
https://github.com/puppylinux-woof-CE/woof-CE/commit/20a1e14b27c823f3c915eb71254ca1a5ec737a01

**Comment by rserwin1** [comment]
Ready for merging!

For now, the get_java package should be disabled in- or removed from from DISTRO_PKGS_SPECS files.  I may create a replacement to convert AdoptOpenJDK tarballs into SFS & .pet files.

BTW, the new OpenJDK 13 package causes IcedTea-web to fail; AdoptOpenJDK appears to be aware of the problem and has a proposed fix.  The OpenJDK 12 SFS file should be copied into the SFS repo.  I understand that I am now responsible for making that happen.  Right?

**Comment by wdlkmpx** [comment]
get_java is [completely] gone.

I was about to upload openjdk12-jre but you said only 11 and 13.

Sourceforge's web page allows to you upload and remove files. It just doesn't get any easier than that, it's like mediafire but sfsget works with sourceforge and ibiblio and similar sites.

But if you tell me your sourceforge username I'll see if I can give you permissions.. 

After a few days I'll open a pull request introducing the new sfs repo with a desktop entry in Menu->setup, below "Puppy package manager"?

That will also work in zwn (alternate build system). So basically there's a need for a somewhat big sfs_repo, 'cause zwn needs it.

**Comment by rserwin1** [comment]
I am attempting to verify the merge by building a bionicpup64 distro with the 0setup-3builddistro scripts.  The process ends with a set of warnings that PKG does not exist + a package name, followed by "Please use the 'official' woofce busybox .pet package..".

It is not obvious how to do that.  I tried installing the busybox .pet included in the build (1.31.0) -- assuming that to be the latest -- but got the same result.  I re-ran only 3builddistro -- maybe the file(s) in question are built by an earlier script.

Please tell me how to resolve that dilemma and possibly expand the message to help the user comply.

**Comment by wdlkmpx** [comment]
I have to build a bionicpup64 to see if something's wrong, but I've
always had trouble building upups. Something happens and that's all I
can say.

Trying building a slacko 14.2 64, there is also dpup buster 64, but I
guess it needs many fixes

Overall the default slackos produce what can be called a default build
that is actually the final build.

**Comment by wdlkmpx** [comment]
I built a bionicpup64, it builds fine, but by reading the logs I see
some (or many?) of the changes I made recently do not apply.

In slacko 14.2 64... I used `./build.sh`, a single command.. it
downloaded about 500MB of files and the build was successful, but
caveat emptor

https://github.com/puppylinux-woof-CE/woof-CE/wiki/Builds#bionicpup64

I'll build and provide isos. I guess it's the least I can do.

**Comment by rserwin1** [comment]
Thank you.

I used ./build.sh today to build slacko64 (14.2) 6.9.9.9 successfully.  
I will try it now with bionicpup64.


wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
I rarely test 64bit builds. I uploaded 2 64bit isos, but I haven't tested any of them.

However, I just built a slacko 14.0 64 and found that is broken:

I uploaded a broken eudev/udev 64-bit package that has libudev in /lib rather than in /lib64

This is the offending commit: https://github.com/puppylinux-woof-CE/woof-CE/commit/58e95ceaadaad3456223b8b9f5a8ca32e5b10f77

So probably these distros are broken:
- slacko 14.0 64 - confirmed
- slacko 14.1 64
- slacko 14.2 64

The deb-based pups should not be broken because I see /lib, /usr/lib are added to /etc/ld.so.conf (/lib64, /usr/lib64 are also added). Hmmm. Confusing.

It's been a month and probably no one noticed it haha. Something this serious has not been reported for some reason, and probably no one was able to troubleshoot it and suggest a solution.

All the default builds are automated, no need to mess with anything, and 0 reports about this serious bug? I don't recall anybody mentioning it.

**Pull request merged**
