### PR TITLE
Let the terminal emulator choose the value of TERM

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by 01micko** [comment]
Yes, `TERM` is all over the place.

**Review by 01micko — APPROVED** [review]

**Comment by 01micko** [comment]
This doesn't work.

```
$ env | grep TERM
COLORTERM=truecolor
TERM=xterm-256color
TERMINFO=/usr/share/terminfo
```

I don't know where that is set but it's a clean install and breaks `nano`

```
~$ nano
Error opening terminal: xterm-256color.
```

**Comment by dimkr** [comment]
In dpup, /lib/terminfo/x/xterm-256color exists and `TERM=xterm-256color nano` works.

What ncurses package do you use?

**Comment by 01micko** [comment]
ncurses-6.3-x86_64-1.txz

**Comment by dimkr** [comment]
Does xterm-256color exists anywhere under /?

**Comment by dimkr** [comment]
/usr/share/terminfo/x/xterm-256color should exist, unless there's a package template or something else that removes it.

**Comment by 01micko** [comment]
Not there. /usr/share/terminfo is built into woof. And probably old as.

**Comment by 01micko** [comment]
adding aaa_terminfo-6.3-x86_64-1.txz fixes it at a cost of 890k disk space :roll_eyes: 

```
/usr/share/terminfo/l/lft
/usr/share/terminfo/l/linux
/usr/share/terminfo/l/linux+decid
/usr/share/terminfo/l/linux+sfkeys
/usr/share/terminfo/l/linux-16color
/usr/share/terminfo/l/linux-basic
/usr/share/terminfo/l/linux-c
/usr/share/terminfo/l/linux-c-nc
/usr/share/terminfo/l/linux-koi8
/usr/share/terminfo/l/linux-koi8r
/usr/share/terminfo/l/linux-lat
/usr/share/terminfo/l/linux-m
/usr/share/terminfo/l/linux-m1
/usr/share/terminfo/l/linux-m1b
/usr/share/terminfo/l/linux-m2
/usr/share/terminfo/l/linux-nic
/usr/share/terminfo/l/linux-s
/usr/share/terminfo/l/linux-vt
/usr/share/terminfo/l/linux2.2
/usr/share/terminfo/l/linux2.6
/usr/share/terminfo/l/linux2.6.26
/usr/share/terminfo/l/linux3.0
/usr/share/terminfo/l/lisa
/usr/share/terminfo/l/lisaterm
/usr/share/terminfo/l/lisaterm-w
/usr/share/terminfo/l/liswb
/usr/share/terminfo/l/ln03
/usr/share/terminfo/l/ln03-w
/usr/share/terminfo/l/lpr
/usr/share/terminfo/l/luna
/usr/share/terminfo/n/nansi.sys
/usr/share/terminfo/n/nansi.sysk
/usr/share/terminfo/n/ncr160vppp
/usr/share/terminfo/n/ncr160vpwpp
/usr/share/terminfo/n/ncr160vt100an
/usr/share/terminfo/n/ncr160vt100pp
/usr/share/terminfo/n/ncr160vt100wan
/usr/share/terminfo/n/ncr160vt100wpp
/usr/share/terminfo/n/ncr160vt200an
/usr/share/terminfo/n/ncr160vt200pp
/usr/share/terminfo/n/ncr160vt200wan
/usr/share/terminfo/n/ncr160vt200wpp
/usr/share/terminfo/n/ncr160vt300an
/usr/share/terminfo/n/ncr160vt300pp
/usr/share/terminfo/n/ncr160vt300wan
/usr/share/terminfo/n/ncr160vt300wpp
/usr/share/terminfo/n/ncr160wy50+pp
/usr/share/terminfo/n/ncr160wy50+wpp
/usr/share/terminfo/n/ncr160wy60pp
/usr/share/terminfo/n/ncr160wy60wpp
/usr/share/terminfo/n/ncr260intan
/usr/share/terminfo/n/ncr260intpp
/usr/share/terminfo/n/ncr260intwan
/usr/share/terminfo/n/ncr260intwpp
/usr/share/terminfo/n/ncr260vppp
/usr/share/terminfo/n/ncr260vpwpp
/usr/share/terminfo/n/ncr260vt100an
/usr/share/terminfo/n/ncr260vt100pp
/usr/share/terminfo/n/ncr260vt100wan
/usr/share/terminfo/n/ncr260vt100wpp
/usr/share/terminfo/n/ncr260vt200an
/usr/share/terminfo/n/ncr260vt200pp
/usr/share/terminfo/n/ncr260vt200wan
/usr/share/terminfo/n/ncr260vt200wpp
/usr/share/terminfo/n/ncr260vt300an
/usr/share/terminfo/n/ncr260vt300pp
/usr/share/terminfo/n/ncr260vt300wan
/usr/share/terminfo/n/ncr260wy325pp
/usr/share/terminfo/n/ncr260wy325wpp
/usr/share/terminfo/n/ncr260wy350pp
/usr/share/terminfo/n/ncr260wy350wpp
/usr/share/terminfo/n/ncr260wy50+pp
/usr/share/terminfo/n/ncr260wy50+wpp
/usr/share/terminfo/n/ncr260wy60pp
/usr/share/terminfo/n/ncr260wy60wpp
/usr/share/terminfo/n/ncr7900i
/usr/share/terminfo/n/ncr7900iv
/usr/share/terminfo/n/ncr7901
/usr/share/terminfo/n/ncrvt100an
/usr/share/terminfo/n/ncrvt100wan
/usr/share/terminfo/n/ncsa
/usr/share/terminfo/n/ncsa-m
/usr/share/terminfo/n/ncsa-m-ns
/usr/share/terminfo/n/ncsa-ns
/usr/share/terminfo/n/ncsa-vt220
/usr/share/terminfo/n/ndr9500
/usr/share/terminfo/n/ndr9500-25
/usr/share/terminfo/n/ndr9500-25-mc
/usr/share/terminfo/n/ndr9500-25-mc-nl
/usr/share/terminfo/n/ndr9500-25-nl
/usr/share/terminfo/n/ndr9500-mc
/usr/share/terminfo/n/ndr9500-mc-nl
/usr/share/terminfo/n/ndr9500-nl
/usr/share/terminfo/n/nec5520
/usr/share/terminfo/n/netbsd6
/usr/share/terminfo/n/newhp
/usr/share/terminfo/n/newhpkeyboard
/usr/share/terminfo/n/news-29
/usr/share/terminfo/n/news-29-euc
/usr/share/terminfo/n/news-29-sjis
/usr/share/terminfo/n/news-33
/usr/share/terminfo/n/news-33-euc
/usr/share/terminfo/n/news-33-sjis
/usr/share/terminfo/n/news-42
/usr/share/terminfo/n/news-42-euc
/usr/share/terminfo/n/news-42-sjis
/usr/share/terminfo/n/news-old-unk
/usr/share/terminfo/n/news-unk
/usr/share/terminfo/n/news28
/usr/share/terminfo/n/news29
/usr/share/terminfo/n/next
/usr/share/terminfo/n/nextshell
/usr/share/terminfo/n/northstar
/usr/share/terminfo/n/nsterm
/usr/share/terminfo/n/nsterm+7
/usr/share/terminfo/n/nsterm+acs
/usr/share/terminfo/n/nsterm+c
/usr/share/terminfo/n/nsterm+c41
/usr/share/terminfo/n/nsterm+mac
/usr/share/terminfo/n/nsterm+s
/usr/share/terminfo/n/nsterm-16color
/usr/share/terminfo/n/nsterm-7
/usr/share/terminfo/n/nsterm-7-c
/usr/share/terminfo/n/nsterm-acs
/usr/share/terminfo/n/nsterm-bce
/usr/share/terminfo/n/nsterm-build309
/usr/share/terminfo/n/nsterm-build326
/usr/share/terminfo/n/nsterm-build343
/usr/share/terminfo/n/nsterm-build361
/usr/share/terminfo/n/nsterm-build400
/usr/share/terminfo/n/nsterm-c
/usr/share/terminfo/n/nsterm-c-acs
/usr/share/terminfo/n/nsterm-c-s
/usr/share/terminfo/n/nsterm-c-s-7
/usr/share/terminfo/n/nsterm-c-s-acs
/usr/share/terminfo/n/nsterm-direct
/usr/share/terminfo/n/nsterm-m
/usr/share/terminfo/n/nsterm-m-7
/usr/share/terminfo/n/nsterm-m-acs
/usr/share/terminfo/n/nsterm-m-s
/usr/share/terminfo/n/nsterm-m-s-7
/usr/share/terminfo/n/nsterm-m-s-acs
/usr/share/terminfo/n/nsterm-old
/usr/share/terminfo/n/nsterm-s
/usr/share/terminfo/n/nsterm-s-7
/usr/share/terminfo/n/nsterm-s-acs
/usr/share/terminfo/n/nwp511
/usr/share/terminfo/n/nwp512
/usr/share/terminfo/n/nwp512-a
/usr/share/terminfo/n/nwp512-o
/usr/share/terminfo/n/nwp513
/usr/share/terminfo/n/nwp513-a
/usr/share/terminfo/n/nwp513-o
/usr/share/terminfo/n/nwp517
/usr/share/terminfo/n/nwp517-w
/usr/share/terminfo/u/uniterm
/usr/share/terminfo/u/unknown
/usr/share/terminfo/u/uts30
/usr/share/terminfo/u/uwin
/usr/share/terminfo/v/v3220
/usr/share/terminfo/v/v5410
/usr/share/terminfo/v/vanilla
/usr/share/terminfo/v/vc303
/usr/share/terminfo/v/vc303a
/usr/share/terminfo/v/vc404
/usr/share/terminfo/v/vc404-s
/usr/share/terminfo/v/vc414
/usr/share/terminfo/v/vc415
/usr/share/terminfo/v/versaterm
/usr/share/terminfo/v/vi200
/usr/share/terminfo/v/vi200-f
/usr/share/terminfo/v/vi200-rv
/usr/share/terminfo/v/vi300
/usr/share/terminfo/v/vi300-old
/usr/share/terminfo/v/vi50
/usr/share/terminfo/v/vi500
/usr/share/terminfo/v/vi50adm
/usr/share/terminfo/v/vi55
/usr/share/terminfo/v/vi550
/usr/share/terminfo/v/vi603
/usr/share/terminfo/v/viewdata
/usr/share/terminfo/v/viewdata-o
/usr/share/terminfo/v/viewdata-rv
/usr/share/terminfo/v/viewpoint
/usr/share/terminfo/v/vip
/usr/share/terminfo/v/vip-H
/usr/share/terminfo/v/vip-Hw
/usr/share/terminfo/v/vip-w
/usr/share/terminfo/v/visa50
/usr/share/terminfo/v/vp3a+
/usr/share/terminfo/v/vp60
/usr/share/terminfo/v/vp90
/usr/share/terminfo/v/vremote
/usr/share/terminfo/v/vsc
/usr/share/terminfo/v/vscode
/usr/share/terminfo/v/vscode-direct
/usr/share/terminfo/v/vt100
/usr/share/terminfo/v/vt100+4bsd
/usr/share/terminfo/v/vt100+enq
/usr/share/terminfo/v/vt100+fnkeys
/usr/share/terminfo/v/vt100+keypad
/usr/share/terminfo/v/vt100+pfkeys
/usr/share/terminfo/v/vt100-nav
/usr/share/terminfo/v/vt100-nav-w
/usr/share/terminfo/v/vt100-putty
/usr/share/terminfo/v/vt100-s
/usr/share/terminfo/v/vt100-s-bot
/usr/share/terminfo/v/vt100-vb
/usr/share/terminfo/v/vt100-w
/usr/share/terminfo/v/vt100-w-nam
/usr/share/terminfo/v/vt100nam
/usr/share/terminfo/v/vt102
/usr/share/terminfo/v/vt102+enq
/usr/share/terminfo/v/vt102-nsgr
/usr/share/terminfo/v/vt102-w
/usr/share/terminfo/v/vt125
/usr/share/terminfo/v/vt131
/usr/share/terminfo/v/vt132
/usr/share/terminfo/v/vt200-js
/usr/share/terminfo/v/vt220
/usr/share/terminfo/v/vt220+cvis
/usr/share/terminfo/v/vt220+cvis8
/usr/share/terminfo/v/vt220+keypad
/usr/share/terminfo/v/vt220+pcedit
/usr/share/terminfo/v/vt220+vtedit
/usr/share/terminfo/v/vt220-8bit
/usr/share/terminfo/v/vt220-base
/usr/share/terminfo/v/vt220-nam
/usr/share/terminfo/v/vt220-old
/usr/share/terminfo/v/vt220-w
/usr/share/terminfo/v/vt220d
/usr/share/terminfo/v/vt320
/usr/share/terminfo/v/vt320-k3
/usr/share/terminfo/v/vt320-k311
/usr/share/terminfo/v/vt320-nam
/usr/share/terminfo/v/vt320-w
/usr/share/terminfo/v/vt320-w-nam
/usr/share/terminfo/v/vt320nam
/usr/share/terminfo/v/vt340
/usr/share/terminfo/v/vt400
/usr/share/terminfo/v/vt420
/usr/share/terminfo/v/vt420+lrmm
/usr/share/terminfo/v/vt420f
/usr/share/terminfo/v/vt420pc
/usr/share/terminfo/v/vt420pcdos
/usr/share/terminfo/v/vt50
/usr/share/terminfo/v/vt50h
/usr/share/terminfo/v/vt510
/usr/share/terminfo/v/vt510pc
/usr/share/terminfo/v/vt510pcdos
/usr/share/terminfo/v/vt52
/usr/share/terminfo/v/vt52+keypad
/usr/share/terminfo/v/vt52-basic
/usr/share/terminfo/v/vt520
/usr/share/terminfo/v/vt520ansi
/usr/share/terminfo/v/vt525
/usr/share/terminfo/v/vt61
/usr/share/terminfo/v/vte
/usr/share/terminfo/v/vte+pcfkeys
/usr/share/terminfo/v/vte-2007
/usr/share/terminfo/v/vte-2008
/usr/share/terminfo/v/vte-2012
/usr/share/terminfo/v/vte-2014
/usr/share/terminfo/v/vte-2017
/usr/share/terminfo/v/vte-2018
/usr/share/terminfo/v/vte-256color
/usr/share/terminfo/v/vte-direct
/usr/share/terminfo/v/vwmterm
/usr/share/terminfo/x/x10term
/usr/share/terminfo/x/x68k
/usr/share/terminfo/x/xerox1720
/usr/share/terminfo/x/xerox820
/usr/share/terminfo/x/xfce
/usr/share/terminfo/x/xiterm
/usr/share/terminfo/x/xnuppc
/usr/share/terminfo/x/xnuppc+100x37
/usr/share/terminfo/x/xnuppc+112x37
/usr/share/terminfo/x/xnuppc+128x40
/usr/share/terminfo/x/xnuppc+128x48
/usr/share/terminfo/x/xnuppc+144x48
/usr/share/terminfo/x/xnuppc+160x64
/usr/share/terminfo/x/xnuppc+200x64
/usr/share/terminfo/x/xnuppc+200x75
/usr/share/terminfo/x/xnuppc+256x96
/usr/share/terminfo/x/xnuppc+80x25
/usr/share/terminfo/x/xnuppc+80x30
/usr/share/terminfo/x/xnuppc+90x30
/usr/share/terminfo/x/xnuppc+b
/usr/share/terminfo/x/xnuppc+basic
/usr/share/terminfo/x/xnuppc+c
/usr/share/terminfo/x/xnuppc+f
/usr/share/terminfo/x/xnuppc+f2
/usr/share/terminfo/x/xnuppc-100x37
/usr/share/terminfo/x/xnuppc-100x37-m
/usr/share/terminfo/x/xnuppc-112x37
/usr/share/terminfo/x/xnuppc-112x37-m
/usr/share/terminfo/x/xnuppc-128x40
/usr/share/terminfo/x/xnuppc-128x40-m
/usr/share/terminfo/x/xnuppc-128x48
/usr/share/terminfo/x/xnuppc-128x48-m
/usr/share/terminfo/x/xnuppc-144x48
/usr/share/terminfo/x/xnuppc-144x48-m
/usr/share/terminfo/x/xnuppc-160x64
/usr/share/terminfo/x/xnuppc-160x64-m
/usr/share/terminfo/x/xnuppc-200x64
/usr/share/terminfo/x/xnuppc-200x64-m
/usr/share/terminfo/x/xnuppc-200x75
/usr/share/terminfo/x/xnuppc-200x75-m
/usr/share/terminfo/x/xnuppc-256x96
/usr/share/terminfo/x/xnuppc-256x96-m
/usr/share/terminfo/x/xnuppc-80x25
/usr/share/terminfo/x/xnuppc-80x25-m
/usr/share/terminfo/x/xnuppc-80x30
/usr/share/terminfo/x/xnuppc-80x30-m
/usr/share/terminfo/x/xnuppc-90x30
/usr/share/terminfo/x/xnuppc-90x30-m
/usr/share/terminfo/x/xnuppc-b
/usr/share/terminfo/x/xnuppc-f
/usr/share/terminfo/x/xnuppc-f2
/usr/share/terminfo/x/xnuppc-m
/usr/share/terminfo/x/xnuppc-m-b
/usr/share/terminfo/x/xnuppc-m-f
/usr/share/terminfo/x/xnuppc-m-f2
/usr/share/terminfo/x/xtalk
/usr/share/terminfo/x/xterm
/usr/share/terminfo/x/xterm+256color
/usr/share/terminfo/x/xterm+256color2
/usr/share/terminfo/x/xterm+256setaf
/usr/share/terminfo/x/xterm+88color
/usr/share/terminfo/x/xterm+88color2
/usr/share/terminfo/x/xterm+alt+title
/usr/share/terminfo/x/xterm+alt1049
/usr/share/terminfo/x/xterm+app
/usr/share/terminfo/x/xterm+app+pc
/usr/share/terminfo/x/xterm+decedit
/usr/share/terminfo/x/xterm+direct
/usr/share/terminfo/x/xterm+direct16
/usr/share/terminfo/x/xterm+direct2
/usr/share/terminfo/x/xterm+direct256
/usr/share/terminfo/x/xterm+edit
/usr/share/terminfo/x/xterm+indirect
/usr/share/terminfo/x/xterm+kbs
/usr/share/terminfo/x/xterm+keypad
/usr/share/terminfo/x/xterm+meta
/usr/share/terminfo/x/xterm+noalt
/usr/share/terminfo/x/xterm+noapp
/usr/share/terminfo/x/xterm+noapp+pc
/usr/share/terminfo/x/xterm+nofkeys
/usr/share/terminfo/x/xterm+nopcfkeys
/usr/share/terminfo/x/xterm+osc104
/usr/share/terminfo/x/xterm+pc+edit
/usr/share/terminfo/x/xterm+pcc0
/usr/share/terminfo/x/xterm+pcc1
/usr/share/terminfo/x/xterm+pcc2
/usr/share/terminfo/x/xterm+pcc3
/usr/share/terminfo/x/xterm+pce0
/usr/share/terminfo/x/xterm+pce1
/usr/share/terminfo/x/xterm+pce2
/usr/share/terminfo/x/xterm+pce3
/usr/share/terminfo/x/xterm+pcf0
/usr/share/terminfo/x/xterm+pcf1
/usr/share/terminfo/x/xterm+pcf2
/usr/share/terminfo/x/xterm+pcf3
/usr/share/terminfo/x/xterm+pcfN
/usr/share/terminfo/x/xterm+pcfkeys
/usr/share/terminfo/x/xterm+pcfn
/usr/share/terminfo/x/xterm+r6f2
/usr/share/terminfo/x/xterm+sl
/usr/share/terminfo/x/xterm+sl-twm
/usr/share/terminfo/x/xterm+sm+1002
/usr/share/terminfo/x/xterm+sm+1003
/usr/share/terminfo/x/xterm+sm+1005
/usr/share/terminfo/x/xterm+sm+1006
/usr/share/terminfo/x/xterm+titlestack
/usr/share/terminfo/x/xterm+tmux
/usr/share/terminfo/x/xterm+tmux2
/usr/share/terminfo/x/xterm+vt+edit
/usr/share/terminfo/x/xterm+x10mouse
/usr/share/terminfo/x/xterm+x11hilite
/usr/share/terminfo/x/xterm+x11mouse
/usr/share/terminfo/x/xterm-1002
/usr/share/terminfo/x/xterm-1003
/usr/share/terminfo/x/xterm-1005
/usr/share/terminfo/x/xterm-1006
/usr/share/terminfo/x/xterm-16color
/usr/share/terminfo/x/xterm-24
/usr/share/terminfo/x/xterm-256color
/usr/share/terminfo/x/xterm-65
/usr/share/terminfo/x/xterm-88color
/usr/share/terminfo/x/xterm-8bit
/usr/share/terminfo/x/xterm-basic
/usr/share/terminfo/x/xterm-bold
/usr/share/terminfo/x/xterm-boldso
/usr/share/terminfo/x/xterm-color
/usr/share/terminfo/x/xterm-direct
/usr/share/terminfo/x/xterm-direct16
/usr/share/terminfo/x/xterm-direct2
/usr/share/terminfo/x/xterm-direct256
/usr/share/terminfo/x/xterm-hp
/usr/share/terminfo/x/xterm-ic
/usr/share/terminfo/x/xterm-mono
/usr/share/terminfo/x/xterm-new
/usr/share/terminfo/x/xterm-nic
/usr/share/terminfo/x/xterm-noapp
/usr/share/terminfo/x/xterm-nrc
/usr/share/terminfo/x/xterm-old
/usr/share/terminfo/x/xterm-pcolor
/usr/share/terminfo/x/xterm-r5
/usr/share/terminfo/x/xterm-r6
/usr/share/terminfo/x/xterm-rep
/usr/share/terminfo/x/xterm-sco
/usr/share/terminfo/x/xterm-sun
/usr/share/terminfo/x/xterm-utf8
/usr/share/terminfo/x/xterm-vt220
/usr/share/terminfo/x/xterm-vt52
/usr/share/terminfo/x/xterm-x10mouse
/usr/share/terminfo/x/xterm-x11hilite
/usr/share/terminfo/x/xterm-x11mouse
/usr/share/terminfo/x/xterm-xf86-v32
/usr/share/terminfo/x/xterm-xf86-v33
/usr/share/terminfo/x/xterm-xf86-v333
/usr/share/terminfo/x/xterm-xf86-v40
/usr/share/terminfo/x/xterm-xf86-v43
/usr/share/terminfo/x/xterm-xf86-v44
/usr/share/terminfo/x/xterm-xfree86
/usr/share/terminfo/x/xterm-xi
/usr/share/terminfo/x/xterm-xmc
/usr/share/terminfo/x/xterm1
/usr/share/terminfo/x/xtermc
/usr/share/terminfo/x/xtermm
/usr/share/terminfo/x/xterms-sun
```

**Comment by dimkr** [comment]
> adding aaa_terminfo-6.3-x86_64-1.txz fixes it at a cost of 890k disk space roll_eyes

It's worth it!

This PR makes so many console-based applications appear normal in Puppy.

**Pull request merged**
