### PR TITLE
remove "outdated" support for serial mice

### LINKED ISSUE #1357: Serial mouse
I think the code that deals with serial mice should be deleted.

It doesn't work with the evdev driver, here is a tutorial on how to make it work with the evdev driver
https://wiki.alpinelinux.org/wiki/Serial_Mouse

Written in 2013.

Older (lib)evdev and/or libinput don't work that good with touchpads [by default], but i guess newer versions fix known bugs and so on.

And basically that's the only reason Xorg in puppy runs in 2 modes, with and without evdev. evdev supports touchscreens

And if someone has a serial mouse, they may want to report whether it works with the old mouse xorg driver. Input-wizard doesn't detect if a serial mouse is connected, it just assumes you know you have a serial mouse in a specific port.

I downloaded 
http://distro.ibiblio.org/quirky/quirky6/sources/alphabetical/p/puppyserialdetect-1.1h.tar.bz2
http://distro.ibiblio.org/quirky/quirky6/sources/alphabetical/p/puppyinputdetect-1.1i.tar.bz2

Simplified it and made it detect only serial mice:
[detect_serial_mouse.c.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2967292/detect_serial_mouse.c.zip)

### PR DESCRIPTION
**Pull request by wdlkmpx**
closes #1357

### CODE REVIEW

**Comment by mavrothal** [comment]
Give it a couple of days to [see first](http://www.murga-linux.com/puppy/viewtopic.php?t=115665)

**Comment by wdlkmpx** [comment]
Mechanical mice don't last long. They get dirty very easily. I had a couple mechanical mice and a few optical mice, only one optical mice is working properly, because it's new.

There are people selling serial mice or CRT monitors, CRT monitors increase the electricity bill.. $$$. I have a 17" CRT monitor, 18-23kg, i was thinking of selling it... $0.15.. it should be recycled. Nowadays with really fast smartphones the pc is getting less and less attention.

A few puppy users might still use serial mice, but maybe none of them use a woofce puppy. They are probably using puppy4, 3 or 2.

woofce provides a i686 initrd, leaving out a wide range of ancient hardware, i think mainboards made in 1999+ support i686 cpus ..

**Comment by wdlkmpx** [comment]
After this change there will be no need to set a specific mouse type, it either works or it doesn't. I guess xinput is the app to configure complex "pointers"

I think it's possible to add automatic detection and support for serial mice when puppy is running with xorg evdev and without xorg evdev, but it will be a serious waste of time. 

PS/2 = USB = touchpad
PS/2 = USB = touchpad = touchscreen (with xorg evdev/udev)

USB mice are plug & play... and PS/2 are too. I was suprised when i connected a PS/2 keyboard and it worked... that didn't work in Windows XP for example, WinXP freezes if you connect or disconnect a PS/2 mouse/keyboard.

Serial mice are a thing of the distant past, those selling serial mice, atari consoles, etc... are selling stuff that should be recycled asap.

But who knows, i have like 300 old coins that were made in 1900-1970.. that i can easily sell and get some extra money. It's just old junk that people collect. Taking photos and prepare stuff to sell takes time, that's what bothers me..

**Comment by wdlkmpx** [comment]
coder4837's comment says it all. Even though the serial port is present in not so old pc's, just like the floppy disk, it's gone completely out of use.

**Comment by wdlkmpx** [comment]
I meant "the serial mouse has gone completely out of use", last time i bought a computer mouse i didn't see a ps/2 mouse, only usb mice, and that's what i bought, very cheap .. plug & play

**Comment by s243a** [comment]
I still have a computer that I use a serial mouse with. It is running soup stretch.

I likely won't use any newer version of puppy on it but sometimes older versions of puppy are built with the latest woofCE. 

With regards to serial mice not lasting long I'll say that also USB ports don't last that long and the computer has a limited number of USB ports. Also I'm able to buy second hand serial mice from the goodwill. Puppy is me to to support older hardware. I think that this change is a mistake!

**Comment by wdlkmpx** [comment]
I use a pc made in 2003, how come this change does not affect my psyche? It
brings a s4nse of realization that i never felt before. And i live in A 3rd
world country (s0rt of)... Why does it feel so damn good? Sent from my
expensive phone

**Pull request merged**
