### PR TITLE
Update download page to correct LxPup link

### PR DESCRIPTION
**Pull request by peabee**

### CODE REVIEW

**Comment by mavrothal** [comment]
The merging commit may mess up the git history.
I made the change in the seconf commit. See 5ceef9f2
Closing

**Comment by peabee** [comment]
I wasn't sure where that came from, nor what I'd done to create it!!! 
nor how to remove it!!!

**Comment by mavrothal** [comment]
I do not know how your fork and local clone is set but what I do is after fork I [configure the upstream](https://help.github.com/articles/configuring-a-remote-for-a-fork/) then before I commit my changes I [sync with the upstream] (https://help.github.com/articles/syncing-a-fork/), commit, push to my fork and issue a pull from there.

**Comment by peabee** [comment]
I was doing it all using the github web interface - no cli involved.....

**Comment by mavrothal** [comment]
Old fork maybe?

**Pull request closed without merging**
