### PR TITLE
Update box_splash

### PR DESCRIPTION
**Pull request by rizalmart**
improve gui

### CODE REVIEW

**Comment by wdlkmpx** [comment]
This commit makes `border = false` the default. It also makes the splash a bit more fat

Default behavior:
Screenshot

With border and fg:
Screenshot(1)

Some people might want it to remain slim. Speak up..

Meanwhile I'm merging this.

**Comment by wdlkmpx** [comment]
Unfortunately the change introduced a bug. quicksetup did not show the splash 

After fixing the bug:
Screenshot(2)

I thought. Hmmm. No. I deleted a few lines, does this look good?
Screenshot(3)

ref: https://github.com/puppylinux-woof-CE/woof-CE/commit/4179dbccc1b5b6631637f47f8090e3a5f2603374

**Comment by peabee** [comment]
I think it is now too much margin.....i.e. too "fat"

**Comment by wdlkmpx** [comment]
Does this look better?

[box_splash.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3798377/box_splash.gz)
/usr/lib/gtkdialog/box_splash

**Comment by peabee** [comment]
Better top and bottom but now very unbalanced and too big margins left and right.
Why can't we go back to how it looked before - which was perfectly OK? Balanced margins top, bottom, left and right and not too big.....thanks.

**Comment by peabee** [comment]
Line wrapping has also changed....
How it looked before:
Screenshot

Latest version:
Screenshot(1)

/usr/lib/gtkdialog/box_splash -placement center -bg yellow -fg black -text "REMINDER: Any downloads will have SPOT ownership but any items in /root/spot/Downloads have been changed to ROOT ownership"

**Pull request merged**
