### PR TITLE
Fix #3699

### LINKED ISSUE #3699: (Few)debianutils programs not installed on jammy64.
I encountered with this error today when I tried to install `ksh` through `apt`.

It said that a program named `add-shell` was not found. So the post-configuration was not completed.

Again, when I tried to uninstall `ksh`, it reported error that `remove-shell` was not found.

Both are part of `debianutils`.

According to https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/x86_64/ubuntu/jammy64/DISTRO_PKGS_SPECS-ubuntu-jammy#L98, `debianutils` **is** going to be installed, which it reports to be as well.

Running `apt install --reinstall debianutils` resolves the problem, with some other configurations so that apt does not continue with uninstalling/installing  `ksh` (or other shells).

### PR DESCRIPTION
**Pull request by lakshayrohila**
This PR tries to fix https://github.com/puppylinux-woof-CE/woof-CE/issues/3699. I am currently running a github action to see if this works or not. Till now, 1download has actually downloaded `debianutils`. So maybe this will resolve the error.

### CODE REVIEW

**Comment by dimkr** [comment]
Maybe automate this by changing https://github.com/puppylinux-woof-CE/woof-CE/blob/262b4dae5b46f193753a57d8767fa6483a4748f9/woof-code/0setup#L166?

(#3589 is a good example)

**Comment by lakshayrohila** [comment]
> Maybe automate this by changing
> 
> https://github.com/puppylinux-woof-CE/woof-CE/blob/262b4dae5b46f193753a57d8767fa6483a4748f9/woof-code/0setup#L166
> ?
> 
> (#3589 is a good example)

I'll see to it. First testing if this works. Maybe doing the automation in `woof-distro/x86_64/ubuntu/jammy64/DISTRO_COMPAT_REPOS-ubuntu-jammy` is better. I mean, do all ubuntu based distros' packages follow the same rule (we need to be sure about that)?

**Comment by dimkr** [comment]
> First testing if this works

It won't work, woof-CE doesn't know how to deal with a package that exists in repo A and in repo B (hence the stable version sort+uniq in https://github.com/puppylinux-woof-CE/woof-CE/blob/262b4dae5b46f193753a57d8767fa6483a4748f9/woof-code/0setup#L319).

**Comment by lakshayrohila** [comment]
> It won't work, woof-CE doesn't know how to deal with a package that exists in repo A and in repo B (hence the stable version sort+uniq in
> 
> https://github.com/puppylinux-woof-CE/woof-CE/blob/262b4dae5b46f193753a57d8767fa6483a4748f9/woof-code/0setup#L319
> ).

Remove updates repo then?

**Comment by dimkr** [comment]
woof-CE doesn't know how to deal with the -updates and -security repos, unless it's done the way it's done by 0setup. If package A is version 1.2.3 and updates has 1.2.3-1 and security has 1.2.3-2, 0setup won't pick the right package unless the three repos are combined into one package list, with one version (= the highest) for each package.

**Comment by lakshayrohila** [comment]
@dimkr, I think this currently goes over my head, so closing this draft. + is this the real issue for debianutils not being installed, or do you think there must be something else behind it?

**Comment by dimkr** [comment]
> do you think there must be something else behind it?

I don't have a quick answer, but I do know that we don't support /etc/shells and many things in Puppy assume that /bin/sh is bash.

**Pull request closed without merging**
