### PR TITLE
Add 5.15.x kernels based on Debian 5.15.3-1

### PR DESCRIPTION
**Pull request by dimkr**
I checked the diff against 5.10.x. F2FS and NTFS drivers are now enabled and built-in, and all other changes are inherited from Debian.

Amazon Linux 2022 uses 5.15.x, and Slackware 15.0 will probably use it:

```
k/kernel-source-5.15.0-noarch-1.txz: Upgraded.
       We'll be using 5.15.x in the 15.0 release, and it's working well here, so
       let's just start it right out in the main tree rather than in /testing.
```

Hopefully, Ubuntu 22.04 will use it too, because that will probably extend the maintenance window of this kernel branch (5.10.x is maintained until 2026, but currently, 5.15.x projected EOL is 2023).

- [x] Disable CONFIG_DEBUG_INFO and check artifact size
- [x] https://github.com/sfjro/aufs5-standalone/issues/6
- [x] Test Slacko 8.x

### CODE REVIEW

**Review by 01micko — COMMENTED** [review]
MMC looks ok :smile:

**Comment by peabee** [comment]
Good idea to provide the latest LTS kernel.
My only concern is that this is presumably built with similar Debian configs as 5.10 and these configs do not seem to support wireless keyboards during the boot sequence as well as previously built "Puppy" kernels.... this support is needed when selecting between multiple save areas
I will check this later today

**Review by peabee — COMMENTED** [review]
Good idea to provide the latest LTS kernel.
My only concern is that this is presumably built with similar Debian configs as 5.10 and these configs do not seem to support wireless keyboards during the boot sequence as well as previously built "Puppy" kernels.... this support is needed when selecting between multiple save areas
I will check this later today

**Comment by peabee** [comment]
For information:
Debian probably never requests terminal input during the boot sequence so their kernel config does not build-in the drivers for wireless keyboards......
For frugal installs Puppy creates *initmodules.txt during the creation of the save area and this contains 6 modules that have to be pre-loaded to activate wireless keyboards:
hid_logitech_hidpp,hid_logitech_dj,hid_generic,usbhid,hid,uhci_hcd

A problem only arises if multiple save areas are present and the *initmodules.txt has not been created.

Puppy kernels traditionally have:
HID support:
CONFIG_HID=y
CONFIG_HID_GENERIC=y
CONFIG_HID_LOGITECH_DJ=y
CONFIG_HID_LOGITECH_HIDPP=y
CONFIG_USB_UHCI_HCD=y
CONFIG_USB_HID=y

so don't need the *initmodules.txt file for wireless keyboards

**Comment by dimkr** [comment]
> CONFIG_HID=y
> CONFIG_HID_GENERIC=y
> CONFIG_HID_LOGITECH_DJ=y
> CONFIG_HID_LOGITECH_HIDPP=y
> CONFIG_USB_UHCI_HCD=y
> CONFIG_USB_HID=y

Done

**Comment by dimkr** [comment]
aufs5.15 is currently broken for > 5.15.4, because `update_time()` has been renamed to `inode_update_time()` (the patch doesn't apply, see https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/fs/inode.c?id=v5.15.5&id2=v5.15.4 and https://github.com/sfjro/aufs5-standalone/blob/e911f0dff5056bd8c2acea57db032ee20e4105e7/aufs5-base.patch#L101).

Let's wait for @sfjro to fix this (I can help).

**Comment by sfjro** [comment]
Dima Krasner:
> update_time() has been renamed to inode_update_time() (see https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/fs/inode.c?id=v5.15.5&id2=v5.15.4), breaking the patch:

Thanx for the report.
I will make and release new aufs5.15.5 branch in a week or two.
If you're in a hurry and can't wwait for my release, try backporting the
commit in aufs5.x-rcN branch,
	cf1efc74d5cf4 2021-11-18 aufs: v5.16-rc1, use inode_update_time helper

J. R. Okajima

**Comment by 01micko** [comment]
Building 5.15.5 in slacko64-8x now after editing `fs/aufs/vfsub.h` and got an _unrelated_ harmless reject: EDIT: hmm not harmless. Build failed.



From the log:

```
Adding Aufs to the kernel sources

patch -N -p1 < aufs5-kbuild.patch
patching file fs/Kconfig
patching file fs/Makefile

patch -N -p1 < aufs5-base.patch
patching file MAINTAINERS
patching file drivers/block/loop.c
Hunk #1 succeeded at 798 (offset -13 lines).
patching file fs/dcache.c
patching file fs/fcntl.c
patching file fs/inode.c
Hunk #1 FAILED at 1782.
1 out of 1 hunk FAILED -- saving rejects to file fs/inode.c.rej
patching file fs/namespace.c
patching file fs/splice.c
patching file fs/sync.c
patching file include/linux/fs.h
Hunk #3 succeeded at 2617 (offset 2 lines).
Hunk #4 succeeded at 2781 (offset 2 lines).
patching file include/linux/lockdep.h
patching file include/linux/mnt_namespace.h
patching file include/linux/splice.h
patching file kernel/locking/lockdep.c
WARNING: failed to add some Aufs patches to the kernel sources.
Check it manually and either CRTL+C to bail or hit enter to go on

patch -N -p1 < aufs5-standalone.patch
patching file fs/dcache.c
patching file fs/exec.c
patching file fs/fcntl.c
patching file fs/file_table.c
patching file fs/inode.c
Hunk #1 succeeded at 1751 with fuzz 2 (offset -37 lines).
patching file fs/namespace.c
patching file fs/notify/group.c
patching file fs/open.c
patching file fs/read_write.c
patching file fs/splice.c
patching file fs/sync.c
patching file fs/xattr.c
patching file kernel/locking/lockdep.c
patching file kernel/task_work.c
patching file security/security.c

patch -N -p1 < aufs5-mmap.patch
patching file fs/proc/base.c
Hunk #1 succeeded at 2189 (offset 3 lines).
patching file fs/proc/nommu.c
patching file fs/proc/task_mmu.c
patching file fs/proc/task_nommu.c
patching file include/linux/mm.h
patching file include/linux/mm_types.h
patching file kernel/fork.c
patching file mm/Makefile
patching file mm/filemap.c
Hunk #1 succeeded at 3349 (offset -1 lines).
patching file mm/mmap.c
patching file mm/nommu.c
patching file mm/prfile.c
Resetting the minor version number
Reducing the number of consoles and verbosity level
Cleaning the kernel sources
make olddefconfig
Creating the kernel headers package
=================== WARNING ===================
Since Linux 5.5, 'make headers_check' is no-op,
and will be removed after Linux 5.15 release.
Please remove headers_check from your scripts.
===============================================
```

.. and the warning about `make headers_check`

**Comment by sfjro** [comment]
Mick Amadio:
> Building 5.15.5 in slacko64-8x now after editing `fs/aufs/vfsub.h` and got an _unrelated_ harmless reject:

Ah, you've replaced update_time() by inode_update_time() manually.  It
is OK.


> patch -N -p1 < aufs5-base.patch
	:::
> patching file fs/inode.c
> Hunk #1 FAILED at 1782.
> 1 out of 1 hunk FAILED -- saving rejects to file fs/inode.c.rej

That is my bad.
I believe I made a mistake in generating aufs5.15/aufs5-base.patch.  I
will fix it in next release.


> Resetting the minor version number
> Reducing the number of consoles and verbosity level
> Cleaning the kernel sources
> make olddefconfig
> Creating the kernel headers package
> =================== WARNING ===================
> Since Linux 5.5, 'make headers_check' is no-op,
> and will be removed after Linux 5.15 release.
> Please remove headers_check from your scripts.
> ===============================================
> ```
>
> .. and the warning about `make headers_check`

I am afraid aufs is not related to this.
Does it come from your build script or something?

Thanx for the report.


J. R. Okajima

**Comment by 01micko** [comment]
@sfjro no problem with `make headers_check`; that is our problem. Thanks for your attention :smiley:

**Comment by dimkr** [comment]
> Thanx for the report. I will make and release new aufs5.15.5 branch in a week or two

Thank you @sfjro!

**Comment by peabee** [comment]
aufs for 5.10.82 is also affected by the same problem apparently...............

**Comment by sfjro** [comment]
PB:
> aufs for 5.10.82 is also affected by the same problem apparently...............

Yes, I already started testing aufs5.10.82 on my side.

https://github.com/sfjro/aufs5-standalone/issues/6#issuecomment-980475162


J. R. Okajima

**Comment by sfjro** [comment]
o news
- aufs5.10.82 and aufs5.15.5 branches just to follow the changes in
  mainline/stable
- aufs5.15, restore missing "rt.patch"

J. R. Okajima

----------------------------------------
- aufs5-linux.git
  aufs5.10.82 and aufs5.15.5 branches

- aufs5-linux.git#aufs5.15
  restore missing "rt.patch"

- aufs5-linux.git#aufs5.x-rcN
  just to follow linux-v5.16-rc2

- aufs5-standalone.git
  ditto

- aufs-util.git
  nothing

**Comment by dimkr** [comment]
Thank you @sfjro! Both fixes applied

**Comment by 01micko** [comment]
5.15.5 builds fine for me. Thanks @sfjro and @dimkr

**Comment by 01micko** [comment]
Something wrong with NVME support (builtin?) but working fine on spinning disk. May need to tweak `.config`.

ver

**Comment by dimkr** [comment]
> Something wrong with NVME support (builtin?) but working fine on spinning disk. May need to tweak `.config`.
> 
> ver

CONFIG_BLK_DEV_NVME=m, probably needs to be CONFIG_BLK_DEV_NVME=y. True for 5.10.x as well.

**Comment by 01micko** [comment]
> CONFIG_BLK_DEV_NVME=m, probably needs to be CONFIG_BLK_DEV_NVME=y. True for 5.10.x as well.

Yes, anything puppy boots off _needs_ to be builtin, including `fs`.

**Comment by CollaboratorGCM** [comment]
Hi @dimkr 

Is there any chance you could enable your personal distro here in WoofCE to allow it booting from its ISO file on a SG2D USB stick, like the other WoofCE PUPs. I would like to evaluate.

Please and Thanks, if you can.

**Pull request merged**
