### PR TITLE
Partial: add support for .xbps files

### PR DESCRIPTION
**Pull request by peabee**
PARTIAL Add support for .xbps files
Cannot:
upload:  /root/.config/rox.sourceforge.net/OpenWith/.application_x-voidlinux-package

or add: 
/usr/share/icons/Puppy Flat/scalable/mimetypes/application-x-archlinux-package-zst.svg
/usr/share/icons/Puppy Flat/scalable/mimetypes/application-x-voidlinux-package.svg
/usr/share/icons/Puppy Standard/scalable/mimetypes/application-x-archlinux-package-zst.svg
/usr/share/icons/Puppy Standard/scalable/mimetypes/application-x-voidlinux-package.svg

all 4 as links to application-x-compressed.svg

n.b. Can no longer do cli push:
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/peabee/woof-CE.git/'

### CODE REVIEW

**Comment by peabee** [comment]
Sorry - did not mean to merge without a review - but it never asked me so to do.............

**Comment by 01micko** [comment]
> Sorry - did not mean to merge without a review - but it never asked me so to do.............

'it' never does.

This commit is enormous! What's in it?

BTW; @github has been nagging on about 2FA for over a year.

**Comment by peabee** [comment]
Shouldn't be "enormous" - unless I've done something wrong??
It adds in support for Void Linux .xbps packages........... similar to what we already have for Arch Linux .zst packages.
The files changed are in this .pet:
[z_xbps_support.pet-false.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/7963168/z_xbps_support.pet-false.gz)

On 2FA...... I haven't needed to use the cli interface for over a year - I haven't seen any "nags" - I can do most of usual activities through the web interface but uploading hidden DOT is not possible other than by cli. If somebody could upload the files above that would be appreciated.

I can revert the commit if you want?

**Comment by 01micko** [comment]
Nah, not that bad, just 248df11 was a strange one. 

Usually, you just update your fork through github, then make a _new_  branch. That would have avoided that commit.

> On 2FA...... I haven't needed to use the cli interface for over a year - I haven't seen any "nags"

Did you check the email that you registered on github with? May have landed in your spam. I got a heap of them and changed to 2FA early last year.

> The files changed are in this .pet:

So, you need `root/.config` merged? Is that correct? (from said pet). Direct to `woof-code/rootfs-skeleton`? Or other?

**Comment by 01micko** [comment]
Ah, also, you **can't** update _Puppy *_ icons here. They _must_ be updated in the icon repos respectively!

It's pretty simple, just add the string `application-x-voidlinux-package.svg` (or whatever it may be) to the end of the icon string you want to link to in _every_ size class in `theme.conf`.

eg:
```
16/mimetypes application-x-compressed.svg application-x-bzip.svg application-x-rar.svg application-7zip.svg application-x-7z-compressed.svg application-x-archive.svg application-x-xz.svg application-x-gzip.svg application-gzip.svg package-x-generic.svg package.svg gz.svg application-x-zstd.svg application-x-archlinux-package-xz.svg application-x-archlinux-package-zstd.svg
```
just tack on ` application-x-voidlinux-package.svg`

**Comment by peabee** [comment]
To Other:
/rootfs-packages/jwm_config/root/.config/rox.sourceforge.net/OpenWith

**Comment by 01micko** [comment]
> To Other: /rootfs-packages/jwm_config/root/.config/rox.sourceforge.net/OpenWith

Ok :)

(check my edit above too)

**Comment by dimkr** [comment]
> I can do most of usual activities through the web interface b

This is such a bad idea ... the web interface is horrible. Many woof-CE commits have the message "update x" and random whitespace changes because of it.

I don't understand why it exists, when some IDEs (like VS Code) make it so easy to use GitHub with almost zero git knowledge. And you don't have to install an IDE - you can use something like https://gitpod.io/#https://github.com/puppylinux-woof-CE/woof-CE. IMHO, it's a much better web interface for GitHub.

**Comment by 01micko** [comment]
@peabee 

In light of this situation, **please do not merge anything** without prior review.

While there isn't a big mess to clean up here there is still _some_ mess,

- remove symlinks in Puppy * icon themes
- add hidden dirs necessary to complete PR

That takes time and I know _my_ time as well as others' time is limited.

**Comment by 01micko** [comment]
@peabee 

What about PMaterial icons? re [#4](https://github.com/puppylinux-woof-CE/puppy_flat_theme/pull/4) and [#11](https://github.com/puppylinux-woof-CE/puppy_icon_theme/pull/11#event-5974879178)

**Comment by 01micko** [comment]
AND

What about 

- 16
- 22
- 24
- 32
- 48
- 64

???

Please add all @peabee

**Comment by peabee** [comment]
I think ? only scalable are needed to display correctly in roxfiler..........
what would all the others be used for?

PMaterial done

**Comment by 01micko** [comment]
They are all needed - and these aren't only for rox filer.

EDIT: already done

**Comment by 01micko** [comment]
There is a _big_ problem with this commit. `./merge2out` thinks that 'common' is an architecture!

bug

I'm going to remove those directories @peabee as this is a bad bug. I notice there are large differences in the containing files - you'll have to fix those later in another PR.

**Pull request merged**
