### PR TITLE
Update delayedrun

### PR DESCRIPTION
**Pull request by ASRIedu**

### CODE REVIEW

**Comment by dimkr** [comment]
Also, "update $name_of_file" is a very bad commit message. We already know you've changed delayedrun according to the commit log. The commit message should contain high-level description of the changeset (i.e "fixed an audio device recognition issue").

I don't understand why so many woof-CE commits have messages in this weird format and who started this mess. It's really hard to keep up with changes by reading the commit log, when all commits have useless descriptions that tell nothing. Merging stuff from forks to testing became a nightmare.

**Comment by mavrothal** [comment]
> Also, "update $name_of_file" is a very bad commit message. We already know you've changed delayedrun according to the commit log. 
- snip -
> I don't understand why so many woof-CE commits have messages in this weird format and who started this mess. 

This is the default github commit message when you edit a file through the github web interface. 
I wonder if it can be changed or eliminated.

**Comment by ASRIedu** [comment]
@ mavrothal
Sorry for unnecessary comments in the script. In the future, I will do better.
Regarding the addition of a '&' in the script, I'll wait until next week to answer you. Until Sunday my schedule is full, starting on Monday I will be on vacation.

@ dimkr
You are right. Now I'm bringing more time writing commit messages.

Regards

**Comment by ASRIedu** [comment]
Sorry for the inconvenience, I cancel my request.
To be continued...
Regards

**Pull request closed without merging**
